### ISSUE TITLE
support for https_proxy env variables?

### ISSUE THREAD

**Issue by flixr** [aws/aws-sdk-cpp#1049]
It seems that simply setting a proxy via (standard curl) env variables (`http_proxy`, `https_proxy`) is not supported/working.

Is this intended, if yes, why?

**Comment by flixr** [comment]
That is unfortunate and a bit strange considering that you can set other things like the key via env variables...
There would always be the possibility to specify it manually to override the env vars...
But ok.

**Comment by singku** [comment]
We will work out a better way to honor environment variables that curl understands.

**Comment by sahil1105** [comment]
Hi, just wanted to check if there are any plans to implement a way to honor the environment variables?

**Comment by Fuuzetsu** [comment]
It'd be extremely useful if there was some `AWS_SDK_DONT_EMPTY_CURLOPT_PROXY` or some-such. Without it, user applications have to do something like:

* scour http_proxy, https_proxy and on variables that `libcurl` already knows about and honours: https://curl.se/libcurl/c/CURLOPT_PROXY.html
* parse these into hostname and port
* pass these to AWS SDK via the client config
* have AWS SDK set the CURLOPT_PROXY

This seems like a lot of error-prone work to tell curl about something it knew how to read in the first place.

>We have some customer use cases that don't want their applications' proxy settings to be affected by env variables and most of the time they need to manually specify proxy authentications in their code.

It seems they could set CURLOPT_PROXY="" and that'd be it. That's a lot easier than rest of the world having to parse HTTP_PROXY and other friends.

The issue is compounded when you don't have easy way to modify and deploy an application that already uses AWS SDK.
