### ISSUE TITLE
Can there be situations where GetObject returns corrupted data?

### ISSUE THREAD

**Issue by rahul003** [aws/aws-sdk-cpp#1066]
Can there be situations where GetObject returns corrupted data? Is it the responsibility of the caller to verify md5 hash or something like that?

**Comment by JonathanHenson** [comment]
Yes, anything, anytime can be corrupted (especially over a network). You do however, have access to crc32c (it’s part of the aws-checksums package. I’d recommend running crc32c over the body and adding the checksum to your metadata. Then run it after download and check that they match. It’s hardware accelerated and orders of magnitude faster than md5.

**Comment by rahul003** [comment]
Thanks for the reply. If I already have my data on S3, and I'm trying to read it by using GetObject in my code, what precautions can I take? Is there a sort of hash that comes with the request that I can use?

**Comment by JonathanHenson** [comment]
There’s etag, and it’s sometimes the md5 but IIRC, it’s not always the md5.

**Comment by marcomagdy** [comment]
Yes. etag is your best bet if the object is already in S3. Otherwise, you can use PutObjectRequest::SetContentMD5(..) when uploading it.

The etag is usually the MD5 of the content. However, there're situations when it's not. Those situations are outlined in the common-headers documentation https://docs.aws.amazon.com/AmazonS3/latest/API/RESTCommonResponseHeaders.html

**Comment by lsong0905** [comment]
As mentioned in https://github.com/aws/aws-sdk-java/issues/970
If we download a part at a time after multi-uploaded an object, is the MD5 of the part in the ETag header same as the locally calculated MD5 checksum of the part? 
Plus, does it matter which type of SSE algorithm being used when uploading the part?
