### ISSUE TITLE
questions about the definition of global of InitAPI/ShutdownAPI

### ISSUE THREAD

**Issue by sunhubs** [aws/aws-sdk-cpp#1093]
I just want to confirm how to use the InitAPI/ShutdownAPI in my scenario.
My platform is CentOS, g++ version is 4.9. i will use sqs, s3, dynamodb and so on.
my service is a plugin service, there is a framework program with different dynamic library(so files), every service will use sqs, s3 or use sqs, dynamodb or other aws client sdks.
my question is where I should call the initAPI/ShutdownAPI for globally usage, in the frame work program? or just every dynamic library internally?

**Comment by sunhubs** [comment]
@JonathanHenson

**Comment by webbnh** [comment]
This seems like a common/recurring problem.

Perhaps it would be handy/helpful if there were an API which allowed the calling code to test whether `InitAPI()` had already been called.  This would allow it to skip the calls to `InitAPI()` and `ShutdownAPI()`, which would cover most of the cases.

Or, better yet, perhaps `InitAPI()` could be made _idem potent_, so that it's safe to be called repeatedly.  Of course, that would only help if `ShutdownAPI()` were similarly modified, so that calling it only had an effect if the number of calls to it matched the number of calls to `InitAPI()`.

**Comment by singku** [comment]
Duplicate to #456
