### ISSUE TITLE
Plugging into the std::error_code framework

### ISSUE THREAD

**Issue by psalvaggio** [aws/aws-sdk-cpp#1118]
### What platform/OS are you using?

Fedora

### What compiler are you using? what version?

GCC8

### What's your CMake arguments?

N/A

### Can you provide a TRACE level log? (sanitize any sensitive information)

N/A

Has there been any thought to hooking up the AWS error mechanism into the std::error_code framework? Currently, I ran into 2 issues when trying to do this on my end.

1. Error enums start at 0, which is reserved for success. The workaround here was to add 1 to the enum value in `make_error_code` and subtract it back off in the `error_category`. Not a great solution for when you want to compare the value of the error code, but it does work.

2. There isn't really a way to through the SDK to map an error enum value (like S3Errors) to a string message, as that is normally stored in the `AWSError` object. I can certainly list out the strings by hand, but this isn't a great solution.

**Comment by singku** [comment]
Thanks.
1. We thought about this to use 0 as reserved for Success. But we defined errors in error enum with all enum values should represent different errors. And the Outcome template is defined with either Error or Result, means once you get Error back, doesn't matter if the error_code 0 or not.

2. Error messages are decided by different services, same error code in a service can emit different error messages. That's why we don't have a mapping from error code to message.

**Comment by KaibaLopez** [comment]
Closing, feel free to reach out if there's any other related questions.
