### ISSUE TITLE
[question] about new aws-sdk-cpp dependencies (aws-c-event-stream/etc)

### ISSUE THREAD

**Issue by crusader-mike** [aws/aws-sdk-cpp#1124]
#### Compiler: MSVC 2017

I've decided to crawl out my cave and start using `vcpkg`... also bump aws-sdk-cpp version to 1.7.80 in my projects. It looks like we have new dependencies:
```
c:\vcpkg>vcpkg install aws-sdk-cpp[core,s3]:x64-windows --dry-run
The following packages will be built and installed:
  * aws-c-common[core]:x64-windows
  * aws-c-event-stream[core]:x64-windows
  * aws-checksums[core]:x64-windows
    aws-sdk-cpp[core,s3]:x64-windows
```

Can someone comment on these libraries and why do I need them to perform simple uploads to S3:
- aws-c-common (looks like some core functionality? smth about non-blocking?)
- aws-c-event-stream (this one is a mystery to me)
- aws-checksums (looks like just a collection of checksum routines)

@JonathanHenson, may be you could chime in?

**Comment by marcomagdy** [comment]
S3 introduced a new feature dubbed [S3-Select](https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectSELECTContent.html) which requires special framing of the response (see details in the link). The decoding of those binary frames is implemented in those C libraries so they can be used by other software components in AWS. Instead of reinventing the wheel, we took a dependency on them.

**Comment by marcomagdy** [comment]
It's worth pointing out that the binary format described above (named event-streams) is and will be used by other services going forward. That's why they're part of the aws-cpp-sdk-core library.

**Comment by crusader-mike** [comment]
Huh... neat. Thank you, Marco.
