### ISSUE TITLE
Is it possible to not call instance metadata when region is supplied to S3Client?

### ISSUE THREAD

**Issue by d-shi** [aws/aws-sdk-cpp#1222]
### What platform/OS are you using?
Ubuntu 16.04

### Which version of the SDK?
1.7.111

### What compiler are you using? what version?
gcc 7.4.0

### What are your CMake arguments?
```
-DCPP_STANDARD=17
-DBUILD_ONLY='kinesis;core;s3;transfer'
-DCMAKE_BUILD_TYPE=RelWithDebInfo
-DENABLE_TESTING=OFF
```

### Can you provide a TRACE level log? (sanitize any sensitive information)
Not relevant here.

It seems that right now when using the S3Client, it calls `DefaultAWSCredentialsProviderChain` -> `InstanceProfileCredentialsProvider` -> `EC2InstanceProfileConfigLoader`, which triggers a call to instance metadata at `/latest/meta-data/placement/availability-zone` to get the region. However, we are already supplying the region to the S3Client, so this call seems redundant.

I am trying to implement kiam, which by default blocks all calls to instance metadata. It would be ideal to not have to whitelist this metadata path in kiam, especially since it seems unnecessary when we are already supplying the region. Would it be possible to suppress this metadata call when the region is supplied to the client, or is there another requirement for this call that I'm missing? Any guidance is greatly appreciated.

**Comment by KaibaLopez** [comment]
Hi @d-shi,
I'd have to look a bit further into what we are using the profile region for in the metadata instance, and if you can think of a better way of getting the region in the EC2InstanceProfileConfigLoader we'll be happy to take a look at it, as always, we are open for contributions.

For now though,  you can avoid using that call by giving s3client a credential provider, that way it won't go through the DefaultAWSCredentialsProviderChain and more importantly you won't hit InstanceProfileCredentialsProvider.
You could, in the case that you are using a .config file for example, do something like:
```
Aws::Client::ClientConfiguration config("default");
auto provider = Aws::MakeShared<Aws::Auth::ProfileConfigFileAWSCredentialsProvider>("ConfigFile");
auto s3_client = std::make_shared<Aws::S3::S3Client>(provider,config);
```
Or you could create your own implementation of the credential provider, we have a template to use as a base too.
The other option, and this would be more of a feature request (although a reasonable one), we could look into having an s3client constructor that takes a CredentialsProviderChain, so that you could potentially create your own and assign that (maybe only avoid some providers).
It all really depends on your implementation though and I may have gone on a tangent already, let me know what you think.

**Comment by d-shi** [comment]
Hi @KaibaLopez,

Thanks for you response. In our case we are actually relying on instance credentials, and not getting credentials from a config file. It seems to me that region is not actually required to get the instance credentials, but rather region is being used to set up the profile. You can see credentials get set up before the call to get region is made here: https://github.com/aws/aws-sdk-cpp/blob/d92009b3b5be057d8e22a19f214a68b60ee9a70d/aws-cpp-sdk-core/source/config/AWSProfileConfigLoader.cpp#L349

I am wondering if it is possible for the region to be passed down to the profile from the `ClientConfiguration`, since we are setting it there. If it is not specified in the `ClientConfiguration` then the CredentialsProvider should look up the region. This makes the most sense to me since the `ClientConfiguration` defaults to the region specified in applicable credentials if not specified, so specifying it makes the region specified by the credentials not used anyway (please correct me if I'm wrong).

Otherwise would it be possible to pass in the region directly to the CredentialsProvider? That way we could create the CredentialsProvider ahead of time and pass it to the S3Client like your suggestion.

I apologize I don't think I can contribute a change since I am not proficient in C++ (I'm just an SRE trying to get kiam rolled out, but have followed the rabbit hole here, 😄). I can speak to some of my team members to see if they would be willing to contribute a change if you think it would make sense to do either of the above.
