### ISSUE TITLE
Support wasm build

### ISSUE THREAD

**Issue by stereomatchingkiss** [aws/aws-sdk-cpp#1233]
Any plan to support wasm? I would like to host a static website developed by Qt5(Qt for wasm), is it possible to compile this sdk by emscripten and make it work in browser?

**Comment by KaibaLopez** [comment]
Hi @stereomatchingkiss, sorry to say we don't currently support or plan to support wasm anytime soon, but there should be a way for you to dynamically link the sdk to your project.
 According to emscripten's [FAQ](https://emscripten.org/docs/getting_started/FAQ.html):
_"... Libraries not included with Emscripten (like Boost) must be compiled and linked with the program just as if they were a module in the project ..."_
The same should be applicable to our sdk.

**Comment by sandroandrade** [comment]
Hi there. Any further information on that? I've managed to build AWS C++ SDK for Web Assembly (emsdk 3.1.25) but I get the following "undefined symbol" errors:
```
error: undefined symbol: aws_default_dns_resolve (referenced by top-level compiled C/C++ code)
error: undefined symbol: aws_event_loop_new_default_with_options (referenced by top-level compiled C/C++ code)
```

That's because `aws-c-io` doesn't include any platform-specific implementation (CMAKE_SYSTEM_NAME is equals "Emscripten" and no implementation files are included).

Can I somehow build the SDK without `aws-c-io`?
