### ISSUE TITLE
Done building project "aws-cpp-sdk-core-tests.vcxproj" -- FAILED.

### ISSUE THREAD

**Issue by LazzariPaolo** [aws/aws-sdk-cpp#1254]
### What platform/OS are you using?
Windows 10

### Which version of the SDK?
I am building AWS SDK 1.7.157.

### What compiler are you using? what version?
Compiler is:

> C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.15.26726/bin/Hostx86/x64/cl.exe

### What are your CMake arguments?

> -D BUILD_ONLY:STRING="transfer;batch;iam;cloudformation;logs;sts" -D CUSTOM_MEMORY_MANAGEMENT=0 -D CMAKE_PREFIX_PATH="S:/paolol/aws-c-common/;S:/paolol/aws-checksums/;S:/paolol/aws-c-event-stream/" -D BUILD_DEPS=OFF

### Can you provide a TRACE level log? (sanitize any sensitive information)
```
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: The command "setlocal
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: ..\bin\Release\aws-cpp-sdk-core-tests.exe --gtest_shuffle --gtest_repeat=3
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: :cmEnd
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: :cmErrorLevel
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: exit /b %1
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: :cmDone
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: if %errorlevel% neq 0 goto :VCEnd
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: :VCEnd" exited with code -1073741515.
Done building project "aws-cpp-sdk-core-tests.vcxproj" -- FAILED.
```
I am building with:

`devenv.com AWSSDK.sln /build "release|x64" /project INSTALL`

The sdk build is failing because aws-cpp-sdk-core-test is failing. It is the **only** component which fails. 

I only want to build the following components:

**transfer;batch;iam;cloudformation;logs;sts**

Is it possible to disable building the tests?
How can I fix this?

**Comment by KaibaLopez** [comment]
Hi @LazzariPaolo 
Yeah, on cmake the argument ENABLE_TESTING controls whether or not the unit and integration test projects are built and is on by default, so simply set it to off and that should disable the tests.

**Comment by LazzariPaolo** [comment]
Hi @KaibaLopez,

Cool, I set that to false and it worked.
Finally got it to build on Windows, thanks!

**Comment by LazzariPaolo** [comment]
@KaibaLopez  Hooray indeed! I would however still like to know whether/how I can fix building the test library.

**Comment by singku** [comment]
Would you mind find out which test cases failed？

**Comment by KaibaLopez** [comment]
Hey @LazzariPaolo, could you check if you have long file names enabled on windows? That is the most common cause of the core tests to fail on windows.
If not, then yea as singku said, we'd need to know which test is failing and the error message it gives.

**Comment by LazzariPaolo** [comment]
@singku Its not that a test case fails, its that the test library does not build in the first place.
@KaibaLopez I tried enabling the long paths but that did not fix the issue. Regardless, the path is lower than 260 characters anyway.

The error message is the one I included in my first post in the ticket.

**Comment by KaibaLopez** [comment]
Hi @LazzariPaolo the thing is that nowhere in the log you've provided tells us which part of the aws-sdk-core-tests fails. 
Error MSB3073 is generally caused by an incorrect path in the command line, this could mean that you don't have permission to write on the location (try running as administrator?)  or that you're building the project in the wrong order or one of the paths provided is not correct (long path truncated so invalid), among other causes.

So, the error message by itself doesn't help us in finding the root cause of your problem.

As to why the long path, it's not really because you'd be saving your project on a long path but, one of those tests in the core test library is "CreateFolderIfnotExists" which fails if long path is not enabled on windows. As a note, and I might sound silly here but, make sure that you rebooted your machine or the change won't take effect. 

Sorry if it feels like we're going in circles but, in order for us to help you, you'll have to find which of the tests is failing and preventing the build.

**Comment by LazzariPaolo** [comment]
Hi @KaibaLopez 
I am attaching the full log for the build, filtered for only the "aws-cpp-sdk-core-tests" library build:
[aws-sdk-core-test.log](https://github.com/aws/aws-sdk-cpp/files/3751654/aws-sdk-core-test.log)

What do you mean by _building the project in the wrong order_? What should this order be and how can I set it?

I have tried running as administrator. And I did reboot after setting the long paths, and made sure that the setting was in place after the reboot.

Thank you for your help.

**Comment by LazzariPaolo** [comment]
Hi @KaibaLopez 

I was able to run the executable manually and get the log:
[aws-cpp-sdk-core-tests-log.log](https://github.com/aws/aws-sdk-cpp/files/3757407/aws-cpp-sdk-core-tests-log.log)

**Comment by KaibaLopez** [comment]
Hi @LazzariPaolo, ok, I think I've found what could be your problem. 

So the error you're getting is kind of vague, and it could be caused by a number of things, it basically means access violation,  so it could be that you're trying to access memory that you have no permition to, or it could be a problem with the dll files, among other things. 

I think, in your case it means you're trying to build for **Debug** when the cmake was generated for **Release**. 
So, you could either add: -DCMAKE_BUILD_TYPE=Debug to the cmake arguments or build on Release (which is the default for the sdk). 
For safety's sake, and to narrow this down a bit, can you try running (from aws-cpp-sdk/build):
cmake .. -DCMAKE_BUILD_TYPE=Debug -DBUILD_ONLY=s3 -G "Visual Studio 15 2017 Win64"

Let me know if that fixed it for you.

On a side note the test when ran by itself fails because it needs to access some auth values in the folder "aws4_testsuite", you can test this on linux or mac, by trying to run:
./aws-cpp-sdk-core-tests/aws-cpp-sdk-core-tests
instead of going into the tests folder andsimply running
./aws-cpp-sdk-core-tests

**Comment by LazzariPaolo** [comment]
Hi @KaibaLopez ,

But I am running

`devenv.com AWSSDK.sln /build "release|x64" /project INSTALL`

does that not build for **Release**?

**Comment by KaibaLopez** [comment]
you're right, my bad there.
 did you try the simpler project cmake though?
cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_ONLY=s3 -G "Visual Studio 15 2017 Win64"
Also, the rest still stands, check for permissions on the folder you're building to.

**Comment by LazzariPaolo** [comment]
Hi @KaibaLopez 

I definitely have full permissions on the directory.
I tried building a simpler project but I still get the same issue.

**Comment by KaibaLopez** [comment]
if you change your command to : 
`devenv.com AWSSDK.sln /build "release|x64" /project ALL_BUILD`
Do you get the same error?

**Comment by LazzariPaolo** [comment]
Unfortunately, yes

**Comment by KaibaLopez** [comment]
Hi @LazzariPaolo , just checking in, I have not been able to reproduce the error you're having and I'm running out of things I can try to pin point what could be going wrong for you...
From a similar issue though we found a bug with environment variable **AWS_PROFILE** that causes an error on the core-tests. It's a different test that fails though, so not sure if it'll work out for you but just in case, can you check if you have AWS_PROFILE as an environment variable and if so, try deleting or giving it the "default" value?
