### ISSUE TITLE
Define strategy for AWS_CUSTOM_MEMORY_MANAGEMENT handling

### ISSUE THREAD

**Issue by anatol** [aws/aws-sdk-cpp#1284]
I am in the process of adding official Arch Linux package for `aws-sdk-cpp` project. Things look good but I found one compatibility issue between `aws-sdk-cpp` and `osquery` that I would like to clarify.

Here is how I compile `aws-sdk-cpp` for the Arch package: `cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_TESTING=OFF -DBUILD_DEPS=OFF -S . -B build && cmake --build build` (let me know if something can be improved here).

Arch Linux packages use shared libraries by default. And what I see that if `CUSTOM_MEMORY_MANAGEMENT`is not defined that it is set to `ON` for shared linked version and to `OFF` for static linked version of `aws-sdk-cpp`.

That in turn affects API provided by the library. If `CUSTOM_MEMORY_MANAGEMENT` is on then `Aws::String` <-> `std::string` conversion functions are not defined. It causes `osquery` fail to compile for dynamically linked version of the library:

```In file included from ../osquery/tables/cloud/ec2_instance_tags.cpp:16:
../osquery/include/osquery/tables.h: In instantiation of ‘std::string osquery::__sqliteField(const Type&) [with Type = std::__cxx11::basic_string<char, std::char_traits<char>, Aws::Allocator<char> >; std::string = std::__cxx11::basic_string<char>]’:
../osquery/tables/cloud/ec2_instance_tags.cpp:58:16:   required from here
../osquery/include/osquery/tables.h:63:24: error: no matching function for call to ‘to_string(const std::__cxx11::basic_string<char, std::char_traits<char>, Aws::Allocator<char> >&)’
   63 |   return std::to_string(source);
      |          ~~~~~~~~~~~~~~^~~~~~~~
```

When I recompile `aws-sdk-cpp` package with `-DCUSTOM_MEMORY_MANAGEMENT=OFF` then this `osquery` problem goes away.

I see several options how to help with this situation:
 * Disable `CUSTOM_MEMORY_MANAGEMENT` in Arch package. Is this feature important for desktop Linux system?
 * Keep `CUSTOM_MEMORY_MANAGEMENT` enabled for Arch package and force all the users (like `osquery`) to handle API incompatibility between 2 types of library (with and without custom management). But it is less then optimal. The same code should work both for statically and dynamically linked library.
 * Force all users (both statically and dynamically linked) to use `CUSTOM_MEMORY_MANAGEMENT`. It means users like `osquery` need to convert their code and avoid using `std::string` when `Aws::String` is expected. What is going to be the best way to convert between these types?

I am not a `aws-sdk-cpp` nor `C++` expert and I am looking for advise here. What would be the best solution that does not force users to maintain two versions of the codebase?

**Comment by KaibaLopez** [comment]
Hi @anatol ,
A few things to answer here:
first, I'll mark this as a feature request because I think we could make the sdk compatible with osquery, but I'd have to look into that in order to say for sure, so no promises there.
Regarding your question, `Is this feature important for desktop Linux system?`:
- it's more of a risk you're facing by enabling it, if enabled it's on you to handle memory; nothing specific to linux.

For `What is going to be the best way to convert between these types?`:
- both Aws::String and std::string have the c_str() method, which returns a const char *, which you could use to convert between the 2.

Let me know if this helped and I'll take a look into osquery compatibility, which by the way if you have suggestions on how to approach that, I'd appreciate that too.
