### ISSUE TITLE
segfault when dealing with Aws::String in android 

### ISSUE THREAD

**Issue by revolushion** [aws/aws-sdk-cpp#129]
Hi,

Every time when the memory management calls Aws::String destructor, I get Segfault.
After long reading about Strings in shared_ptr and your description in AWSString.h file, it still doesn't work.

Some details:
* using standalone toolchain arm-v7a gnu 4.9
* android platform 21
* using gnustl_static

Thanks,
Revo

**Comment by bretambrose** [comment]
Are you invoking cmake directly or are you using the (admittedly undocumented) android build script?  If using cmake directly, what is your command line that you're passing?

**Comment by revolushion** [comment]
cmake -DTARGET_ARCH=ANDROID -DANDROID_STANDALONE_TOOLCHAIN=/home/ob/tc -DANDROID_NATIVE_API_LEVEL=android-21 ..

**Comment by bretambrose** [comment]
Unless I'm overlooking something, it looks like custom memory management is turned off by default.  Can you try building with -DCUSTOM_MEMORY_MANAGEMENT=1 added?  

We have a work-in-progress build-and-test script (android-build/build_and_test_android.py) that can give you a lot of information on what we've needed to do in order to get success with android builds.

Android support has languished for a while now but I'm hoping we can return to it and finish it up within the next couple of months.

**Comment by revolushion** [comment]
I already tried with -DCUSTOM_MEMORY_MANAGEMENT=1 and also with -DSTATIC_LINK=1 but it's the same result ... segfault.

I'm trying to work my way with build-and-test script but no luck. cloud you write down the build-and-test script full command with parameters?

Thanks.

**Comment by bretambrose** [comment]
To try and better help with this I went back and created a fresh install of the SDK and have been working through getting everything working via the build-and-test script.  It's been about 6 months since Android was last actively worked on or tested and a lot of problems have crept in.  I began typing a list of instructions and workarounds needed but it became so long and messy that I can't in good conscience just say "go do this."  

I will be transitioning back onto the SDK in a couple of weeks and will attempt to make Android support my first priority.  I realize this is a very unsatisfactory answer, but if you're able to wait a few weeks, I believe we'll be able to work through this much easier once I'm able to devote work time to the SDK.

**Comment by revolushion** [comment]
I made it work by changing the following definitions:
Aws::String ==> std::basic_string< char > (instead Aws::string dedicated implementation to android)
Aws::StringStream ==> std::stringstream
Aws::OStringStream ==> std::ostringstream 
Aws::StringBuf ==> std::stringbuf

no more segfaults :)

**Comment by JonathanHenson** [comment]
We've updated our android build process. have a look and reopen if this issue still persists.
