### ISSUE TITLE
Support for inclusion as git submodule + add_subdirectory?

### ISSUE THREAD

**Issue by mpetri** [aws/aws-sdk-cpp#1294]
### What platform/OS are you using?
Ubuntu 18.04

### Which version of the SDK?
1.6.0 (or whatever git master is currently)

### What compiler are you using? what version?
g++-9

### What are your CMake arguments?
none

### Can you provide a TRACE level log? (sanitize any sensitive information)

I'm trying to include the sdk as a git submodule and subsequently as a add_subdirectory dependency in a larger cmake project. For example ideally I would like to write a cmake file such as:

```
add_subdirectory(external/aws-sdk-cpp/)
target_link_libraries(test aws-cpp-sdk-s3)
```

Is this supported? I can't seem to get this to work. For example, Issue #1210 appears to make compilation fail (make seeks write permissions to a system directory)

**Comment by KaibaLopez** [comment]
Hi @mpetri ,
Right so, the PR is trying to solve a sudo call that happens when you don't manually install the SDKs dependencies, we do these automatically and by default they try to install themselves in the local lib folder which on some cases require sudo calls. If you're having the same issue, it'd work by doing "sudo cmake", or installing the dependencies individually or specifying an installation path.

The second thing is, we don't "support" what you're trying to do in like, we don't have documentation or examples and we wouldn't consider it a bug if it didn't work, but I see no reason why you wouldn't be able to do this, so I might be able to help you get it to work. 

For now, I'll try to reproduce this and meanwhile could you tell me, what error are you getting and at what step?

**Comment by mpetri** [comment]
Hello, thanks for the response!

A simple example to reproduce what I'm trying to do:

1. `mkdir test_aws`
2. `cd test_aws`
3. `git clone https://github.com/aws/aws-sdk-cpp.git`
4. Create `CMakeLists.txt` with content:

```
project(test LANGUAGES CXX)

add_subdirectory(./aws-sdk-cpp/)
add_executable(test test.cpp)
target_link_libraries(test aws-cpp-sdk-s3)
```

5. `mkdir build`
6. `cd build && cmake ..`
7. `make test`

So preferably the aws sdk should be built in the `build` directory and not installed system wide and I should just be able to add for example the `aws-cpp-sdk-s3` target.

Quite a few other c++ libraries work like this. For example many logging frameworks etc.

**Comment by KaibaLopez** [comment]
ah, I misunderstood what you're trying to do there, [this might help you](https://aws.amazon.com/blogs/developer/using-cmake-exports-with-the-aws-sdk-for-c/) then:
Basically, you'd have to build and install the libraries before you can use them.
Let me know if the guide helped.

**Comment by mpetri** [comment]
I followed the instructions you provided before and it works. I just don't like that the sdk (1) has to be installed it system wide (2) I can't just use add_subdirectory and have the whole code for my application be in one directory managed by git and git submodule.

Closing this issue as I think it is resolved. Thanks anyway.

**Comment by m-j-ahmadi** [comment]
@mpetri Hi did you find any solution for this i have same problem.
