### ISSUE TITLE
S3  I/O *twice* as costly for smaller objects.

### ISSUE THREAD

**Issue by aghiles** [aws/aws-sdk-cpp#1302]
When using the TransferManager::DownloadFile,  you issue a HEAD to get the size of the object to decide if, yes or no, you should use multipart download. This is has the effect that smaller blobs are twice as costly to download as much larger blobs, on average. 

### What platform/OS are you using?
All.

### Which version of the SDK?
e8a7e7263e900983921e95363026efaa494622ab

**Comment by KaibaLopez** [comment]
Hi @aghiles , 
So, transfer manager is kind of a wrapper for S3 operations meant to make things easier for you when handling big data transfers, but if you know you're doing a lot of smaller sized object operations, it's probably better to just use the S3 getObject.

**Comment by aghiles** [comment]
OK. But please note that the TransferManager is probably what most of your customers will use. And they will see you service as more expensive than it should be (compared to your competition maybe). I highly recommend to at Document this behaviour, to the very least.

I understand it's a "wrapper". But if you told me that the wrapper will cost twice as much ... I would say the wrapper has a problem! :)

**Comment by KaibaLopez** [comment]
@aghiles, 
I see your point, and I agree that we could/should mention the downsides of transfer manager against simple s3 service operations.
But also keep in mind, this is not what transfer manager is there for, it is meant to simplify larger data transfer, not to optimize smaller ones.
As you mention, there is a reason for getting the headers and the increased operation cost, but if you don't need that (you know what kind of objects you're getting for example), you can not-have it and use the s3 service operations directly instead of using transfer manager.
So I'd argue you're using the wrong tool for the scenario you're describing.
Let me know what you think though, or if you have a change in mind to approach this issue, we are definitely open for suggestions.

**Comment by aghiles** [comment]
Actually, to the contrary, the TransferManager is even more useful for many smaller transfers than larger ones! Making one large transfer is trivial, but having the necessary plumbing for efficiently handling many request in multi-thread, which needs good multi-threading, is not that easy :)

So beyond documentation, what can be done ? It's easy and hard at the same time. It's easy because it "just" returns a "GET+HEAD" API call from the backend. It gets the [first] blob, if it exists, and also returns the HEAD. From there you can know that there are more blobs to download. I guess thats feasible. The hard part is that backend  is not on the SDK side :)

Commercial rationale:  this command  will definitely relieve pressure from you backend, lower your clients costs and also has some announcement value.

Anther rationale: If download sizes follow a normal distribution, you must have about same bandwidth used for small blobs than for larger blobs ... but you will get much more HEADs than GETs which could amount for unnecessary pollution and backend stress. The GET+HEAD might solve that.

**Comment by aghiles** [comment]
I must add something important here. It's not only the cost that suffers ... but the latency too. You have **twice** the latency for smaller objects because of the dual round trip (HEAD+GET).

When I say small, its not _that_ small btw.  I think your default limit is something like 5 megs.

**Comment by KaibaLopez** [comment]
So the first thing here I'd like to point out is yea, the get+head you suggest would be a change done to the s3 api, but it would be outside of the sdk's team scope, meaning we could ask for it but no promises there, would be cool though and having the issue asking for it helps a lot, so maybe.

That being said, I still feel like I **must** be missing something here, for sure we are doing a double call on transfer manager to get the headers so the latency does get affected, but the double size is what I don't see... it made sense to me when "smaller files" meant something like 500-1,000 bytes, where yea, the header would be about the same size as the object but 5megs... there's no way the header is ever that big, so what do you mean by this?

And finally, I'd like to see if there is a sort of workaround we could figure out for your specific situation, or maybe a transfer manager functionality thing we can add to the sdk rather than depending on the s3 service.... so what is it you're trying to do exactly?
