### ISSUE TITLE
Set set correct defaults (c++ 11) as a public property 

### ISSUE THREAD

**Issue by dblock** [aws/aws-sdk-cpp#1338]
### What platform/OS are you using?

MacOS

### Which version of the SDK?

Mojave

### What compiler are you using? what version?

CMake 3.16.4

Coming from https://github.com/awsdocs/aws-doc-sdk-examples/pull/1022#discussion_r388497318

Currently projects require setting the target compile features to C++ 11 in CMakeLists.txt with `target_compile_features(my-example PUBLIC cxx_std_11)` or risk getting the following errors:

```
[ 50%] Building CXX object CMakeFiles/list-s3-buckets.dir/main.cpp.o
In file included from /Users/dblock/source/aws-sdk/list-s3-buckets/main.cpp:2:
In file included from /usr/local/include/aws/core/Aws.h:17:
In file included from /usr/local/include/aws/core/utils/logging/LogLevel.h:20:
In file included from /usr/local/include/aws/core/utils/memory/stl/AWSString.h:20:
In file included from /usr/local/include/aws/core/utils/memory/stl/AWSAllocator.h:21:
/usr/local/include/aws/core/utils/memory/AWSMemory.h:162:78: error: 'T' does not refer to a value
            std::size_t headerSize = (std::max)(sizeof(std::size_t), alignof(T));
                                                                             ^
/usr/local/include/aws/core/utils/memory/AWSMemory.h:149:23: note: declared here
    template<typename T>
                      ^
```

There should be a way to not have to do this for every project.

**Comment by Lectem** [comment]
Note that it would require to have at least one exported target to have this compile feature requirement.

It seems cmake does not install such requirements by default (I opened an issue on cmake bug tracker https://gitlab.kitware.com/cmake/cmake/issues/20430) , so it should be handled by the https://github.com/aws/aws-sdk-cpp/blob/master/cmake/AWSSDKConfig.cmake file. 
Since it already iterates over targets it could probably call `target_compile_features` for each of them ?

It already tries to do something with a hardcoded CPP_STANDARD https://github.com/aws/aws-sdk-cpp/blob/a80b3e7784188deeeafdb3605066a18454913e18/cmake/AWSSDKConfig.cmake#L71 that knows how to set the standard only for gcc/linux (see https://github.com/aws/aws-sdk-cpp/blob/bfec5f0bf7cc3d4fcc4b614dc7055bab5e99b644/cmake/compiler_settings.cmake#L36 and https://github.com/aws/aws-sdk-cpp/blob/0912003eae920b53661ef6287b7b97d16a507b67/cmake/platform/linux.cmake#L32 )
