### ISSUE TITLE
AttributeValue is missing some SetS,SetN functions that appear in header

### ISSUE THREAD

**Issue by adrianboston** [aws/aws-sdk-cpp#136]
It seems that aws.dynamodb.model.AttributeValue.cpp is missing some SetS,SetN that appear in header.

The result of which is a "symbol not found" link error for something like    
   AttributeValue homer;
    homer.SetS("Homer");

"Doh" missed the following inline
   /// if uninitialized, specializes the type to a String with specified value
    /// if already specialized to another type then the behavior is undefined
    AttributeValue& SetS(const char* n) { return SetS(Aws::String(n)); }

But nevertheless still get a link error. 

Undefined symbols for architecture x86_64:
  "Aws::DynamoDB::Model::AttributeValue::SetS(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      Aws::DynamoDB::Model::AttributeValue::SetS(char const*) in homer_test.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by adrianboston** [comment]
doh. im wrong missed the inline

**Comment by adrianboston** [comment]
Despite the issue above the associated Dynamo tests -- that use SetS("Homer") -- does compile and link. 
Any suggestions?

Scanning dependencies of target runDynamoDBIntegrationTests
[100%] Building CXX object aws-cpp-sdk-dynamodb-integration-tests/CMakeFiles/runDynamoDBIntegrationTests.dir/RunTests.cpp.o
[100%] Building CXX object aws-cpp-sdk-dynamodb-integration-tests/CMakeFiles/runDynamoDBIntegrationTests.dir/TableOperationTest.cpp.o
[100%] Linking CXX executable runDynamoDBIntegrationTests
[100%] Built target runDynamoDBIntegrationTests

**Comment by bretambrose** [comment]
It sounds like a CUSTOM_MEMORY_MANAGEMENT #define mismatch (in particular, your exe is looking for a function where strings are using std::allocator while your SDK was likely compiled with a switch making strings use Aws::Allocator).  The integration tests work because they are using the exact same set of preprocessor directives.

Try adding -DCUSTOM_MEMORY_MANAGEMENT=0 to your cmake command line when setting up the build for the CPP SDK.  

In the near future we will handle this option/#define better so that it's impossible to get a mismatch between the library binaries and your binaries.

**Comment by JonathanHenson** [comment]
We've made this much easier for use with CMake. Have a look at this blog post:

https://aws.amazon.com/blogs/developer/using-cmake-exports-with-the-aws-sdk-for-c/

**Comment by adrianboston** [comment]
-DCUSTOM_MEMORY_MANAGEMENT=0 seems to have solved that. thnx for the response.
