### ISSUE TITLE
cmake: cmake can't find libraries for android

### ISSUE THREAD

**Issue by miryee** [aws/aws-sdk-cpp#1366]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**
cmake is unable to find the AWS libraries and returns errors:
```
CMake Error at CMakeLists.txt:41 (find_package):
  By not providing "FindAWSSDK.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "AWSSDK", but
  CMake did not find one.

  Could not find a package configuration file provided by "AWSSDK" with any
  of the following names:

    AWSSDKConfig.cmake
    awssdk-config.cmake

  Add the installation prefix of "AWSSDK" to CMAKE_PREFIX_PATH or set
  "AWSSDK_DIR" to a directory containing one of the above files.  If "AWSSDK"
  provides a separate development package or SDK, be sure it has been
  installed.
```
AWSSDK_DIR is set correctly.  This occurs with the path structure set as:  manually restructured to {awssdklibs/libs/[PLATFORM_PREFIX]/[Debug|Release]} and {awssdklibs/lib/[PLATFORM_PREFIX]/[Debug|Release]}

Moving AWSSDKConfig.cmake from awssdkdir/libs/cmake to the awssdklib directory generates the following error:

```
  AWS SDK for C++ headers found, but we were unable to locate the binaries.
  Have you deleted or moved it?

              Please make sure header files and binaries are located in INSTALL_ROOT_DIR/INCLUDE_DIR/ and INSTALL_ROOT_DIR/LIB_DIR/[PLATFORM_PREFIX]/[Debug|Config|OtherConfigs]
```
The above error also occurs with the default awssdkcpp library build {awssdklibsinclude, awssdklibs/lib} per architecture type and debug/release. The default install directory awssdklibs/lib contains the binaries etc for the specific architecture type.  It does not have the directory structure that cmake is complaining about of INSTALL_ROOT_DIR/LIB_DIR/[PLATFORM_PREFIX]/[Debug|Config|OtherConfigs].

*SDK version number**
1.7.277

**Platform/OS/Hardware/Device**
Trying to build app on MacBookPro for Android {armeabi-v7a, arm64-v8a, x86, x86_64}

**To Reproduce (observed behavior)**
`cmake .  -DCMAKE_FIND_DEBUG_MODE=ON -DCMAKE_BUILD_TYPE=Debug -D-DTARGET_ARCH=ANDROID -DANDROID_ABI=x86`

CMakeLists.txt:
```
cmake_minimum_required(VERSION 2.8)
project(cmaketest LANGUAGES CXX)

... everything else has been commented out so the focus is just on finding the AWS libs

find_package(AWSSDK REQUIRED COMPONENTS s3 identity-management)
add_executable(${PROJECT_NAME} "main.cpp")
target_link_libraries(${PROJECT_NAME} ${AWSSDK_LINK_LIBRARIES})
```

**Expected behavior**
Am able to build my application successfully.

**Logs/output**
[cmaketest_01.log](https://github.com/aws/aws-sdk-cpp/files/4504995/cmaketest_01.log)
[cmaketest_02.log](https://github.com/aws/aws-sdk-cpp/files/4504996/cmaketest_02.log)

**Additional context**
Need to be able to build with this version of the awssdkcpp.  I have already integrated and tested successfully on Windows version of our proprietary software and am now trying to build on all the platforms we support. If the fix for this problem is supposed to be in a more recent version of the awssdkcpp, then please confirm which commit version.  This has taken significantly more time to integrate than expected.

I have found similar complaints, but no responses much less resolutions:
http://archlinux.2023198.n4.nabble.com/aws-sdk-cpp-git-cmake-issues-compiling-proograms-for-it-td4722631.html
This one speaks to linux, but appears to only be partially addressed:
https://github.com/aws/aws-sdk-cpp/issues/1188

**Comment by justinpa-asg** [comment]
justin.palmer@asg.com is no longer a valid e-mail address.  Please contact Tim Wake at tim.wake@asg.com with any questions, comments, or concerns.

Diese justin.palmer@asg.com ist keine gultige Email-Adresse mehr. Bitte setzen Sie sich mit Tim Wake an folgende Email-Adresse tim.wake@asg.com in Verbindung, falls Sie etwaige Fragen, Kommentare oder Bedenken diesbezuglich haben.

Cette justin.palmer@asg.com n'est plus une adresse de courriel valable. Veuillez contacter Tim Wake a l'adresse de courriel suivante tim.wake@asg.com si vous avez des questions, des commentaires ou des preoccupations quelconques.

From: noreply@github.com
Sent: Monday, April 20 2020 5:20 PM
To: aws-sdk-cpp@noreply.github.com
CC: subscribed@noreply.github.com
Subject: [aws/aws-sdk-cpp] cmake: cmake can't find libraries for android (#1366)


Confirm by changing [ ] to [x] below to ensure that it's a bug:

  *    I've gone though Developer Guide<http://TOC.ASG.COM:8080/?dmVyPTEuMDAxJiZlYzI3N2ZmNzIwZDNiYjY2NT01RTlEREEyNl8yNzk2Xzc2N18xJiZmMzUxMmNkZTBiYzE2ZmI9MTIzMiYmdXJsPWh0dHBzJTNBJTJGJTJGZG9jcyUyRWF3cyUyRWFtYXpvbiUyRWNvbSUyRnNkay1mb3ItY3BwJTJGdjElMkZkZXZlbG9wZXItZ3VpZGUlMkZ3ZWxjb21lJTJFaHRtbA==> and API reference<http://TOC.ASG.COM:8080/?dmVyPTEuMDAxJiZlYzNkNmRhMzJjZDJmODJhNT01RTlEREEyNl8yNzk2Xzc2N18xJiYzMjg0ZDkxZTVhNzUyYjI9MTIzMiYmdXJsPWh0dHAlM0ElMkYlMkZzZGslMkVhbWF6b25hd3MlMkVjb20lMkZjcHAlMkZhcGklMkZMQVRFU1QlMkZpbmRleCUyRWh0bWw=>
  *    I've searched for previous similar issues<http://TOC.ASG.COM:8080/?dmVyPTEuMDAxJiZlMDY1N2ZmYTNjOTJmNDcyND01RTlEREEyNl8yNzk2Xzc2N18xJiYzNzU0ZWRhZWZmYTU4ZWQ9MTIzMiYmdXJsPWh0dHBzJTNBJTJGJTJGZ2l0aHViJTJFY29tJTJGYXdzJTJGYXdzLXNkay1jcHAlMkZpc3N1ZXM=> and didn't find any solution

Describe the bug
cmake is unable to find the AWS libraries and returns errors:

CMake Error at CMakeLists.txt:41 (find_package):
  By not providing "FindAWSSDK.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "AWSSDK", but
  CMake did not find one.

  Could not find a package configuration file provided by "AWSSDK" with any
  of the following names:

    AWSSDKConfig.cmake
    awssdk-config.cmake

  Add the installation prefix of "AWSSDK" to CMAKE_PREFIX_PATH or set
  "AWSSDK_DIR" to a directory containing one of the above files.  If "AWSSDK"
  provides a separate development package or SDK, be sure it has been
  installed.


AWSSDK_DIR is set correctly. This occurs with the path structure set as: default awssdkcpp build structure {awssdklibsinclude, awssdkdir/libs} per architecture type, and manually restructured to {awssdklibs/libs/[PLATFORM_PREFIX]/[Debug|Release]} and {awssdklibs/lib/[PLATFORM_PREFIX]/[Debug|Release]}

Moving AWSSDKConfig.cmake from awssdkdir/libs/cmake to the awssdkdir directory generates the following error:

AWS SDK for C++ headers found, but we were unable to locate the binaries.
  Have you deleted or moved it?


SDK version number*
1.7.277

Platform/OS/Hardware/Device
What are you running the sdk on?
Trying to build app on MacBookPro for Android {armeabi-v7a, arm64-v8a, x86, x86_64}

To Reproduce (observed behavior)
Steps to reproduce the behavior (please share code)
cmake . -DCMAKE_FIND_DEBUG_MODE=ON -DCMAKE_BUILD_TYPE=Debug -D-DTARGET_ARCH=ANDROID -DANDROID_ABI=x86

cmake_minimum_required(VERSION 2.8)
project(cmaketest LANGUAGES CXX)

... everything else has been commented out so the focus is just on finding the AWS libs

find_package(AWSSDK REQUIRED COMPONENTS s3 identity-management)
add_executable(${PROJECT_NAME} "main.cpp")
target_link_libraries(${PROJECT_NAME} ${AWSSDK_LINK_LIBRARIES})


Expected behavior
Am able to build my application successfully.

Logs/output
If applicable, add logs or error output.

To enable logging, set the following system properties:

REMEMBER TO SANITIZE YOUR PERSONAL INFO
cmaketest_01.log<http://TOC.ASG.COM:8080/?dmVyPTEuMDAxJiZlMDY1N2ZmYTNjOTJmNDcyND01RTlEREEyNl8yNzk2Xzc2N18xJiYzNzU0ZWRhZWZmYTU4ZWQ9MTIzMiYmdXJsPWh0dHBzJTNBJTJGJTJGZ2l0aHViJTJFY29tJTJGYXdzJTJGYXdzLXNkay1jcHAlMkZmaWxlcyUyRjQ1MDQ5OTUlMkZjbWFrZXRlc3QlNUYwMSUyRWxvZw==>
cmaketest_02.log<http://TOC.ASG.COM:8080/?dmVyPTEuMDAxJiZlMDY1N2ZmYTNjOTJmNDcyND01RTlEREEyNl8yNzk2Xzc2N18xJiYzNzU0ZWRhZWZmYTU4ZWQ9MTIzMiYmdXJsPWh0dHBzJTNBJTJGJTJGZ2l0aHViJTJFY29tJTJGYXdzJTJGYXdzLXNkay1jcHAlMkZmaWxlcyUyRjQ1MDQ5OTYlMkZjbWFrZXRlc3QlNUYwMiUyRWxvZw==>

Additional context
Need to be able to build with this version of the awssdkcpp. I have already integrated and tested successfully on Windows version of our proprietary software and am now trying to build on all the platforms we support. If the fix for this problem is supposed to be in a more recent version of the awssdkcpp, then please confirm this is true. This has taken significantly more time to integrate than expected.

I have found similar complaints, but no responses much less resolutions.
http://archlinux.2023198.n4.nabble.com/aws-sdk-cpp-git-cmake-issues-compiling-proograms-for-it-td4722631.html<http://TOC.ASG.COM:8080/?dmVyPTEuMDAxJiZiZjdhMmNiZTdlODRhZDJiNT01RTlEREEyNl8yNzk2Xzc2N18xJiZlNmMxM2QwZTViNTU5ZjE9MTIzMiYmdXJsPWh0dHAlM0ElMkYlMkZhcmNobGludXglMkUyMDIzMTk4JTJFbjQlMkVuYWJibGUlMkVjb20lMkZhd3Mtc2RrLWNwcC1naXQtY21ha2UtaXNzdWVzLWNvbXBpbGluZy1wcm9vZ3JhbXMtZm9yLWl0LXRkNDcyMjYzMSUyRWh0bWw=>

**Comment by miryee** [comment]
Ok I got this finally to work with by adding all the paths to CMAKE_PREFIX_PATH before find_package in my cmake file.  Apparently find_package does not search recursively in subdirectories and it is not specified to that depth in the AWSSDKConfig.cmake file.  

However, now I have run into another problem.

All my awssdkcpp android packages are built statically using the same build commands and the same repository source.  However, trying to link them to my app I get different results.  With arm64-v8a and x86_64 I am able to successfully build both debug and release versions.  With armeabi-v7a and x86, I get fails:

```
CMake Error at CMakeLists.txt:38 (find_package):
  Could not find a configuration file for package "AWSSDK" that is compatible
  with requested version "".

  The following configuration files were considered but not accepted:

    /Users/myee/Projects/awssdklibs/awssdkcpp_android_x86_debug/lib/cmake/AWSSDK/AWSSDKConfig.cmake, version: 1.7.277 (32bit)
```
Any help would be appreciated. 
[cmakebattery.log](https://github.com/aws/aws-sdk-cpp/files/4506282/cmakebattery.log)

**Comment by justinpa-asg** [comment]
justin.palmer@asg.com is no longer a valid e-mail address.  Please contact Tim Wake at tim.wake@asg.com with any questions, comments, or concerns.

Diese justin.palmer@asg.com ist keine gultige Email-Adresse mehr. Bitte setzen Sie sich mit Tim Wake an folgende Email-Adresse tim.wake@asg.com in Verbindung, falls Sie etwaige Fragen, Kommentare oder Bedenken diesbezuglich haben.

Cette justin.palmer@asg.com n'est plus une adresse de courriel valable. Veuillez contacter Tim Wake a l'adresse de courriel suivante tim.wake@asg.com si vous avez des questions, des commentaires ou des preoccupations quelconques.

From: noreply@github.com
Sent: Monday, April 20 2020 9:31 PM
To: aws-sdk-cpp@noreply.github.com
CC: justin.palmer@asg.com, comment@noreply.github.com
Subject: Re: [aws/aws-sdk-cpp] cmake: cmake can't find libraries for android (#1366)


Ok I got this finally to work with by adding all the paths to CMAKE_PREFIX_PATH before find_package in my cmake file. Apparently find_package does not search recursively in subdirectories and it is not specified to that depth in the AWSSDKConfig.cmake file.

However, now I have run into another problem.

All my awssdkcpp android packages are built statically using the same build commands and the same repository source. However, trying to link them to my app I get different results. With arm64-v8a and x86_64 I am able to successfully build both debug and release versions. With armeabi-v7a and x86, I get fails:

CMake Error at CMakeLists.txt:38 (find_package):
  Could not find a configuration file for package "AWSSDK" that is compatible
  with requested version "".

  The following configuration files were considered but not accepted:

    /Users/myee/Projects/awssdklibs/awssdkcpp_android_x86_debug/lib/cmake/AWSSDK/AWSSDKConfig.cmake, version: 1.7.277 (32bit)


Any help would be appreciated.
cmakebattery.log<http://TOC.ASG.COM:8080/?dmVyPTEuMDAxJiZjMjllYzQ1MjAxMjZlMTQyMz01RTlFMTRCQl8yMjA4Ml8xOV8xJiZkYTBjNmIwZTkzNjQ2MjY9MTIzMiYmdXJsPWh0dHBzJTNBJTJGJTJGZ2l0aHViJTJFY29tJTJGYXdzJTJGYXdzLXNkay1jcHAlMkZmaWxlcyUyRjQ1MDYyODIlMkZjbWFrZWJhdHRlcnklMkVsb2c=>

**Comment by KaibaLopez** [comment]
Hi @miryee ,
Sorry for the late response, been a crazy month. 
For this issue you seem to be pretty far ahead and this may come a little late for you but we do have scripts that you can run to do cross-platform builds which should take care of these things for you.
 For the armeabi, I believe you can run the script like this:
```
cd aws-sdk-cpp
export ANDROID_NDK="/opt/android-ndk-r12b" //or your ndk location path.
python scripts/build_3rdparty.py --configs="ReleaseStatic ReleaseDynamic DebugDynamic DebugStatic" --parallel=8 --installdir="../Install" --generateClients="0" --architecture=AndroidArm --cmake_params="-DMINIMIZE_SIZE=ON -DANDROID_NATIVE_API_LEVEL=19"
```
And for arm64 you can change it for:
```
python scripts/build_3rdparty.py --configs="DebugDynamic ReleaseDynamic DebugStatic ReleaseStatic" --parallel=8 --installdir="../Install" --generateClients="0" --architecture=AndroidArm64 --cmake_params="-DMINIMIZE_SIZE=ON"
```

Let me know if this works for you and sorry again for the late response.
