### ISSUE TITLE
Undefined references when building S3 application with Visual Studio 2019

### ISSUE THREAD

**Issue by geoffhaynes** [aws/aws-sdk-cpp#1367]
Following the guidelines here:
https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/setup.html
I downloaded Visual Studio 2019 (Community Edition) and created a project with the aim of running one of the simple S3 examples. I used NuGet to install the AWSSDKCPP-Core and AWSSDKCPP-S3 packages.

On building the project, my C++ source file compiled successfully but the linker failed because all my references to the AWS packages were undefined  (eg. the call to Aws::InitAPI).

I took a look at the project log and saw that the LINK command didn't include the .lib files for the AWS packages! This is odd, because the packages are listed in the project properties, and the compiler also found the AWS header files without my having to specify them.

So I added the two .lib files aws-cpp-sdk-core.lib and aws-cpp-sdk-s3.lib using Project Properties > Library > Input and specified the directories where they live using Library > General.

The build then succeeded and produced an .exe.

**Comment by justinpa-asg** [comment]
justin.palmer@asg.com is no longer a valid e-mail address.  Please contact Tim Wake at tim.wake@asg.com with any questions, comments, or concerns.

Diese justin.palmer@asg.com ist keine gultige Email-Adresse mehr. Bitte setzen Sie sich mit Tim Wake an folgende Email-Adresse tim.wake@asg.com in Verbindung, falls Sie etwaige Fragen, Kommentare oder Bedenken diesbezuglich haben.

Cette justin.palmer@asg.com n'est plus une adresse de courriel valable. Veuillez contacter Tim Wake a l'adresse de courriel suivante tim.wake@asg.com si vous avez des questions, des commentaires ou des preoccupations quelconques.

From: noreply@github.com
Sent: Tuesday, April 21 2020 4:23 PM
To: aws-sdk-cpp@noreply.github.com
CC: subscribed@noreply.github.com
Subject: [aws/aws-sdk-cpp] Undefined references when building S3 application with Visual Studio 2019 (#1367)


Following the guidelines here:
https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/setup.html<http://TOC.ASG.COM:8080/?dmVyPTEuMDAxJiZiNDUzMzMwOGJmODMxMDEzMD01RTlGMUUxM18xMzg2OV8yMjA0XzEmJmUxNmQyOTYyODFiY2MzMz0xMjMyJiZ1cmw9aHR0cHMlM0ElMkYlMkZkb2NzJTJFYXdzJTJFYW1hem9uJTJFY29tJTJGc2RrLWZvci1jcHAlMkZ2MSUyRmRldmVsb3Blci1ndWlkZSUyRnNldHVwJTJFaHRtbA==>
I downloaded Visual Studio 2019 (Community Edition) and created a project with the aim of running one of the simple S3 examples. I used NuGet to install the AWSSDKCPP-Core and AWSSDKCPP-S3 packages.

On building the project, my C++ source file compiled successfully but the linker failed because all my references to the AWS packages were undefined (eg. the call to Aws::InitAPI).

I took a look at the project log and saw that the LINK command didn't include the .lib files for the AWS packages! This is odd, because the packages are listed in the project properties, and the compiler also found the AWS header files without my having to specify them.

So I added the two .lib files aws-cpp-sdk-core.lib and aws-cpp-sdk-s3.lib using Project Properties > Library > Input and specified the directories where they live using Library > General.

The build then succeeded and produced an .exe.

**Comment by KaibaLopez** [comment]
Hi @geoffhaynes ,
it sounds like you've solved your problem, so that's great!
We don't support NuGet packages anymore though, so I don't think there is much to do here.

**Comment by justinpa-asg** [comment]
justin.palmer@asg.com is no longer a valid e-mail address.  Please contact Tim Wake at tim.wake@asg.com with any questions, comments, or concerns.

Diese justin.palmer@asg.com ist keine gultige Email-Adresse mehr. Bitte setzen Sie sich mit Tim Wake an folgende Email-Adresse tim.wake@asg.com in Verbindung, falls Sie etwaige Fragen, Kommentare oder Bedenken diesbezuglich haben.

Cette justin.palmer@asg.com n'est plus une adresse de courriel valable. Veuillez contacter Tim Wake a l'adresse de courriel suivante tim.wake@asg.com si vous avez des questions, des commentaires ou des preoccupations quelconques.

From: noreply@github.com
Sent: Wednesday, April 22 2020 5:34 PM
To: aws-sdk-cpp@noreply.github.com
CC: justin.palmer@asg.com, comment@noreply.github.com
Subject: Re: [aws/aws-sdk-cpp] Undefined references when building S3 application with Visual Studio 2019 (#1367)


Hi @geoffhaynes<http://TOC.ASG.COM:8080/?dmVyPTEuMDAxJiZjYTI2NzBhMDdjZGQ2NmM0Yz01RUEwODA2MF8yNzQ0XzYzMl8xJiY2MjM1Y2Y1OTI5MWZkYmY9MTIzMiYmdXJsPWh0dHBzJTNBJTJGJTJGZ2l0aHViJTJFY29tJTJGZ2VvZmZoYXluZXM=> ,
it sounds like you've solved your problem, so that's great!
We don't support NuGet packages anymore though, so I don't think there is much to do here.

**Comment by geoffhaynes** [comment]
Yup, I just thought I'd document it for anyone else who runs into it. Could I respectfully suggest that you change the online docs to reflect the fact that NuGet is no longer supported? I noticed that the libraries fetched by NuGet are pretty old (version 1.6.25) - presumably if I'd used vcpkg I would have got more up-to-date versions.

**Comment by justinpa-asg** [comment]
justin.palmer@asg.com is no longer a valid e-mail address.  Please contact Tim Wake at tim.wake@asg.com with any questions, comments, or concerns.

Diese justin.palmer@asg.com ist keine gultige Email-Adresse mehr. Bitte setzen Sie sich mit Tim Wake an folgende Email-Adresse tim.wake@asg.com in Verbindung, falls Sie etwaige Fragen, Kommentare oder Bedenken diesbezuglich haben.

Cette justin.palmer@asg.com n'est plus une adresse de courriel valable. Veuillez contacter Tim Wake a l'adresse de courriel suivante tim.wake@asg.com si vous avez des questions, des commentaires ou des preoccupations quelconques.

From: noreply@github.com
Sent: Thursday, April 23 2020 8:30 AM
To: aws-sdk-cpp@noreply.github.com
CC: justin.palmer@asg.com, comment@noreply.github.com
Subject: Re: [aws/aws-sdk-cpp] Undefined references when building S3 application with Visual Studio 2019 (#1367)


Yup, I just thought I'd document it for anyone else who runs into it. Could I respectfully suggest that you change the online docs to reflect the fact that NuGet is no longer supported? I noticed that the libraries fetched by NuGet are pretty old (version 1.6.25) - presumably if I'd used vcpkg I would have got more up-to-date versions.

**Comment by justinpa-asg** [comment]
justin.palmer@asg.com is no longer a valid e-mail address.  Please contact Tim Wake at tim.wake@asg.com with any questions, comments, or concerns.

Diese justin.palmer@asg.com ist keine gultige Email-Adresse mehr. Bitte setzen Sie sich mit Tim Wake an folgende Email-Adresse tim.wake@asg.com in Verbindung, falls Sie etwaige Fragen, Kommentare oder Bedenken diesbezuglich haben.

Cette justin.palmer@asg.com n'est plus une adresse de courriel valable. Veuillez contacter Tim Wake a l'adresse de courriel suivante tim.wake@asg.com si vous avez des questions, des commentaires ou des preoccupations quelconques.

From: noreply@github.com
Sent: Thursday, April 23 2020 8:30 AM
To: aws-sdk-cpp@noreply.github.com
CC: justin.palmer@asg.com, comment@noreply.github.com
Subject: Re: [aws/aws-sdk-cpp] Undefined references when building S3 application with Visual Studio 2019 (#1367)


Closed #1367<http://TOC.ASG.COM:8080/?dmVyPTEuMDAxJiY4MWIxMTg2YzEzZTI0MzBlNz01RUExNTIyNF8yMjA4Ml85MDk1XzEmJjA1NTZmNDRmYjcyYWZmNj0xMjMyJiZ1cmw9aHR0cHMlM0ElMkYlMkZnaXRodWIlMkVjb20lMkZhd3MlMkZhd3Mtc2RrLWNwcCUyRmlzc3VlcyUyRjEzNjc=>.

**Comment by JimMikola** [comment]
This issue is still present best I can tell.   The Nuget Packages only contain artifacts for Visual Studio tools version 120, 140, and 141.

Visual Studio 2019 is tool version 142.  The nuget package manager will successfully install the packages, but the libs  and DLLs are not made available to any project in the solution built off the v142 toolset.

**Comment by JimMikola** [comment]
It's not obvious that NuGet is no longer supported.  The documentation here still lists NuGet as an option:  https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/setup.html

I think I'll switch to Vcpkg, but I need to determine if that is still supported as well.
