### ISSUE TITLE
I was forced to build parts of aws-c-common to get S3 working.

### ISSUE THREAD

**Issue by h3rbg3** [aws/aws-sdk-cpp#1392]
**Describe the bug**
I was prompted by rcarter to open a bug report here.

From awslabs/aws-c-event-stream
"Hello, it sounds like the issue you're running into is related to the C++ SDK. If that's true, because this ticket is for building this library individually, would you be able to open a new issue on the C++ SDK repo? Also, just to be sure, it sounds like the issue you're describing here is the same one that you encountered here: #7. Is that correct?"

**SDK version number**
1.7.3

**Platform/OS/Hardware/Device**
Ubuntu 18.04

**To Reproduce (observed behavior)**
Attempt to build S3 without first building dependencies

**Expected behavior**
I expect it to know how to build itself out of the box.

**Logs/output**

Unlike the other dependencies of the s3 component, ie aws-c-common and aws-checksums, this library generates those errors in CMake. Encountering the problem this afternoon, as well

```
$ cmake -DCMAKE_PREFIX_PATH=/usr/local/lib/ -DCMAKE_INSTALL_PREFIX=/usr/local/lib/ -S aws-c-event-stream -B aws-c-event-stream/build
CMake Error at CMakeLists.txt:36 (include):
  include could not find load file:

    AwsCFlags


CMake Error at CMakeLists.txt:37 (include):
  include could not find load file:

    AwsSharedLibSetup


CMake Error at CMakeLists.txt:38 (include):
  include could not find load file:

    AwsSanitizers


CMake Error at CMakeLists.txt:74 (aws_set_common_properties):
  Unknown CMake command "aws_set_common_properties".


-- Configuring incomplete, errors occurred!
See also "/home/ubuntu/aws-c-event-stream/build/CMakeFiles/CMakeOutput.log".
```

**Additional context**
I was able to fix this issue by manually building dependencies introduced to the aws S3 component in 1.7.0, those being aws-c-common, aws-c-event-streams and its dependencies

https://github.com/awslabs/aws-c-event-stream/issues/34

https://github.com/awslabs/aws-c-event-stream/issues/7

**Comment by KaibaLopez** [comment]
Hi @h3rbg3 ,
I'm not quite understanding what the problem or expectation is here, the SDK does require the 3 projects.

You can either do that manually or let the sdk do it for you (on linux you may need to add "sudo" to your cmake argument), but they must be there to use the sdk. Is it a problem with the error messages not being clear enough or do you just want the sdk to not need them?

**Comment by h3rbg3** [comment]
It did not build these automagically as expected.  I had to research the issue.

**Comment by KaibaLopez** [comment]
that's odd...
Can I ask what version of the sdk you tried? did you get it from source? 
Can you link me to the documentation you're talking about? And if you follow the [instructions on the readme](https://github.com/aws/aws-sdk-cpp#creating-an-out-of-source-build-recommended) does it not try to install them? does it fail on cmake or make?

**Comment by h3rbg3** [comment]
This is the exact method I used (I had to document it for installation purposes)

```
sudo apt update
sudo apt upgrade
sudo apt-get install libcurl4-openssl-dev libssl-dev uuid-dev zlib1g-dev libpulse-dev
git clone https://github.com/aws/aws-sdk-cpp

# newly added dependencies

git clone https://github.com/awslabs/aws-c-common
cd aws-c-common
mkdir build && cd build
cmake ..
make
sudo make install
cd ../..

git clone https://github.com/awslabs/aws-checksums
cd aws-checksums
mkdir build && cd build
cmake ..
make
sudo make install
cd ../..

git clone git@github.com:awslabs/aws-c-event-stream.git
cd aws-c-event-stream
mkdir build && cd build
cmake -DCMAKE_PREFIX_PATH=/usr/local/ -DCMAKE_INSTALL_PREFIX=/usr/local/ ../
make
sudo make install
cd ../..

# build S3 component

cd aws-sdk-cpp
mkdir sdk_build && cd sdk_build

sudo cmake -DBUILD_SHARED_LIBS=ON -DDCMAKE_BUILD_TYPE=Release -DBUILD_ONLY="s3" ../

sudo make
sudo make install
cd ~


# Note that calling sudo make install a second time might produce different results!!!
# (sometimes files weren't written, who knows...)

#This is not needed:
#export CMAKE_PREFIX_PATH=$CMAKE_PREFIX_PATH;/usr/local/include/aws
```

**Comment by KaibaLopez** [comment]
So unless there is some configuration in your environment that I'm missing, I've got 2 things that I think could be happening depending on when it is failing:

_**Assuming it happens when you're trying to build aws-c-event-stream:**_ 
I think the problem happens because aws-c-common and aws-checksums are not installing where you think they are, and so, cmake is not finding them.
By default, the 3 libraries are installed in "/usr/local/include/aws" and so when you build aws-c-event-stream, your `-DCMAKE_PREFIX_PATH=` should point there (by your post it seems like you only added "usr/local"). Of course you can change that location when building the checksums and c-common, but for that you need to add -DCMAKE_INSTALL_PREFIX to their cmake call.

_**Assuming you were actually able to build aws-c-event-stream but are having problems with the aws-sdk-cpp build:**_
There is another thing that may be going wrong here:
```
sudo cmake -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release -DBUILD_ONLY="s3" ../
```
This will make the sdk try and build the dependencies again, if you were already able to build and install the dependencies, then you should just tell cmake where to find them and that should solve your issue:
```
sudo cmake -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release -DBUILD_ONLY="s3" -DBUILD_DEPS=OFF -DCMAKE_PREFIX_PATH=<deps-install-dir> ../
```
Let me know if neither of these options worked for you, and if that's the case when exactly is the error showing?

**Comment by wps132230** [comment]
Hi there, there are known issues with third party dependencies installation need to be fixed.
For temporary workaround, could you build and install third party dependencies as dynamic libraries?
For example, to build aws-c-common, the cmake command is
```
cmake .. -DBUILD_SHARED_LIBS=ON
```

The root cause is because of the change of installation directory of third party dependencies.

When you build aws-c-common as **static** libraries by default, they will install `aws-c-common-targets.cmake` to `<install_dir>/lib/aws-c-common/cmake/static/`. If you open `<install_dir>/lib/aws-c-common/cmake/aws-c-common-config.cmake`, you will find these lines:
```
if (BUILD_SHARED_LIBS)
    include(${CMAKE_CURRENT_LIST_DIR}/shared/aws-c-common-targets.cmake)
else()
    include(${CMAKE_CURRENT_LIST_DIR}/static/aws-c-common-targets.cmake)
endif()
```
That means it depends on the value of `BUILD_SHARED_LIBS`.

After building and installing aws-c-common, aws-checksums and aws-c-event-strem, you build aws-sdk-cpp with `BUILD_SHARED_LIBS=ON`, it will try to find cmake files: `<install_dir>/lib/aws-c-common/cmake/shared/aws-c-common-targets.cmake` and failed.

It's not an issue when we build both aws-sdk-cpp and third party dependencies as shared libraries or both of them are static. But in your case, third party dependencies are static while aws-sdk-cpp are dynamic.

**Comment by h3rb** [comment]
I am the "ghost" .. and I wanted to mention that even when doing what you have suggested (-DBUILD_SHARED_LIBS=ON) it still cannot find it when building the project on which this depends.  It is in that project that it is seeking the static folder (that doesn't exist) where it is in the shared folder.
