### ISSUE TITLE
S3 CopyObject fails silently even when return success

### ISSUE THREAD

**Issue by hicder** [aws/aws-sdk-cpp#1420]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**
I did a `CopyObject` of a file (~55MB) from a source location to a destination location. (Source and destination locations are in different buckets, but both in `us-west-2`). The code is roughly as follow:
```
std::shared_ptr<Aws::S3::S3Client> client_;
auto outcome = client_->CopyObject(request);
```
In this case, `outcome.IsSuccess()` is `true`. However, the file is not copied. We enabled versioning in the destination bucket, however there is no such file ever exists in the destination bucket.

My guess is, the C++ SDK does not handle the case where the request returns a 200 status code, but the response body contains error, as stated in the `CopyObject` [documentation](https://docs.aws.amazon.com/AmazonS3/latest/API/API_CopyObject.html):

> A copy request might return an error when Amazon S3 receives the copy request or while Amazon S3 is copying the files. If the error occurs before the copy operation starts, you receive a standard Amazon S3 error. If the error occurs during the copy operation, the error response is embedded in the 200 OK response. This means that a 200 OK response can contain either a success or an error. Design your application to parse the contents of the response and handle it appropriately.

The official JS SDK does handle this case correctly: https://github.com/aws/aws-sdk-js/blob/dfb49100f7db707a2479726f911ca31443f5a861/lib/services/s3.js#L646

**SDK version number**
1.7.325

**Platform/OS/Hardware/Device**
Ubuntu 18.04

**To Reproduce (observed behavior)**
```
std::shared_ptr<Aws::S3::S3Client> client_;
auto outcome = client_->CopyObject(request);
```

**Expected behavior**
The file is copied successfully.

**Logs/output**
I don't have logs for this.

**Additional context**

**Comment by KaibaLopez** [comment]
Hi @hicder ,
Sorry I got no good news for you, this is a kind of known problem we got... so yea it is a bug, sorry this is affecting you , we're working on it.

**Comment by WolfgangVogl** [comment]
But how do you make sure that there really was no mistake?
Since CopyObjectOutcome returns IsSuccess() true, the result of the type CopyObjectResult can be retrieved by GetResult() or GetResultWithOwnership() methods... but CopyObjectResult has neither a GetBody() nor a GetError() method. So how can I check further here?
(see https://sdk.amazonaws.com/cpp/api/LATEST/class_aws_1_1_s3_1_1_model_1_1_copy_object_result.html)

As a side issue: The example on https://github.com/awsdocs/aws-doc-sdk-examples/blob/master/cpp/example_code/s3/copy_object.cpp does not deal with this case in any way and is wrong from this point of view because success (= copy) is suggested although this is not the case.
