### ISSUE TITLE
TransferManager callbacks

### ISSUE THREAD

**Issue by nakkore** [aws/aws-sdk-cpp#1422]
Confirm by changing [ ] to [x] below:
- [X ] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [X ] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
What are you running the sdk on?
Android - AWS SDK 1.8.2
**Describe the question**
**Transfer Status and error callbaks**
I've noticed that for a given file upload in progress, had the device experience networking issues (sudden loss of connectivity) the transfer status callback and error callbacks are called multiple times reporting the same status:  for example the error callback reports many NETWORK_CONNECTION errors and the transfer status callbacks reports multiple STATUS_FAILED statuses. Now I suppose this multiple notifications happen because the upload in reality it's a multipart upload so each callback it's triggered from the relative upload part. My question is: can I be notified for the overall process rather than for each single part ? 
When things goes well and the transfer is succesful I  get notified with a single status COMPLETED. Why this is not happening for a non successful transfer ?  Can it be achieved ? Or Am using wrongly the API ? 
I wouldn't expect to use TransferHandle::WaitUntilFinished to understand that the transfer ended giving I'm relying on callbacks. Am I right in thinking this ?

Thanks in advance

**Comment by KaibaLopez** [comment]
Hi @nakkore ,
I would have to know more about your use case to know for sure, for example, it might be retrying (and failing) to reconnect a bunch of times.
 Could you show me your debug logs (make sure to sanitize them of private info)?

**Comment by nakkore** [comment]
Hi sure,
to exclude retries I've configured config.retryStrategy = std::make_shared<Aws::Client::DefaultRetryStrategy>(0);
I'm not doing any retries in the code. 
I've attached the relevant log when the first sequence of errors start which happens when, while there's an upload in progress, I put the phone in flight mode.
[aws.log](https://github.com/aws/aws-sdk-cpp/files/4988256/aws.log)

Hope it helps.

P.S.
I had to remove from CurlHttpClient.cpp::CurlDebugCallback the debug print which prints the buffer as it was generating non useful noise (else branch). Would it be more useful if it optionally printed an hexdump instead ?

**Comment by nakkore** [comment]
@KaibaLopez did you have a chance to check the log please ?

**Comment by KaibaLopez** [comment]
sorry for the slow updates @nakkore , but yea regarding the questions:

> can I be notified for the overall process rather than for each single part ?

I guess it depends on what you mean by "notified" ? The Trace logs will happen for each part, because each part is a different request, which gets a response, this is true for successes too btw.... but just the same way you get a TransferStatus::COMPLETE,for successful calls, you can get TransferStatus::FAILED once its all done.

> I wouldn't expect to use TransferHandle::WaitUntilFinished to understand that the transfer ended giving I'm relying on callbacks. 

I'd still use TransferHandle::WaitUntilFinished.... you don't really **_HAVE_** to I guess but then it's up to you to know when all the threads working on the upload are finished, all that the function does is having a semaphore wait for a signal anyway so you can do that yourself on your callbacks.

Sorry about the earlier confusion and let me know if I misunderstood something about your questions again.

**Comment by nakkore** [comment]
Thank you @KaibaLopez. You correctly say that I get one TransferStatus::COMPLETE for the overall transfer and that's true but the same doesn't apply for the TransferStatus::FAILED where, instead, I receive multiple calls: see my first comment and that's the point of my report.
By "notified", sorry If I wasn't clear enough, I meant that the callback is triggered. To make things clearer I'm referring to the transferStatusUpdatedCallback and errorCallback which are configured in TransferManagerConfiguration. 

For example and to be more precise the FAILED callback, when the transfer fails in my case, is triggered at TranferManager.cpp line 409 (in DoMultiPartUpload) but also at TranferManager.cpp line 533 (in **HandleUploadPartResponse**) and line 588 (in **HandleUploadPartResponse**). So it's not happening once as I expected and as you've stated but it's happening multiple times. 
If I've understood correctly the code the FAILED for the overall transfer should be the one raised in DoMultiPartUpload . The other unexpected FAILED calls come from HandleUploadPartResponse.
For reference line numbers refer to the 1.8.15 SDK.

I hope it's clearer.

P.S
For the use of WaitUntilFinished:
In my mind If I used WaitUntilFinished it means that I want to block until I get a result making, de facto, the calls to UploadFile/DownloadFile blocking. By using WaitUntilFinished I don't see the point using callbacks If I have to wait.
If I used only callbacks it means that I don't want to block and I want to be "notified" when the transfer completes or errors.

**Comment by KaibaLopez** [comment]
Hi @nakkore ,
So there's a few things here: 

> If I've understood correctly the code the FAILED for the overall transfer should be the one raised in DoMultiPartUpload . The other unexpected FAILED calls come from HandleUploadPartResponse.
I mean, I wouldn't say unexpected, each part is a unique "upload" so it is important to know the response to each, specially if it failed. But yea the overall comes from DoMultiPartUpload.

> You correctly say that I get one TransferStatus::COMPLETE for the overall transfer and that's true but the same doesn't apply for the TransferStatus::FAILED.

This is the part that's confusing, I can see in the logs you provided, the very last line states a change to the update handle status to Failed, that is the status of the overall call. 
But I can see also that the update handle to FAIL status change happens twice, which is kind of weird, I was also able to reproduce this so I'll look into it a bit, I think it's related to the last "batch" of async calls, but I'd have to dig a bit further to be sure.

Finally, Regarding WaitUntilFinished, I think we are kind of in agreement that it is up to you when to use the semaphore/mutex but:

> In my mind If I used WaitUntilFinished it means that I want to block until I get a result making, de facto, the calls to UploadFile/DownloadFile blocking

True, the calls would be blocking, but they kind of have to be since they are multi threaded operations at some point you need to coincide...Now this doesn't mean you have to be waiting right after the upload call, so the point of the callbacks is that you can do other stuff while that is happening, you just need to block (via your own semaphore/mutex or calling WaitUntilFinished) before you try to access the response/outcome and/or before you try to exit the application, here's a quick example of what I mean:
```
    auto uploadHandle = transferManager->UploadFile(file, bucket , name, "text/plain", Aws::Map<Aws::String, Aws::String>());

/* here you can do other stuff unrelated and with no access to uploadHandle , and this could be the bulk of your code so long as you don't touch uploadHandle it should be safe*/

    uploadHandle->WaitUntilFinished(); 
    bool success = uploadHandle->GetStatus() == TransferStatus::COMPLETED; // to get this you need to know the threads have all ran their course so you need to block the callbacks.
    if(success){/*do more stuff that's related to the uploadHandle result*/}
    else{/*get error or whatever*/}

    Aws::ShutdownAPI(options); // To get here as well, you need to be sure the threads have finished.
```

I hope this clears some things up at least? And I'll get back to you on why the upload Handle is updated to FAILED twice sometimes. 
Again, let me know if I misunderstood something or if you got other questions.
