### ISSUE TITLE
Cognito requests crashes on callback if interrupted or handler is removed. How can we clean the Cognito module?

### ISSUE THREAD

**Issue by DevGarou** [aws/aws-sdk-cpp#1436]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**
I am implementing this in Unreal engine version 4.23. All modules of Aws are loaded at the startup. 
Everything seems to be well implemented and functionning but when I am in the editor and I play my game, if I close the session and therefore remove the instance of the class that holds the handler of an async function the app crashes because the Aws Cognito module is trying to call back the handler.

**SDK version number**
1.7.314

**Platform/OS/Hardware/Device**
What are you running the sdk on?
Windows

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code)
Create a class that will call an async function on the Aws Cognito client module and that pass it a handler that is a class method.
in the main.cpp:
Init the SDK. Create a class instance. Call the async function. Removes the class instance from memory. See the crash.

**Expected behavior**
I was hoping that I could find a Clean function to call on the Cognito Client Pointer so it could remove all delegates or non existing references or pointers but I didn't see that.

**Logs/output**
If applicable, add logs or error output.

To enable logging, set the following system properties:

*REMEMBER TO SANITIZE YOUR PERSONAL INFO*

```
options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Trace;
Aws::InitAPI(options)
```

**Additional context**

**Comment by KaibaLopez** [comment]
Hi @DevGarou ,
The steps to reproduce are a bit vague, from the description it sounds to me like an async function syncing problem rather than a bug, our async functions do not automatically wait for closure, it is up to you on how to use semaphores or mutexes when calling them.
So in your case I'd suggest using a mutex and wait for it to unlock before removing the instance from memory.
If you need more specific help, I'm going to need sample code on what you're trying to do so I can either point out the recommended way of doing it or so that I can run and reproduce the error.
