### ISSUE TITLE
The requested file could not be opened

### ISSUE THREAD

**Issue by neelam256** [aws/aws-sdk-cpp#1460]
Hello,
Some time, when I upload the file to s3, I am getting following error "The requested file could not be opened". This error is intermittent and I can't reproduce this in local.
I can see at the same time file got uploaded on s3 by comparing the logtime and s3 update time.
Please help.

**Comment by KaibaLopez** [comment]
Hi @neelam256 ,
I'm going to need more information to be able to help. I need to know what the full error is and when exactly it happens? is it the putObject request that returns that failure? or are you trying to getObject on something that you previously uploaded? Was it on big or small files? does it happen with certain file types?
If you could give me some minimal sample code that reproduces the error, even if it is just sometimes, that would make things a lot faster too.

**Comment by neelam256** [comment]
Hello @KaibaLopez ,
Thanks for response,  yes it is for putobject which is returning the error, and it not only for certain file file types. file size is approx ~20 MB.  please see the attached code.
[awsputobject.txt](https://github.com/aws/aws-sdk-cpp/files/5220906/awsputobject.txt)


Thanks
Neelam

**Comment by KaibaLopez** [comment]
Hi @neelam256 ,
Hmm I have not been able to reproduce the error, and the size should not be a problem, the "The requested file could not be opened" error most commonly that happens because of a typo on the file name (which is my guess here since in your code you manually input the file name) but could also be a serialization error, lack of permissions on the file, or lack of free memory space...  Could you show me the trace log (remember to clear credentials and other sensible information from it) of a time when it fails?

**Comment by neelam256** [comment]
@KaibaLopez  can you give example or point out to get detail error message and better error handling.

**Comment by KaibaLopez** [comment]
to activate the trace logs add these lines to your code:
```
Aws::SDKOptions options;
options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Trace;
Aws::InitAPI(options);
...
```
That will create a log file with all the steps the sdk went by.
As far as error handling I usually just use something like `put_object_outcome.GetError().GetMessage()`
