### ISSUE TITLE
S3Client: access headers of successful responses

### ISSUE THREAD

**Issue by pitrou** [aws/aws-sdk-cpp#1466]
**Is your feature request related to a problem? Please describe.**
When a `S3Client` method returns with a successful `Outcome`, neither the outcome nor the wrapped result give you acces to the HTTP response headers. For example, you can't get the value of a hypothetical "x-amz-bucket-region" header. But there are probably other user cases.
(conversely, in case of error, the `AWSError` class gives you access to the HTTP response details)

I tried using `SetDataReceivedEventHandler` to intercept the HTTP response, but that handler is only called if the response actually has a body. So HEAD requests don't trigger the handler...

**Describe the solution you'd like**
A possible solution would be to add a `const HeaderValueCollection& GetResponseHeaders () const` method to `Outcome` (or to a dedicated subclass of `Outcome`).

Another possible solution would be to add a `void SetHeadersReceivedEventHandler(...)`, that handler would be called once when all response headers are received (even if there's no body). The handler's type would probably be `std::function<void(const HttpRequest*, HttpResponse*>`.

**Describe alternatives you've considered**
Currently, I'm writing a `S3Client` subclass so that I can access protected members of `S3Client` and cook the HTTP request manually, call it using `MakeRequest` and then read the headers on the response. But that's cumbersome and fragile. Also, some thing are not available (for example `ComputeEndpointString()` is private, so I can't compute the region signer).

**Comment by KaibaLopez** [comment]
Hi @pitrou ,
So... I think there are workarounds for this kind of thing, for example, most of the header info is saved in the objects metadata or object's properties, and we've also got `HeadObjectRequest` and `HeadBucketRequest` and their result returns just the headers, is there a reason why you can't or don't want to use those?

**Comment by pitrou** [comment]
Unless I'm missing something, `HeadBucketOutcome` is an alias of `Aws::Utils::Outcome<Aws::NoResult, S3Error>`, and `Aws::NoResult` doesn't give access to the response headers.

**Comment by KaibaLopez** [comment]
sorry yea you're right, but the point was more like "there are ways to get the information". As in getting a buckets region is doable without looking into the headers, there is a request specifically for that: `GetBucketLocation`.

Now I get that that is only one header, but I'm trying to see if there are workarounds to this problem you're having because a feature request like this one will potentially take a long time for the team to get to. I'm not saying it's not doable, but it would probably be low priority since it's not really something that blocks usage of the SDK.

If you can specify more on what exactly you're trying to do and why that is not possible without this (or a similar) change, then I might be able to push for the feature.

**Comment by pitrou** [comment]
`GetBucketLocation` only works if you're the bucket owner, which does not satisfy the general use case.

**Comment by tusharjagtap** [comment]
Hi, are there any plans to fix this issue?
