### ISSUE TITLE
Why the API named PutObject not support SetHeaders in aws-sdk-cpp-s3 module?

### ISSUE THREAD

**Issue by ToBeMyOwnHero** [aws/aws-sdk-cpp#1473]
I saw S3 supported the StreamS3Request class and the S3Request class, however, the S3Requset class support SetHeaders but another not support.I really want to know the reason.

**Comment by KaibaLopez** [comment]
Hi @ToBeMyOwnHero ,
So first, the intended way to set headers in PutObjects is by using metadata, either use `AddMetadata()`, `SetMetadata()` or `WithMetadata()`.
Now as to why the sdk was built this way, I believe the idea is that some of the object headers are "required" to meet with the service's standard, it doesn't expose that so that the user doesn't have to know about them, but as I mentioned before, it allows the user to add extra headers in the form of metadata.

Let me know if this answers your question or if I missed something.

**Comment by ToBeMyOwnHero** [comment]
Thanks for your answers！It reallyt clear  my idea.
