### ISSUE TITLE
iOS 14 Privacy - SDK pops up permission request to "find and connect to devices on local network"

### ISSUE THREAD

**Issue by triton3** [aws/aws-sdk-cpp#1516]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
What are you running the sdk on?
iOS 14.2 

**Describe the question**
On iOS 14, initializing the cognito identity client results in a pop-up asking for permission to allow the app to find and connect to devices on local network. Disallowing permission still works, but this is a privacy concern. 

Why does it need this permission?

```
auto cognito_id_client = std::make_shared<Aws::CognitoIdentity::CognitoIdentityClient>(config);
```

**Logs/output**
![iOS-interstitial](https://user-images.githubusercontent.com/13472986/99442302-2fd55a80-28e7-11eb-848c-082472d7679a.jpg)

**Comment by KaibaLopez** [comment]
Hi @triton3 ,
Just wanted to write a bit of an update, this is the first time I see something like that so I'll try looking into it but it might take some time to figure out. I'll update as soon as I find something useful.

**Comment by triton3** [comment]
@KaibaLopez Thank you for the update. The sdk version is 1.4 on our side. Please let me know if you need any other information.

**Comment by KaibaLopez** [comment]
@triton3 ,
So, that is a very old version of the sdk , and it makes things harder to test, can you use a newer (newest would be better) version?

**Comment by triton3** [comment]
@KaibaLopez The reason we havent updated to the latest version is because there were many breaking changes in the sdk, that required a full overhaul. Is there anything we can do to check with the version we have? I can put up the aws sdk source zip file and share through a private message using dropbox, if that helps.

**Comment by triton3** [comment]
@KaibaLopez Just wanted to check if there is any update? Any advice is appreciated.

**Comment by KaibaLopez** [comment]
Sorry for the long wait, the only updates I've got is that this seems to be caused by a new iOS14 privacy feature, here's a helpful thread on the [iOS dev forums](https://developer.apple.com/forums/thread/663858).
Been trying to test things out but with no real luck finding the root cause, from what I can tell it looks like a false positive on iOS 14 local network privacy warning, which btw I can find a bunch of similar cases, I just haven't been able to prove that's the case.

I can say that the SDK version doesn't really matter, so no problem if you don't update.

Sorry I can't be of more help here, I'll keep trying but it does seem like it will be a while until I find it, I am not really an expert on iOS development and other issues will take priority over this at least for the time being.

Having said that, I will keep this open in the hopes that other community members might see this and contribute ideas.

**Comment by triton3** [comment]
@KaibaLopez Thank you for the update.

**Comment by jstock78** [comment]
We're having the problem.  For us it happens when constructing the Aws::Client:ClientConfiguration.
  
_clientConfig = Aws::MakeShared<Aws::Client::ClientConfiguration>("mem_AwsClientManager");

**Comment by jstock78** [comment]
Update: we were able to get around the prompt by setting the AWS_EC2_METADATA_DISABLED environment variable to TRUE before initializing our ClientConfiguration.

>         setenv("AWS_EC2_METADATA_DISABLED", "TRUE", true);
>         _clientConfig = Aws::MakeShared<Aws::Client::ClientConfiguration>("mem_AwsClientManager");

**Comment by triton3** [comment]
@jstock78 Thanks! We will try this as well...
