### ISSUE TITLE
How to pass other type argument to aws lambda function invoked by aws sdk c++

### ISSUE THREAD

**Issue by GitZinger** [aws/aws-sdk-cpp#1529]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
What are you running the sdk on?
win 10  

**Describe the question**
Local end I am working on aws sdk c++ and at cloud end, it is the python lambda function.
How can I pass other type arguments like OpenCV Mat data into the python lambda function to process it and return the processed data to local end?
I saw the example on https://docs.aws.amazon.com/code-samples/latest/catalog/cpp-lambda-lambda_example.cpp.html, it seems they are string type and in json style.
```
jsonPayload.WithString("key1", "value1");
  jsonPayload.WithString("key2", "value2");
    jsonPayload.WithString("key3", "value3");
```

**Logs/output**
If applicable, add logs or error output.

To enable logging, set the following system properties:

*REMEMBER TO SANITIZE YOUR PERSONAL INFO*

```
options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Trace;
Aws::InitAPI(options)
```

**Comment by KaibaLopez** [comment]
@GitZinger ,
Can you provide minimal sample code on what you're trying to do and which specific call you'd like to change, as is the description is kind of broad and I might suggest the wrong thing depending on the situation....

For example, I could say that you send the same type of json type and instead of having:
`jsonPayload.WithString("key1", "value1");`
you'd have to convert your CV::Mat to double and then send it:
`jsonPayload.WithDouble("key1", 3.41);`

But without seeing what you're trying to do I'm not 100% sure that's correct.

**Comment by GitZinger** [comment]
Yes. But I guess both the arguments and response or return have the limitation of the data. So eventually it is not working. it has to work with S3. Thank you
