### ISSUE TITLE
[Feature] Precompiled Binaries

### ISSUE THREAD

**Issue by ChrisCates** [aws/aws-sdk-cpp#1551]
### Problem

Right now, AWS asks you to compile the SDK from scratch. While the instructions are simple, straightforward and are easy to follow... It's a fairly time consuming process to get from `clone` to `make install`.

It would be great if there was some sort of public S3 bucket where you could curl binaries for specifics archs you need.

#### Use `curl` and `wget`

We really don't need to get bogged down with Linux/Darwin/DOS package managers like `apt`, `brew` or `choco`. Instead, it would be best if there was a straightforward to curl your desired arch binaries to your local include folder.

A good example snippet of how the end result implementation would look like is:

```bash
curl https://some-s3-bucket.com/arch.gz -o s3-sdk-arch.gz
gunzip s3-sdk-arch.gz /usr/local/...
...
# the actual commands may need to be slightly different.
```

#### Create a Unix compatible bash script

This is far more effort to develop and maintain. (Take a look at `nvm` for an example of level of effort to implement). However, it would make it even easier for developers. Where you'd literally just have to run some like:

```bash
curl https://universal.shell.script -o universal.script.sh
sh universal.script.sh
```

Only posting this here, since it would be a handy feature to integrate into the AWS C++ Ecosystem.

-- Chris

**Comment by KaibaLopez** [comment]
@ChrisCates ,
Not sure if we would take this request for like git clone or curl get each service component, but we do support a way to build only the services you need so that the building process doesn't take quite as long, you can [look here for more info](https://github.com/aws/aws-sdk-cpp/blob/master/Docs/CMake_Parameters.md#build_only), but basically just add the cmake parameter `-DBUILD_ONLY=<service_name>` (for multiple services separate them by ';') for example: 
```cmake <source_dir> -DBUILD_ONLY="s3;dynamodb;transfer"```
Would build only the s3, transfer manager and dynamodb services.
Let me know if that helps.

**Comment by ChrisCates** [comment]
@KaibaLopez, so the way I see it is there would be a `.tar.gz` file for each service stored in AWS S3.

Example:

```
libaws-cpp-sdk-alexaforbusiness.tar.gz
libaws-cpp-sdk-firehose.tar.gz
libaws-cpp-sdk-amplifybackend.tar.gz
libaws-cpp-sdk-amplify.tar.gz
````

And then in the `.sh` script you `curl` and then run. It would unzip and then transfer those files to `/usr/local/lib` or could have a flag like: `sh script.sh --path /usr/local/alternative/path`

**Comment by KaibaLopez** [comment]
I think I wasn't really clear on the last comment but, the problem is supporting precompiled binaries, the short reason for that being that the sdk is not a header only library so there is just too many variables.
It's kind of a c++ limitation... I found this [stack overflow question](https://stackoverflow.com/questions/62328574/why-many-projects-dont-provide-a-pre-compiled-binary-file) that pretty much explains why it's just not normal practice for non header only libraries in case you wanna read more about that.

**Comment by ChrisCates** [comment]
@KaibaLopez, completely reasonable.

In this case, we would just want to have a Universal Install script that can be ran via something like:

```bash
curl -o- https://cdn.aws.com/aws-sdk-cpp/install.sh | bash
```

And would automatically compile the project correctly for said Arch.
Further more, it could be granularized with flags like:


```bash
curl -o- https://cdn.aws.com/aws-sdk-cpp/install.sh | bash --components S3,EC2 #etc etc
```

---

This is lower priority and don't worry about this too much.
Better to focus on stable compiles on all archs.

Keep this issue as a reference for the future though.

**Comment by KaibaLopez** [comment]
so while that'd be cool, I think we'd find ourselves in the same "hard to maintain" situation where we'd have to have a bunch of scripts (at least one for each OS). 
But yea, I mean we kind of do that for docker images so it may be possible, will keep it open as reference and also to kind of gauge interest on this kind of request.

**Comment by ChrisCates** [comment]
Absolutely, let's not increase scope for the time being.
Most important is making sure compiling is smooth for end users.

Looking forward to seeing new updates come in soon! Cheers.

**Comment by NewbiZ** [comment]
Supporting pre-built releases would definitely be a great improvement for adoption.

It's a real pain to ask everyone using a library indirectly depending on the AWS SDK for C++ to manually download and build it.

**Comment by ChrisCates** [comment]
@NewbiZ, the alternative is to go the header based route instead of `.so` lib files.

They don't seem to want to do a header based library. Even though I think this is what the C++ community needs to survive Rust.

**Comment by ChrisCates** [comment]
@NewbiZ yea, fair enough, doesn't solve C++ having a Rust package manager (CMake is nowhere close). Anyway, let's see what the boys at AWS are going to respond.

**Comment by NewbiZ** [comment]
Honestly I'm fine with doing the work of automating the construction of a pre-built `.tar.gz` and `deb` package, hosted on github release, it's really not much work. But I need some assurance it will be merged and not just PR ghosted.
