### ISSUE TITLE
WaitUntilFinished abort abnormally

### ISSUE THREAD

**Issue by bryce-shang** [aws/aws-sdk-cpp#1591]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x ] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x ] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**

`WaitUntilFinished` abort abnormally.

```cpp
# transfer_manager is created via Aws::Transfer::TransferManager::Create(transfer_configuration);
auto get_handle = transfer_manager->DownloadFile(s3_bucket_name, s3_object_name, Aws::String(file_name.c_str()));

# Abort abnormally
get_handle->WaitUntilFinished();
```

**SDK version number**
1.8.161
This issue does not happen on `1.7.316`

**Platform/OS/Hardware/Device**
What are you running the sdk on?

Ubuntu 20.04

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code)

See description

**Expected behavior**

Not abort

**Logs/output**
No error. The line of code crashes.

*REMEMBER TO SANITIZE YOUR PERSONAL INFO*

```
options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Trace;
Aws::InitAPI(options)
```

**Additional context**

**Comment by jmklix** [comment]
Can you provide a code sample that reproduces this?

**Comment by bryce-shang** [comment]
The sample code was provided in `Describe the bug`. The code should be good for reproducing the bug.

**Comment by KaibaLopez** [comment]
@bryce-shang ,
I am going to need some more info to help you with this:
* A quick code sample on what you're trying to do. And to be clear here, I can see the 2 lines you think are problematic but I have tests on transfer manager's download file and those are passing so I am guessing you are either missing something on your code or you've hit an edge case.
* The full trace logs generated when you are seeing this problem (remember to sanitize them for private information). This will also help me pin-point the problem if it is an edge case happening and give me more insight on what the problem is.
* More details on the object you are trying to download: Size, object type, bucket info... These shouldn't really matter but if those are affecting TransferManager's behavior then it would be a higher impact bug so might as well get as much info as we can.
