### ISSUE TITLE
Missing functionality of removing all tags from CloudFormation stacks.

### ISSUE THREAD

**Issue by chiyuchentw** [aws/aws-sdk-cpp#1616]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**
I think it is the same issue as what had been reported in the java SDK https://github.com/aws/aws-sdk-java/issues/721 where the report gave an empty collection as the tags input but the parameter got totally ignored and the stack tags were not touched at all. I am facing the same problem when calling client.CreateChangeSet() with an empty vector as tags input in cpp SDK. Looking for a way to clean up all tags on CloudFormation stacks. Any suggestion would be appreciated.

**SDK version number**
1.7.281

**Platform/OS/Hardware/Device**
Linux 4.4.182+

**Expected behavior**
Remove all tags from CloudFormation stacks when making a call to CreateChangeSet with an empty vector as tags input.

**Logs/output**
Apr 12 14:26:58.325 EFCD4950145B I      svc.cloudformation Done waiting for change set changeset-11486144855441624375 for cloudformation stack *****, status FAILED, reason The submitted information didn't contain changes. Submit different information to create a change set., execution status UNAVAILABLE

**Comment by KaibaLopez** [comment]
Hi @chiyuchentw ,
Sorry for the slow response, and yea it seems like this is a functionality missing from various SDKs, I'm looking into it but wanted to give a bit of an update.
I don't know how much it helps but guess I should mention as a sort of workaround this: 
Because of the way the C++ SDK implements this, you could erase "all but one tag" this way. Meaning if you make a changeset with only one tag it would delete all the other tags previously there.
Thanks for pointing this out to us.
