### ISSUE TITLE
[Curl] Use libcurl's multi interface instead of threading?

### ISSUE THREAD

**Issue by timtianyang** [aws/aws-sdk-cpp#1637]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution

Just out of curiosity, have we considered using libcurl's multi interface, in stead of having multiple threads in transfer manager each blocking on a curl easy handle? For applications that want to use a large number of connections in parallel, sounds like using select() and asynchronous programming would have great performance. According to s3 guidelines, we can still break up files into chunks, and scale horizontally with parallel connections with a single thread. Thoughts?

Current operations where we are limited by number of threads and handles.
thread0  -> curl easy handle
thread1  -> curl easy handle
...
threadn  -> curl easy handle
Application thread -> wait for download or poll download progress...

With multi-interface:
Application thread  -> poll curl multi handle (that can scale to 10k+ easy handles) -> application code/callbacks

**Comment by KaibaLopez** [comment]
Hey @timtianyang ,
Hmm yea I'll look into it, I can't really say what the reasoning behind the decision was at the time since I wasn't there, but it makes sense and sounds worth while to at least revisit and see how much work it'd take.
In the mean time, thanks for pointing this out to us! I'll re-lable as a Feature Request and update the issue once we figure it out.
