### ISSUE TITLE
Ubuntu 20.04 does not work. This new re-organized repo is a mess

### ISSUE THREAD

**Issue by xanather** [aws/aws-sdk-cpp#1673]
For one of the richest companies in the world I am amazed at how hard you broke everyone's CI. Does any kind of testing go on here beyond AWS own environments? Why is AWS designing new open-source libraries pulled in via git submodules which conflict with the names of older libraries that have been around for decades.

I don't want to waste any more time than I already have today, but these two scenarios are completely broken and all the documentation all over aws site is now also wrong now.

**Ubuntu 20.04 attempt 1:**
```
  git clone https://github.com/aws/aws-sdk-cpp.git --depth 1 --recursive
  cd aws-sdk-cpp
  mkdir sdk-build
  cd sdk-build
  cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_ONLY="cloudformation;ec2;monitoring;ssm;s3;cloudfront" -DENABLE_TESTING=OFF
  make
  make install
```
Attempting to use:
```
find_package(AWSSDK REQUIRED COMPONENTS cloudformation ec2 monitoring ssm s3 cloudfront)
```
Results: completely falls over, need to specify BUILD_SHARED_LIBS in our own CMakeLists for some reason. Then complains about LibCrypto probably due to s2n confliction.

**Ubuntu 20.04 attempt 2:** using a custom install prefix to avoid polluting the system and supporting multiple versions of the library:
```
  git clone https://github.com/aws/aws-sdk-cpp.git --depth 1 --recursive
  cd aws-sdk-cpp
  mkdir sdk-build
  cd sdk-build
  cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_ONLY="cloudformation;ec2;monitoring;ssm;s3;cloudfront" -DENABLE_TESTING=OFF -DCMAKE_INSTALL_PREFIX="$mainDir/third-party/aws-sdk-cpp/sdk-install"
  make
  make install
```
Attempting to use (assuming I built in third-party/aws-sdk-cpp):
```
  set(PREV_BUILD_SHARED_LIBS ${BUILD_SHARED_LIBS})
  set(BUILD_SHARED_LIBS ON)
  set(AWSSDK_ROOT_DIR "${CMAKE_SOURCE_DIR}/third-party/aws-sdk-cpp/sdk-build")
  set(s2n_DIR "${CMAKE_SOURCE_DIR}/third-party/aws-sdk-cpp/sdk-install/lib/s2n/cmake")
  set(aws-crt-cpp_DIR "${CMAKE_SOURCE_DIR}/third-party/aws-sdk-cpp/sdk-install/lib/aws-crt-cpp/cmake")
  set(aws-c-common_DIR "${CMAKE_SOURCE_DIR}/third-party/aws-sdk-cpp/sdk-install/lib/aws-c-common/cmake")
  set(aws-c-http_DIR "${CMAKE_SOURCE_DIR}/third-party/aws-sdk-cpp/sdk-install/lib/aws-c-http/cmake")
  set(aws-c-io_DIR "${CMAKE_SOURCE_DIR}/third-party/aws-sdk-cpp/sdk-install/lib/aws-c-io/cmake")
  set(aws-c-cal_DIR "${CMAKE_SOURCE_DIR}/third-party/aws-sdk-cpp/sdk-install/lib/aws-c-cal/cmake")
  set(aws-c-compression_DIR "${CMAKE_SOURCE_DIR}/third-party/aws-sdk-cpp/sdk-install/lib/aws-c-compression/cmake")
  set(aws-c-mqtt_DIR "${CMAKE_SOURCE_DIR}/third-party/aws-sdk-cpp/sdk-install/lib/aws-c-mqtt/cmake")
  set(aws-c-auth_DIR "${CMAKE_SOURCE_DIR}/third-party/aws-sdk-cpp/sdk-install/lib/aws-c-auth/cmake")
  set(aws-cpp-sdk-core_DIR "${CMAKE_SOURCE_DIR}/third-party/aws-sdk-cpp/sdk-install/lib/cmake/aws-cpp-sdk-core")
  find_package(AWSSDK REQUIRED COMPONENTS cloudformation ec2 monitoring ssm s3 cloudfront PATHS "${CMAKE_SOURCE_DIR}/third-party/aws-sdk-cpp/sdk-install" NO_DEFAULT_PATH)
  set(BUILD_SHARED_LIBS ${PREV_BUILD_SHARED_LIBS})
```
Yes, thats right, I have to set all those directories. Then complains about "Could NOT find LibCrypto (missing: LibCrypto_LIBRARY LibCrypto_INCLUDE_DIR)"

Note: AWSSDK_ROOT_DIR is no longer used correctly and ignored for ALL dependencies now it seems.

Bit late to turn master branch back now, this mess should've never been pushed.

**Comment by xanather** [comment]
Side note: Consuming this library without using cmake's find_package now is just about impossible without reverse engineering the structure of the repo.

**Comment by wps132230** [comment]
Hi @xanather , sorry about providing these bad experience.
We don't have Ubuntu 20.04 in our CI and failed to catch some issues with it, and we started to make improvement in it.

For your attempt 1, we switch to use openssl (instead of aws-lc) by default now, and it won't install any libcrypto or libssl libraries which would populate your system default openssl anymore. https://github.com/aws/aws-sdk-cpp/commit/212bc2e2e789f8239bd3f81b0ba3ec73d0ad8593

For your attempt 2, we've fixed an issue where `mark_as_advanced()` and `find_path()` combination remove local variables such that SDK is not able to find `libcrypto`. https://github.com/aws/aws-sdk-cpp/commit/de387275f5982501d6b578c7ddefed5d9131512c

When you build your application with the latest C++ SDK, in theory, you don't need to specify `BUILD_SHARED_LIBS` or provide hard-coded path to those dependencies if they are installed into system directories. Or `CMAKE_PREFIX_PATH` is sufficient if you install SDK with `CMAKE_INSTALL_PREFIX`.

We have some basic tests for Ubuntu 20.04 in CI now. And could you try the latest version of SDK to see if those fixes work for you? And please let us know if you still encounter a build issue that is uncovered by CI.
