### ISSUE TITLE
installing AWS SDK for C++

### ISSUE THREAD

**Issue by versacex** [aws/aws-sdk-cpp#1675]
downloaded the zip from git and unzipped to location

ran command "C:\program files\cmake\bin\cmake.exe" c:\code\aws-sdk-cpp-main -G "Visual Studio 16 2019" -A x64 -DCMAKE_BUILD_TYPE=Debug

but getting errors
- fatal error C1083: Cannot open include file: 'unistd.h'
- error C2065: 'umask': undeclared identifier [C:\code\aws_build\CMakeFiles\CMakeTmp\cmTC_9cf0f.vcxproj]

the second im pretty sure is a symptom of the first

any thoughts? I straight unzipped the sdk from git and ran cmake with above command... not sure if the unistd.h file is just missing from the download or what

**Comment by KaibaLopez** [comment]
Hi @versacex ,
Since version 1.9 the SDK has been using submodules to consume it's dependencies, this has had the side effect of making building from the zip file very compicated, and so at the moment we don't really recommend it, see #1648 .
If possible, I'd suggest using `git clone --recurse-submodules https://github.com/aws/aws-sdk-cpp` to get the sdk. 
If that's not an option, we do have a script to make it work but it is meant for linux based systems. [look here](https://github.com/aws/aws-sdk-cpp/blob/main/prefetch_crt_dependency.sh).
