### ISSUE TITLE
ExpiredToken exception even if expiration is checked on instance profile credentials

### ISSUE THREAD

**Issue by lordgamez** [aws/aws-sdk-cpp#1684]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
AWS EC2 - Ubuntu 20.04

**Describe the question**
We are running a deployment in kubernetes on top of EC2 that uploads data to S3. Our service uses AWS SDK with instance profile credentials for S3 authentication. For this we are using `Aws::Auth::DefaultAWSCredentialsProviderChain` to retrieve and cache the credentials in a simple way:

`auto creds = Aws::Auth::DefaultAWSCredentialsProviderChain().GetAWSCredentials();`

The problem is that this long running service start failing after a few days with the following message:
```
HTTP response code: 400
Exception name: ExpiredToken
Error message: Unable to parse ExceptionName: ExpiredToken Message: The provided token has expired.
```
It seems that the credentials expire after a while so we thought the problem is that we are caching the credentials and that's why they are not getting refreshed. 

Now before every upload, we check if the stored credentials are expired with the `Aws::Auth::AWSCredentials::IsExpiredOrEmpty` check and refresh them using `DefaultAWSCredentialsProviderChain` again. But even after checking the expiry of the credentials the problem still persists and the upload fails after a few days. Is there a proper way to refresh the instance profile credentials or check for expiry?

**Comment by KaibaLopez** [comment]
Hi @lordgamez ,
> It seems that the credentials expire after a while so we thought the problem is that we are caching the credentials and that's why they are not getting refreshed.


So, yes they do expire. The problem with your approach is that there might be a clock skew in between, like the credentials could return as valid when you check but become invalid before you do the check again, or they could even not be expired locally but expired in the server. 
This can be mitigated by checking range before it expires.

Can you provide small sample code on how you are doing this? I might not be able to reproduce just because of the nature of the process but I want to see how you are caching the credentials or how it was running before you tried that solution.

**Comment by lordgamez** [comment]
Hi @KaibaLopez,

Here's a small code sample of a simplified version how we handle it:
```
class AwsCredentialsProvider {
 public:
  Aws::Auth::AWSCredentials getAWSCredentials() {
    return Aws::Auth::DefaultAWSCredentialsProviderChain().GetAWSCredentials();
  }
};

class AWSCredentialsService {
 public:
  Aws::Auth::AWSCredentials getAWSCredentials() {
    if (aws_credentials_->IsExpiredOrEmpty()) {
      aws_credentials_ = aws_credentials_provider_.getAWSCredentials();
    }
    return aws_credentials_;
  }

 private:
  AWSCredentialsProvider aws_credentials_provider_;
  Aws::Auth::AWSCredentials aws_credentials_;
};

void onTrigger(AWSCredentialsService& service, ConfigProvider& config_provider, RequestBuilder& request_builder) {
  auto credentials = service.getAWSCredentials();
  auto client_config = config_provider.getClientConfig();
  auto request = request_builder.buildNextRequest();
  Aws::S3::S3Client s3_client(credentials, client_config);
  s3_client.PutObject(request);
}

int main() {
  AWSCredentialsService service;
  ConfigProvider config_provider;
  RequestBuilder request_builder;
  while(true) {
    onTrigger(service, config_provider, request_builder);
    std::this_thread::sleep_for(std::chrono::seconds(10));
  }
  return 0;
}
```
Beforehand we did not check `IsExpiredOrEmpty` so it was always cached, never trying to refresh it. If you are interested, you can check the whole code in the [MinifiCPP](https://github.com/apache/nifi-minifi-cpp) repository under `extensions/aws` directory.

**Comment by lordgamez** [comment]
> So, yes they do expire. The problem with your approach is that there might be a clock skew in between, like the credentials could return as valid when you check but become invalid before you do the check again, or they could even not be expired locally but expired in the server.
> This can be mitigated by checking range before it expires.

After the token expires the credentials won't work anymore on any additional PutS3Object trigger, so it is more likely to be expired on the server. Could you give an example how this can be mitigated?

**Comment by KaibaLopez** [comment]
Sorry I must've been confuse when I said to do a comparison by range, that won't be easy or clean so never mind. 

So first, I think this [blog post](https://aws.amazon.com/premiumsupport/knowledge-center/security-token-expired/) goes through the expected way to handle this problem through IAM roles.
I would also recommend that you don't cache the credential... the clock skew problem is probably what's happening on your code because of it, and also, the credentials are already held by the client, plus, since you are already using the default provider, you can simply have the client set up, like:
```cpp
...
  auto client_config = config_provider.getClientConfig();
  auto request = request_builder.buildNextRequest();
  Aws::S3::S3Client s3_client(client_config); //it will by default use the default credential provider chain and renew the credentials when they are about to expire.
 ...
 ```
The SDK handles credentials on the background and checks for expiration, you shouldn't have to cache them yourself. 

Sorry about the lack of response and previous confusion.

**Comment by lordgamez** [comment]
Thanks for the information @KaibaLopez. It seems that after relying on the SDK and not caching the credentials the issue disappeared. There are use cases where we are not using the default credentials chain and the credentials provider decides what credentials should be used in the project, so I cannot use the default parameter in the `S3Client`. Still when the credentials provider chain is used skipping the credential caching solves the issue. I think this issue can be closed.
