### ISSUE TITLE
Clarification needed on CRuntime libraries building.

### ISSUE THREAD

**Issue by sakthisg** [aws/aws-sdk-cpp#1698]
Confirm by changing [ ] to [x] below:
- [X ] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [X ] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
What are you running the sdk on?
Linux Arm
**Describe the question**
We are trying to build the lambda library the below cmake commands:
=>  have created the aws-crt-cpp and other c run time  from the git code base.
=> given the following cmake command.
cmake -DENABLE_TESTING=OFF -DAUTORUN_UNIT_TESTS=OFF -DBUILD_ONLY="lambda" -DTARGET_ARCH=LINUX -DBUILD_SHARED_LIBS=ON -DDISABLE_ANDROID_STANDALONE_BUILD=ON

Observations:
1. The  C Run time libaws-c-common and  libaws-c-event-stream are generated as static libraries . Even though i have specified as BUILD_SHARED_LIBS=ON -> Why is it generating static library? 
2.  As it is static library, Does libaws-cpp-sdk-core.so  have all the required libraries linked? I dont see any error in generating libaws-cpp-sdk-core shared library generation.  How to check the libaws-cpp-sdk-core.so is correctly generated with static libraries?

**Logs/output**
If applicable, add logs or error output.

To enable logging, set the following system properties:
[CMakeCache.txt](https://github.com/aws/aws-sdk-cpp/files/6748211/CMakeCache.txt)

**Comment by KaibaLopez** [comment]
@sakthisg ,
Ok so first thing that comes to mind is... I think what's happening is that you are building the dependencies as shared libraries when building the SDK, to avoid this you'd have to add `-DBUILD_DEPS=OFF` to your cmake argument for the crt libraries to not be built.

I am pretty sure you can't have the sdk built as a shared library and the dependencies as static libraries though, so not sure how that's going to work.

**Comment by sakthisg** [comment]
@KaibaLopez  : 1. We would like to make the dependent libraries also as shared object. Hence we have given  option as DBUILD_SHARED_LIBS=ON - Why is it creating static libaries of libaws-c-common and libaws-c-event-stream? Is this a bug in the build process?
2.  When i checked the libaws-cpp-sdk-core.so for few functions like aws_common_library_init , aws_date_time_year those symbols are present in the shared object with the below commands:
$/opt/arm/gcc-linaro-6.1.1-2016.08-x86_64_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-nm -D libaws-cpp-sdk-core.so | grep -i aws_common_library_init

001a1554 T aws_common_library_init 
/opt/arm/gcc-linaro-6.1.1-2016.08-x86_64_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-readelf -a libaws-cpp-sdk-core.so | grep -i aws_date_time_year
  1546: 001a2a81    28 FUNC    GLOBAL DEFAULT   11 aws_date_time_year 
 The Shared object  libaws-cpp-sdk-core.so already containing the static libraries functions. Is my understanding correct?

**Comment by KaibaLopez** [comment]
My bad @sakthisg , I think I am still not quite following. 
So just to be on the same page, could you verify. 
The only steps you took to build the SDK was to clone it :
```
git clone --recurse-submodules https://github.com/aws/aws-sdk-cpp
```
and then run the cmake command:
```
cmake -DENABLE_TESTING=OFF -DAUTORUN_UNIT_TESTS=OFF -DBUILD_ONLY="lambda" -DTARGET_ARCH=LINUX -DBUILD_SHARED_LIBS=ON -DDISABLE_ANDROID_STANDALONE_BUILD=ON
```
and this generated both static and shared libraries ? 

And for the second question, the shared objects would have the same functions as the static ones, so... yes?

**Comment by VictorFrench** [comment]
@KaibaLopez , All the sub gits are populated by downloading the released zip files from github. There is no shared libraries generated even though we mentioned the flag **-DBUILD_SHARED_LIBS=ON** in cmake.

**Comment by KaibaLopez** [comment]
Sorry I think I was confused on this too, but if I understand it correctly:

1. Why is it generating static library? 
This is expected behavior. Currently,  the BUILD_SHARED_LIBS is not read by the c-runtime libraries... those are always built as static. 
2. As it is static library, Does libaws-cpp-sdk-core.so have all the required libraries linked? 
Yes, they are, you can look at the generated `aws-cpp-sdk-core-config.cmake` & `aws-crt-cpp-config.cmake` files for how they are finding them. But basically find_package gets the value of BUILD_SHARED for both of them and looks depending on it.

Let me know if this helps. I can try and go more in depth on it, but figured it was more of a "is it ok to assume" question so yea.

**Comment by VictorFrench** [comment]
@KaibaLopez , 
          we are using both AWS IOT CPP V2 SDK and AWS SDK CPP. AWS IOT CPP V2 SDK generated all .so from crt module. We thought of reusing it from AWS SDK CPP. Is it a bug in AWS SDK ?. If yes, is it possible to apply patch and get shared libraries from AWS SDK CPP too?.

**Comment by KaibaLopez** [comment]
It is not a bug, the AWS SDK CPP will always generate static libraries on linux for the dependencies, this is expected behavior.
 
We do recommend that if you are going to use the 2 SDKs together, you build and link the dependencies manually, that way you can verify that these mismatch on libraries types and locations don't happen. Also, there could be a version mismatch on the dependencies installed by the IoT SDK and the c++ SDK, so again, building them and linking them manually would be the safest option.
