### ISSUE TITLE
Retry Strategy Warning In SDK log file

### ISSUE THREAD

**Issue by saad-alsaad1** [aws/aws-sdk-cpp#1720]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
Centos 7/8

**Describe the question**
I always get the following warning in sdk log file:
"ClientConfiguration [139868509919552] Retry Strategy will use the default max attempts."
I'm using default configurations and enabled HTTPS and connection with S3 and get/put/delete APIs are working successfully, but I'm concern about this warning, my question is:
why I always get this warning ? and can this warning affect the connectivity with AWS S3 ?

**Comment by KaibaLopez** [comment]
Hi @saad-alsaad1 ,
So, the "warning" happens as a way to let the user know that this is something that can be configured but as a default it will retry "retry-able errors". It is done this way because it is not as visible as other configurations, and can only be configured via env variables or the config file.
> why I always get this warning ? 

As long as you use the default values yes, you can modify it to only retry a number of times.
> and can this warning affect the connectivity with AWS S3 ?

No, the log is not meant to be a warning for some risk, it is meant to be a way to communicate to the user that this is configurable.

**Comment by mohammad-aburadeh** [comment]
Hi @KaibaLopez 

Thanks a lot for the feedback. 

What exactly needs to be configured and how to configure it? 
Also, what's the recommended? 

Thanks
Mohammad

**Comment by KaibaLopez** [comment]
@mohammad-aburadeh ,
To clarify, it does not _need_ to be configured, it just can be if you for some reason want to limit the amount of retries the requests should do.

To give a bit more context: In the default retry strategy, a request that fails due to things like, slow internet or missing packages, are retried with exponentially bigger waits in between (up to a a max of about 20 seconds). Normally this is useful since those errors can happen kind of randomly, and simply rerunning usually solves this...but in some cases you might want to fail earlier and so you can limit the number of times it retries the request, this can be done by either creating your own custom retry strategy or by setting a numeric value to the environment variable: `AWS_MAX_ATTEMPTS`.

The recommendation is to use the default and ignore the log, think of it as info and not a warning.

**Comment by mohammad-aburadeh** [comment]
Thanks @KaibaLopez 
I think it's more clear now.
