### ISSUE TITLE
Transcribestreaming sample from the web is not working

### ISSUE THREAD

**Issue by trajcenikolovnick** [aws/aws-sdk-cpp#1743]
Hello,
I am trying to make work the sample from the following link:
[https://aws.amazon.com/blogs/developer/real-time-streaming-transcription-with-the-aws-c-sdk/](url)

I am getting in the console the following message:
=== Now recording!! Speak into the microphone. ===

and I have setup to use IAM credidential for aws. But I am not getting the translated string even I see I am speaking to the microphone. I have the log file if that can help

**Comment by KaibaLopez** [comment]
Hi @trajcenikolovnick ,
a couple things:
1. What version of the SDK are you using to compile your application? And what are you running it on (please follow the issue template next time, it might end up being important info). 
2. The application seems to have been built properly so I doubt the problem lies in the SDK, the logs would only be useful if you are seeing something like "slow down " warnings there which would only be that, the application being slow. If you don't see any errors like that, I would check if your application has access to the microphone, maybe it just doesn't recognize it as an input device?

**Comment by trajcenikolovnick** [comment]
Hi @KaibaLopez ,
1. The version string is 1.8.126, Windows10
2. I am seeing in the log many requests has been done without any response. By looking in the PortAudio code all the calls are done without errors. Any further hints?
Thank you so much for the support!

Nick

**Comment by trajcenikolovnick** [comment]
Hi again @KaibaLopez ,

here is from the log if this can get us some clue

20210819/eu-west-3/transcribe/aws4_request
df1c1bbd75685bd29df6118d595589e0b8edea510018c97b31a20cd8ae0823c8
2bff97dcabdc4e8af1a57d3c7f7896c513e97c8e0118d8dcca82c5154d0b21b1
a8e6b222e6087f333850a249a94aeab97c343a5eb6ba211d14f4da625d87959b
[DEBUG] 2021-08-19 14:56:35.243 AWSAuthEventStreamV4Signer [13296] Final computed signing hash: 69675e337fcd41f6d412814b7d7fce503a2adf11a9c40112112d792ab9f95df9
[INFO] 2021-08-19 14:56:35.243 AWSAuthEventStreamV4Signer [13296] Event chunk final signature - 69675e337fcd41f6d412814b7d7fce503a2adf11a9c40112112d792ab9f95df9
[WARN] 2021-08-19 14:56:35.244 WinInetSyncHttpClient [9580] Send request failed: The server name or address could not be resolved


[DEBUG] 2021-08-19 14:56:35.244 WinInetSyncHttpClient [9580] Closing http request handle 0000000000CC0010
[DEBUG] 2021-08-19 14:56:35.244 WinInetSyncHttpClient [9580] Releasing connection handle 0000000000CC000C
[DEBUG] 2021-08-19 14:56:35.244 WinInetConnectionPoolMgr [9580] Releasing connection to endpoint transcribestreaming.eu-west-3.amazonaws.com:443
[DEBUG] 2021-08-19 14:56:35.244 AWSClient [9580] Request returned error. Attempting to generate appropriate error codes from response
[ERROR] 2021-08-19 14:56:35.244 AWSClient [9580] HTTP response code: -1
Resolved remote host IP address: 
Request ID: 
Exception name: 
Error message: Encountered network error when sending http request
0 response headers

**Comment by KaibaLopez** [comment]
Hi @trajcenikolovnick ,
Thanks for pointing this out, it does seem like something is going on on windows for transcribe streaming... But it does seem like we have a bug here.

**Comment by trajcenikolovnick** [comment]
Hi @KaibaLopez,

I am new to AWS and I am wondering if my aws console is setup correctly. For access I setup IAM user with programmatic access and the Policy to full access of the Transcribestreaming. Just few ideas if this might be an issue

**Comment by KaibaLopez** [comment]
Hi @trajcenikolovnick ,
Sorry for the lack of response here, don't think the IAM user setup would be a problem here, you would get a permission error if that were the case.
But on better news it sounds like this was caused by a service side problem they had with the API which should be resolved now, though it is hard to say if this was the root cause for your specific problem, would you mind trying again and let me know if you are still seeing the issue?

**Comment by trajcenikolovnick** [comment]
Hi @KaibaLopez ,

yes, indeed there is a progress now. It is not real time though as it should be. I am talking to the mic and no realtime recognition and prints as it should be, just on exit (Ctrl+C) when I kill the app I get partial response printed out, something like this, after saying 5 times Hello for example:

=== Now recording!! Speak into the microphone. ===
[partial] Hello.
[partial] Hello.
[partial] Hello. Hello.
[partial] Hello. Hello.
[partial] Hello? Hello. Hello.
[partial] Hello? Hello. Hello.
[partial] Hello? Hello? Hello. Hello.
[partial] Hello? Hello? Hello. Hello.
[partial] Hello? Hello? Hello. Hello. Heh.
[partial] Hello? Hello? Hello? Hello. Hello.
[partial] Hello? Hello? Hello? Hello. Hello.
[partial] Hello? Hello? Hello? Hello? Hello. Hello.
[partial] Hello? Hello? Hello? Hello? Hello. Hello.

**Comment by jmklix** [comment]
Please check out our new [transcribe streaming sample](https://github.com/awsdocs/aws-doc-sdk-examples/tree/main/cpp/example_code/transcribe)
