### ISSUE TITLE
Wrong installation path option in CMake sample command in README.md

### ISSUE THREAD

**Issue by khoyee** [aws/aws-sdk-cpp#1780]
Hi,

In [README.md](https://github.com/aws/aws-sdk-cpp/blob/main/README.md), there is the following sample command:
```
cmake <path-to-root-of-this-source-code> -DCMAKE_BUILD_TYPE=Debug -DCMAKE_PREFIX_PATH=<path-to-install>
```

[CMAKE_PREFIX_PATH](https://cmake.org/cmake/help/latest/variable/CMAKE_PREFIX_PATH.html) is not used to specify installation path, I think it should be [CMAKE_INSTALL_PREFIX](https://cmake.org/cmake/help/latest/variable/CMAKE_INSTALL_PREFIX.html).

Could you please confirm and fix accordingly?

Thanks.

**Comment by KaibaLopez** [comment]
Hi @khoyee ,
So I will admit it is somewhat confusing and maybe we could just remove the extra arguments and put a more default command so maybe then it would be less confusing.....Anyways here's the explanation on why it's like that.

The idea was that the command in the instructions kind of expects that users can build on a separate folder, and because the sdk uses find_package it would need the `CMAKE_PREFIX_PATH` argument to let cmake know where to look for it.

`CMAKE_INSTALL_PREFIX` is as you say installation path, it tells cmake where to install when you run `make install`, so you can think of it as `CMAKE_PREFIX_PATH` is for the cmake command to run and `CMAKE_INSTALL_PREFIX` is a customization on make install, kind of related but different.

Anyways, let me know what you think.

**Comment by khoyee** [comment]
Hi @KaibaLopez ,

Thanks for the quick response.

Since the comment to the option says `-DCMAKE_PREFIX_PATH=<path-to-install>`, so I thought that it is meant for specifying the installation path. I specified a non-existent directory `-DCMAKE_PREFIX_PATH=/usr/local/aws-sdk-cpp` on my system but later found that `make install` still installed to `/usr/local`. So I started to look around and found the following in `CMakeCache.txt`.

```
//Install path prefix, prepended onto install directories.
CMAKE_INSTALL_PREFIX:PATH=/usr/local

//No help, variable specified on the command line.
CMAKE_PREFIX_PATH:UNINITIALIZED=/usr/local/aws-sdk-cpp
```

At least on my system, specifying `CMAKE_PREFIX_PATH` to a non-existent path did not cause any issue when building the SDK.


With above said, 
- if we want to let user know how to specify installation path, we should use `CMAKE_INSTALL_PREFIX` in the sample command.
- if it is meant for the building process to find dependencies, we should either modify the comment `<path-to-install>` to something like `<path-to-find-other-dependencies>`, or remove the option completely since users who use custom install paths should know their way after all?

What do you think?
