### ISSUE TITLE
BUILD_SHARED_LIBS=ON builds static libaws-c-event-stream.a

### ISSUE THREAD

**Issue by cemoktra** [aws/aws-sdk-cpp#1802]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**
I'm building the SDK with `BUILD_SHARED_LIBS=ON` but it seems it is not correctly passed down to CRT as i always get a static `libaws-c-event-stream.a`

**SDK version number**
1.9.129

**Platform/OS/Hardware/Device**
Debian Buster

**To Reproduce (observed behavior)**
```
git clone --recurse-submodules -branch 1.9.129 --depth 1 https://github.com/aws/aws-sdk-cpp
cmake -G Ninja -DENABLE_UNITY_BUILD=ON -DENABLE_TESTING=OFF -DBUILD_SHARED_LIBS=ON -DBUILD_ONLY="s3;sqs;sns" <path>
ninja
ninja install
```

**Expected behavior**
I would expect an `libaws-c-event-stream.so` like in older SDK versions (migrating from 1.7x currently)

**Comment by KaibaLopez** [comment]
right, this was a deliberate change made to the SDK to avoid some building issues, that being said, the dependencies can be built as shared libraries but you'd have to do it manually. 
On that note, could you give me some background on what your use case is? Maybe we can provide a workaround or revisit what the default should be.

**Comment by cemoktra** [comment]
Hi,

well we build shared libraries for SDK 1.7 and then our CMake links to `${AWSSDK_LINK_LIBRARIES}` which then fails as seems to reference shared libraries while in reality a static library is built

**Comment by KaibaLopez** [comment]
Hi @cemoktra ,
Sorry for the lack of response, kind of confused on what you mean on this last comment, sounds like you are trying to build shared libs using the old version and expecting the new version to use those, but that's not quite how that'd work, specially with such an old version. 
I guess my biggest worry here is that the last comment says the build fails, which it shouldn't it should just use the statically built dependencies so... Is the failure happening because you are trying to use the shared libs created on version 1.7 build or does the failure happens just trying to build the SDK?

**Comment by cemoktra** [comment]
Hey. No we are trying to build shared libs with the new version with our same script. But it's building parts as static library instead. But the CMake vars still make everything depend on shared libs

**Comment by KaibaLopez** [comment]
Right...
> But the CMake vars still make everything depend on shared libs

So this I can't reproduce, even when running the same command, for me the SDK builds with no problem, so I'm kind of lost... My guess is the problem might be that somehow cmake could be caching the value?

It is true and intended that the dependencies are created static even when setting `BUILD_SHARED_LIBS=ON`, but `AWSSDK_LINK_LIBRARIES` should still work...
Could you show me what logs you get exactly? Also, you mentioned "our same script" not sure if there's anything meaningful in it? Or if there is anything else you can say about how to reproduce this error?

**Comment by cemoktra** [comment]
Well the script no big magic. Just replacing the SDK version makes itt fail
```
function buildAwsSdk() {
    AWSSDKCPP_REPO_URL="https://github.com/aws/aws-sdk-cpp"
    cd /tmp
    git clone --recurse-submodules --branch ${AWSSDKCPP_VERSION} --depth 1 ${AWSSDKCPP_REPO_URL}
    cd ${BUILD_DIR}
    mkdir aws-sdk
    cd aws-sdk
    AWS_REQUIRED_COMPONENTS="s3;sqs;sns;secretsmanager" 
    cmake -G Ninja -DENABLE_UNITY_BUILD=ON -DENABLE_TESTING=OFF \
        -DBUILD_ONLY="${AWS_REQUIRED_COMPONENTS}" /tmp/aws-sdk-cpp
    ninja
    DESTDIR=${INST_DIR}/aws-sdk ninja install
    tar --create --gzip --directory ${INST_DIR}/aws-sdk --file ${PKG_DIR}/aws-sdk.tar.gz .
}
```

Then we install from this package and end up with: `libaws-c-event-stream.so.0unstable: cannot open shared object file: No such file or directory`

**Comment by KaibaLopez** [comment]
@cemoktra ,
Sorry I still can't reproduce this, I've tried different cmake, ninja, make, gcc and sdk versions and still it should just build the way that you are trying it.
I still think that there is some cache from the older version builds that cmake might be using that points it towards the shared libs instead of the static ones... I would suggest either clearing the previous installation or setting a CMAKE_INSTALL_PREFIX to a different location. and see if that works?
