### ISSUE TITLE
AWS CPP SDK InitAPI starts failing from Sep 1st

### ISSUE THREAD

**Issue by mostbestjia** [aws/aws-sdk-cpp#2102]
I have a CI on Github Actions which have been working, but starting from Sep 1st, it crashes on InitAPI, am I the only one seeing this issue? Note I have a for loop downloading S3 object, each step has InitAPI paired with ShutdownAPI, the first download is successful, the crash happens on the second InitAPI

Here's the stack:

```
 1# 0x00007F4AA535F090 in /lib/x86_64-linux-gnu/libc.so.6
 2# 0x00007F4AA5FD37D8 in /usr/local/lib/libaws-cpp-sdk-core.so
 3# 0x00007F4AA5FACB70 in /usr/local/lib/libaws-cpp-sdk-core.so
 4# s2n_config_free in /usr/local/lib/libaws-cpp-sdk-core.so
 5# 0x00007F4AA5F92B09 in /usr/local/lib/libaws-cpp-sdk-core.so
 6# Aws::Crt::Io::TlsContext::TlsContext(Aws::Crt::Io::TlsContextOptions&, Aws::Crt::Io::TlsMode, aws_allocator*) in /usr/local/lib/libaws-cpp-sdk-core.so
 7# Aws::InitAPI(Aws::SDKOptions const&) in /usr/local/lib/libaws-cpp-sdk-core.so
```

**Comment by jmklix** [comment]
Can you reply with the following information so I can better understand what is causing your problems with InitAPI?


Describe the bug
What is the problem? A clear and concise description of the bug.

Expected Behavior
What did you expect to happen?

Current Behavior
What actually happened?

Please include full errors, uncaught exceptions, stack traces, and relevant logs.
If service responses are relevant, please include wire logs.

Reproduction Steps
Provide a self-contained, concise snippet of code that can be used to reproduce the issue.
For more complex issues provide a repo with the smallest sample that reproduces the bug.

Avoid including business logic or unrelated code, it makes diagnosis more difficult.
The code sample should be an SSCCE. See http://sscce.org/ for details. In short, please provide a code sample that we can copy/paste, run and reproduce.

Possible Solution
Suggest a fix/reason for the bug

Additional Information/Context

Anything else that might be relevant for troubleshooting this bug. Providing context helps us come up with a solution that is most useful in the real world.

AWS CPP SDK version used

Compiler and Version used
gcc --version / Visual Studio / clang --version

Operating System and version

**Comment by mostbestjia** [comment]
I root caused the issue, we have two InitAPI competing, closing the issue! Thank you aws!
