### ISSUE TITLE
When the object name contains the equal sign (=), the urlencode is used for signature calculation. However, the urlencode is not used when the request is sent.

### ISSUE THREAD

**Issue by charlesgogo01** [aws/aws-sdk-cpp#2259]
### Describe the bug

When the object name contains the equal sign (=), the urlencode is used for signature calculation. However, the urlencode is not used when the request is sent.

### Expected Behavior

When the object name contains the equal sign (=), the urlencode is used for signature calculation and the urlencode is also used when the request is sent.

### Current Behavior

[DEBUG] 2022-12-21 04:25:59.513 AWSAuthV4Signer [140265152804608] Canonical Request String: HEAD
**/zjn_test/sft/p%3D5/000000_1**

amz-sdk-invocation-id:E690DC55-4B53-4C01-B634-8377C54EF7D0
..........
[TRACE] 2022-12-21 04:25:59.513 CurlHttpClient [140265152804608] Making request to **http://obs-bigdata-posix-bucket.obs.armregion.arm.com/zjn_test/sft/p=5/000000_1**

### Reproduction Steps

null

### AWS CPP SDK version used

 aws-sdk-cpp/1.9.179

### Compiler and Version used

 GCC/10.3.0

### Operating System and version

 Linux/3.10.0-514.el7.x86_64

**Comment by jmklix** [comment]
Can you include a code snippet that reproduces this?

**Comment by zh-jn** [comment]
A headObject request can reproduce:
`Aws::S3::Model::HeadObjectOutcome outcome = s3client -> HeadObject(request);`.

Enable the trace log will show that the objKey is urlencoded in sign, but in http request it not.

**Comment by yasminetalby** [comment]
Hello @zh-jn ,

Thank you very much for your submission.

I sincerely apologize for the delay of answer.
I have attempted to reproduce the behavior you have described in the issue submission following your reproduction steps and I am able to observe the behavior described in the latest AWS SDK. However this does not cause any issue or limitation. Are you encountering any limitation due to this behavior?

I would also recommend you to take a look at the AWS S3 Developer Guide documentation regarding [Creating object key name](https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-keys.html). As you can see there Equals ("=") character fall under the section of "Characters that might require special handling".

Let me know if there is a specific limitation or use case you are encountering that we could help with.

Best,

Yasmine
