### ISSUE TITLE
Clicking on AWS C++ documentation links forces download

### ISSUE THREAD

**Issue by bipinmathew** [aws/aws-sdk-cpp#2307]
### Describe the issue

Click on any C++ documentation and instead of opening in the browser the HTML page is downloaded to disk.  I have tried this on chrome, and firefox both desktop and mobile and we get the same behavior. Here an example:

[https://sdk.amazonaws.com/cpp/api/0.12.9/d4/d27/class_aws_1_1_auth_1_1_a_w_s_credentials.html](url)

### Links

https://sdk.amazonaws.com/cpp/api/0.12.9/d4/d27/class_aws_1_1_auth_1_1_a_w_s_credentials.html

**Comment by jmklix** [comment]
Where are you finding these links? I'm not finding any links that are forcing downloads on the [API docs](https://sdk.amazonaws.com/cpp/api/LATEST/root/html/index.html)

**Comment by bipinmathew** [comment]
In "incognito mode" (for example) if I google "Aws::Auth::AWSCredentials"
and click on the first link I get this issue.

The first link is:

https://sdk.amazonaws.com/cpp/api/0.12.9/d4/d27/class_aws_1_1_auth_1_1_a_w_s_credentials.html

**Comment by jmklix** [comment]
This might be because we recently changed the folder structure in release 1.11 that caused this path to no longer exist. Google might have cached it and now the only option is to download the file. We can't change what results Google is returning, but you can report the result as outdated.

I believe this is the updated link that you are looking for:
https://sdk.amazonaws.com/cpp/api/LATEST/aws-cpp-sdk-core/html/class_aws_1_1_auth_1_1_a_w_s_credentials.html
