### ISSUE TITLE
Temp directory during build / unittests

### ISSUE THREAD

**Issue by asylvest** [aws/aws-sdk-cpp#232]
When building the SDK on Linux, it creates a /tmp/.aws directory (I assume the equivalent happens on Windows as well)... I'm guessing this is happening when the unittests are run and is used as a dumping ground to put some temporary credentials in.  The problem is that this directory is left hanging after the build, so if another user on the system goes to build the SDK later, they get a failure related to not having permissions to this directory.  Even if we took care to change our umask across the board, you could end up with possible collisions if multiple users happened to be building at the same time.

I would suggest changing this to create a unique directory in /tmp each time, using a UUID or equivalent.  Or at a minimum, name the directory based on the username, though you could still get unlucky with collisions there too depending on user behavior.

**Comment by bretambrose** [comment]
I've added an issue into our backlog to take a look at this.  There are a number of places where non-transactional execution can leave junk lying around.

**Comment by singku** [comment]
@asylvest Environment variable HOME is purposely set to "/tmp" on unix system or "/var/tmp" on osx when doing unit test at building stage, mostly because of android system. Windows will not be affected. Also .aws is the default dir to fetch credentials, randomized name is not appropriate.  Credentials inside this dir will be renamed and restored before and after unit-test, so multiple users run on same system is not a problem. The problem is that this dir is created with 0755 permission mode, others has no right to write file in it. We have pushed out a fix on this and will merge shortly.
