### ISSUE TITLE
"unresolved external symbol" When linking to the library

### ISSUE THREAD

**Issue by TyrasNistru** [aws/aws-sdk-cpp#2421]
### Describe the bug

I'm trying to build a simple test program that downloads a file from a S3 bucket. I've already done that a couple of times with older versions of the SDK, but with the current version, It doesn't seems to work since I can't link properly with the library:

In older versions, I only had to link to three libraries: aws-cpp-sdk, aws-cpp-sdk-s3 and aws-cpp-sdk-transfer.

Now, even linking with all libraries generated by the build, it still complains about an unresolved external symbol.

### Expected Behavior

To link and work properly

### Current Behavior

It does not link, complaining about the following unresolved external symbol:

error LNK2001: unresolved external symbol "public: static unsigned __int64 const Aws::Endpoint::AWSPartitions::PartitionsBlobSize" (?PartitionsBlobSize@AWSPartitions@Endpoint@Aws@@2_KB)

### Reproduction Steps

- Build the sdk on Windows, using MS Visual Studio 2019, default settings except for the `BUILD_ONLY`, setting it to `core;s3;transfer`
- Try to link a simple code, just trying to declare a `std::shared_ptr<Aws::S3::S3Client>` variable
- Try to build, linking all the libraries generated by the SDK build (`aws-cpp-sdk-transfer`, `aws-cpp-sdk-s3`, `aws-cpp-sdk-core`, `aws-c-auth`, `aws-c-cal`, `aws-c-common`, `aws-c-compression`, `aws-c-event-stream`, `aws-checksums`, `aws-c-http`, `aws-c-io`, `aws-c-mqtt`, `aws-crt-cpp`, `aws-c-s3`, `aws-c-sdkutils`)

### AWS CPP SDK version used

1.11.48

### Compiler and Version used

Visual Studio 2019 (MSVC 19.29.30147.0)

### Operating System and version

Windows 11 Pro 22H2 build 22621.1413

**Comment by RobertvandeVelde** [comment]
I'm having exactly the same issue on Windows 10 and Visual Studio 2022. I built and installed the 'master' branch instead of the 'main' branch and that one compiles without linker errors.

**Comment by jmklix** [comment]
What are the build commands that you are using?

**Comment by RobertvandeVelde** [comment]
1. git cmd: git clone --recurse-submodules https://github.com/aws/aws-sdk-cpp

2. cmake gui 3.26: configure and generate (both with default options)

3. windows cmd: "C:\Program Files\Microsoft Visual Studio\2022\Community\Msbuild\Current\Bin\MSBuild.exe" "C:\...\aws-sdk-cpp\build\ALL_BUILD.vcxproj" -p:Configuration=Release

4. windows cmd: "C:\Program Files\Microsoft Visual Studio\2022\Community\Msbuild\Current\Bin\MSBuild.exe" "C:\...\aws-sdk-cpp\build\INSTALL.vcxproj" -p:Configuration=Release

5. Visual Studio project properties->linker->input:
ws-cpp-sdk-core.lib; aws-cpp-sdk-s3.lib; aws-c-auth.lib; aws-c-cal.lib; aws-c-common.lib; aws-c-compression.lib; aws-c-event-stream.lib; aws; checksums.lib; aws-c-http.lib; aws-c-io.lib; aws-c-mqtt.lib; aws-crt-cpp.lib; aws-c-s3.lib; aws-c-sdkutils.lib

6. C:\...\my_project_directory\includes\aws\ contains the following maps (copied from the SDK):
auth; cal; checksums; common; compression; core; crt; event-stream; http; io; mqtt; s3; sdkutils

7. source file includes:
#include <aws/core/Aws.h>
#include <aws/s3/S3Client.h>

As said above, I did the same steps for the 'master' branch (--branch master) and that one did not have the linker error so that it compiled properly.

**Comment by SergeyRyabinin** [comment]
Hi @RobertvandeVelde ,

It is quite strange that you encounter only following linker error.
> error LNK2001: unresolved external symbol "public: static unsigned __int64 const Aws::Endpoint::AWSPartitions::PartitionsBlobSize" (?PartitionsBlobSize@AWSPartitions@Endpoint@Aws@@2_KB)

I would expect much more similar linker errors because this is not a unique variable following this C++ static const variable pattern.
Could you please make sure that the whole SDK is rebuilt from a fresh/clean git repo, and installed into the destination location.

Also, could you please specify cmake configuration you have for the SDK build and the SDK consuming app? What C++ version (11/14/17/20) are using?

> C:...\my_project_directory\includes\aws\ contains the following maps (copied from the SDK):

This part is not very clear, could you please elaborate a bit? Are you saying that this dir contains SDK and CRT headers or you are talking about property "additional include dirs" setting in a VS vcxproj config?

Best regards,
Sergey

**Comment by RobertvandeVelde** [comment]
Thanks for your reply! I will remove the current installation and then redownload, build and install the main branch, although it might take some hours. I'm using C++14 (default option). For cmake, I open cmake gui (version 3.26.2), set the source and binary directories and then press configure and generate, all with default options. After building and installing with MSBuild, I copy only the libs and headers that I currently need (for a S3 client) from the installation directory to my project directory. I took the headers from C:\Program Files (x86)\aws-cpp-sdk-all\include\aws and the libs from C:\Program Files (x86)\aws-cpp-sdk-all\bin and C:\Program Files (x86)\aws-cpp-sdk-all\lib.

**Comment by jmklix** [comment]
Can you also try building the sdk statically with the follow cmake arguments: `-DFORCE_SHARED_CRT=OFF -DBUILD_SHARED_LIBS=OFF`

**Comment by RobertvandeVelde** [comment]
I will try it this weekend, I'm busy with other things currently. I'll let you know.

**Comment by RobertvandeVelde** [comment]
Turning both options off leads to errors during build for both main and master source versions. If I only turn off BUILD_SHARED_LIBS I can build the SDK, but when I use it in my project I get 103 unresolved externals for the main source. If I use master then my project builds without errors.

**Comment by D3troit98** [comment]
The issue still remains. I am also experiencing the same issue.

**Comment by code-disaster** [comment]
I ran into the same issue. Built from source as shared libraries, `BUILD_ONLY="s3"`, `cmake --install` into custom folder.

Then tried to compile "Hello S3" in my CMake project, but added the libraries manually, so not using `AWSSDKConfig.cmake`. This doesn't define `USE_IMPORT_EXPORT`, leading to link errors because of the now wrong `AWS_XY_API` declarations.

The simple fix is to define USE_IMPORT_EXPORT before including any SDK headers.

**Comment by Lovecookie** [comment]
@code-disaster This way saved my life. Thanks a lot!

**Comment by jmklix** [comment]
What does your CMakeLists.txt look like?

Can you make sure that you have `find_package` added with all of the aws services that you are using added to it?
It should look something like this:
```cmake
find_package(AWSSDK REQUIRED COMPONENTS s3 lambda transfer)
```

**Comment by RoyZhang2022** [comment]
The issue exists for 1.11.21. The solution is to define USE_IMPORT_EXPORT before including any SDK headers.
