### ISSUE TITLE
What's the suggested client usage pattern for online S3 range query?

### ISSUE THREAD

**Issue by newpoo** [aws/aws-sdk-cpp#267]
Basically we need to do online S3 range query from our C++ services. Since this is an online service, we will need to tune our client usage code to reduce S3 query latency as much as possible.

With our quick benchmark code (create a global S3Client, and share it with 8 worker threads, and each worker thread query S3 syncrhonously), we can achieve 90ms P90 latency for 400KB range. Not sure if this performance is reasoanble or not. Anything else we could tune to achieve better performance? BTW: the experiments ran on 3 i2.2x instances, and the incoming network bandwidth consumption for each instance is about 70MB/s.

Thanks!

**Comment by JonathanHenson** [comment]
What sort of bandwidth are you looking for? Are you CPU bound, memory bound, or network bound? Do you know where your bottleneck is?

**Comment by newpoo** [comment]
Actually we are looking for the best possible S3 range get latency. CPU, memory or bandwidth are unlikely to be the bottleneck of our system.

**Comment by JonathanHenson** [comment]
If you are wanting to do get-range in parallel on the same object, I would advise against it, since you will likely cause disk thrash on S3's back end. If you are downloading multiple objects, I would advise that you do range gets on separate objects in parallel instead of on the same object.

S3 has a Download Part API somewhere, but it hasn't trickled out to the SDKs, I'll go investigate that.

**Comment by JonathanHenson** [comment]
Closing issue. Feel free to reopen if you have more questions.
