### ISSUE TITLE
Error Init hash

### ISSUE THREAD

**Issue by atharvapaladin** [aws/aws-sdk-cpp#2722]
### Describe the bug

While initializing AWS API in C++ code I get this error
"s2n_init() failed: 335544335 (error initializing hash)
Fatal error condition occurred in /home/ubuntu/aws-sdk-cpp/crt/aws-crt-cpp/crt/aws-c-io/source/s2n/s2n_tls_channel_handler.c:203: 0 && "s2n_init() failed"
Exiting Application
################################################################################
Stack trace:
################################################################################
"

### Expected Behavior

Initialize AWS API and start S3 bucket upload

### Current Behavior

<img width="980" alt="git" src="https://github.com/aws/aws-sdk-cpp/assets/143420952/7712e54b-6e9f-40ce-af05-c61abf9d79dc">

### Reproduction Steps

Initailize AWSAPI for uploading to S3 bucket

### AWS CPP SDK version used

1.11

### Compiler and Version used

gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0

### Operating System and version

Ubuntu 20.04

**Comment by atharvapaladin** [comment]
@kha-

**Comment by atharvapaladin** [comment]
@khapaladin

**Comment by atharvapaladin** [comment]
@yasminetalby

**Comment by jmklix** [comment]
How are you trying to initialize this sdk? You need to make sure that you are making sdk calls within brackets `{}`:
```cpp
    Aws::SDKOptions options;
    Aws::InitAPI(options);
    {
        //sdk calls here
    }
    Aws::ShutdownAPI(options);
```

You can also find a complete example for how to use put_object [here](https://github.com/awsdocs/aws-doc-sdk-examples/blob/main/cpp/example_code/s3/put_object.cpp).

If that doesn't help you please provide a minimal code sample that reproduces the error you are seeing.

**Comment by khapaladin** [comment]
Trying a few things on my end based on your response. Thank you. I'll make sure to get back to you soon if this works for us. This is all we do during init, and it gives the error. Error is stemming from this call Aws::InitAPI(options);

![image](https://github.com/aws/aws-sdk-cpp/assets/111612958/65835a13-b5cc-4a7d-8220-68159e5e9ed9)
![image](https://github.com/aws/aws-sdk-cpp/assets/111612958/5c10e580-f5b0-447e-b6e0-dc3ae10679d1)

**Comment by SergeyRyabinin** [comment]
Hi @atharvapaladin ,

It is quite complicated for us to triage this issue.

Could you please provide full reproduction steps, including:
* OS (provided) and any particular config/customization on the OS running;
* Host type (cpu type / arch);
* SDK version used and how you have built it (cmake configure and cmake build/install commands used);

Another option would be to simply ask you to debug step by step the [s2n_init function](https://github.com/aws/s2n-tls/blob/dec039dc654335b066d3ff83db960e695dd33b21/utils/s2n_init.c#L51-L95)... The function is not that long and frankly speaking it would be much easier to get to the root cause.

Best regards,
Sergey

**Comment by khapaladin** [comment]
Will try the option where we'll debug the s2n_init function. Thanks for the tip. Will post what we find soon.
