### ISSUE TITLE
Cloudfront with S3

### ISSUE THREAD

**Issue by TechBeings** [aws/aws-sdk-cpp#283]
I have created an application that downloads from the S3 client .
I would now like to make the application download from cloudfront but as far as I can tell cloudfront does not contain methods to help me do this e.g. specify the range or receive the download progress updates.
Does anyone have a clue how one would go about doing this, I was hopping that I would still have to keep my S3 code because it works just need to tell it to download from cloudfront.

**Comment by bretambrose** [comment]
Hello,

The cloudfront API is primarily a config/control-plane API rather than a data plane one.  Once configured, you would use regular http requests to pull your data rather than an S3 client.  In theory you could probably use the http client we provide in core for these requests, but there may be some tweaks needed in order to make the requests just right.

**Comment by TechBeings** [comment]
Ok thanks for the reply .Looks like I have a lot of work to do, to get my application working the same way as it is while downloading from s3 directly.
I have some other projects so this will have to wait for now, but I will definitely work on it in the future.
