### ISSUE TITLE
including aws headers in #pragma push()/pop() blocks throws C4251 on MSVC

### ISSUE THREAD

**Issue by zippererer** [aws/aws-sdk-cpp#293]
We've wrapped some headers in pragma push()/pop() to temporarily disable warnings due to invalid characters in some of the aws headers.  We found this by compiling on a machine using simplified Chinese as the default code page.  We used the push()/pop() method to limit the scope of when these warnings were disabled to prevent masking issues in our own code.  We have found that this can cause C4251 to be thrown on MSVC if we try to include aws headers in 2 different locations.  An example below:

.h file:
# pragma warning(push)
# pragma warning(disable:4819)  // Invalid character not in default code page
# include <aws/core/Aws.h>

...
# pragma warning(pop)

.cpp file:
# include <aws/core/utils/threading/Executor.h>

Diving deeper on this, we found that Core_EXPORTS.h uses #pragma warning(disable:4251) in a file that also has #pragma once.  This prevents the warning from being disabled when a second file that subsequently includes Core_EXPORTS.h a second time.

**Comment by bretambrose** [comment]
When did you last sync the SDK?  The invalid characters issue was fixed (as far as we know) a month or so ago.

**Comment by bretambrose** [comment]
That being said, we can move the disable to a /w4251 definition inside cmakelists.txt

**Comment by singku** [comment]
@bretambrose @JonathanHenson @zippererer 
I think this is more of a logical problem when using this SDK. It's not a bug. Your use case is to preserve settings first by pragma push, then import settings from SDK, then restore your original settings by pragma pop, so settings from SDK are ineffective. Now you include the AWS's header the second time, but pragma warning(disable 4251) is not taking into effect because of #pragma once. The solution I think is either we extract this warning from pragma once or you can add it in your own code

**Comment by singku** [comment]
Please reopen if you have any other questions

**Comment by zippererer** [comment]
ok.  btw I work at Amazon on Lumberyard, I had to add these pragma scopes around all the location we called into your sdk when I enabled warnings as errors on the Lumberyard codebase.  Changing compiler warnings without internal scope exposed our code to all of these errors, which we did not want to do.  I thought it was ugly and dangerous, and that you may want to address it.
