### ISSUE TITLE
Wrong file size of unicode file name, real-time progress in case multiupload

### ISSUE THREAD

**Issue by bvhoang91** [aws/aws-sdk-cpp#303]
Hi,

In my MFC project, type of file path variable is CSTring. I create request handle like this:

```
auto requestPtr = transferManager.UploadFile(ConvertCStringToSting(filePath).c_str(), bucketName, key,
                                                 contentType, Aws::Map<Aws::String, Aws::String>());
```

Or

```
auto fileStream = Aws::MakeShared<Aws::FStream>(ALLOCATION_TAG, ConvertCStringToString(filePath).c_str(), std::ios_base::in | std::ios_base::binary);
auto requestPtr = transferManager.UploadFile(fileStream, bucketName, key, contentType, Aws::Map<Aws::String, Aws::String>());
```

But, when filePath is unicode name, it detect wrong file size. So, I try implement upload func by convert filepath to wstring:

```
auto fileStream = Aws::MakeShared<Aws::FStream>(ALLOCATION_TAG, ConvertCStringToWString(filePath).c_str(), std::ios_base::in | std::ios_base::binary);
auto requestPtr = transferManager.UploadFile(fileStream, bucketName, key, contentType, Aws::Map<Aws::String, Aws::String>());
```

It work.

So, Is it bug in the first two examples? How can I impliment upload func by the right way?

The second question:
I upload 20MB file, it take a long time to update progress from 0->25%, take a little time update from 25 ->100%. Is there any way to build real-time progress bars?

Thanks.

**Comment by bretambrose** [comment]
For the file size issue, are you able to step into the execution in a detailed manner to determine where the incorrect size is calculated?

We've had a number of requests for a more accurate progress update on multi-part uploads so we'll look into it further.  We'd like to avoid locking on callbacks and we'd like to avoid backwards progress when a part fails (better to stall the progress imo).  Satisfying both of these desires at the same time is potentially tricky.

**Comment by bvhoang91** [comment]
```
fileStream->seekg(0, std::ios_base::end);
 size_t length = static_cast<size_t>(fileStream->tellg());
```
Incorrect size is calculated in UploadFile func.
If I initialize filestream by wtring filepath (ex 3 in first cmt). It is calculated correct size.

**Comment by bretambrose** [comment]
There's two parts to this issue.  The size calculation was wrong in this case because the stream was invalid.  Yesterday's update fixed this and returns an upload error when the stream is not good.  

The other issue, as you've helpfully discovered, is that on Windows, filenames/paths with unusual characters do not create valid fstreams if you pass the name as a std::string/Aws::String.  Instead, you need to convert to std::wstring, switching to another std::fstream constructor.  

The short term workaround is to just use the stream interface on TransferClient, with the responsibility for getting the stream set up correctly on the user.  For a real solution, unless anyone can think of an objection, we may (on Windows only) just convert every path to a wide string and use its fstream constructor.  The cost to do this conversion is vanishingly trivial compared to everything else involved in an upload operation.

I believe this issue and #328 are essentially the same thing (the size on an invalid stream was -1 which led to an attempt to upload 4g or more of "nothing").

**Comment by singku** [comment]
@bretambrose Have you decided how to solve this problem?
