### ISSUE TITLE
Documentation missing to build for iOS.

### ISSUE THREAD

**Issue by antoinelefebvre** [aws/aws-sdk-cpp#340]
The documentation do not specify how to build for iOS. I was able to build for Windows, Mac OSX, and Android but so far, my attempts at building for iOS failed.

Anyone knows the proper cmake flags?

**Comment by JonathanHenson** [comment]
I have them, I'm in the process of simplifying the whole thing by ditching libcurl (but I haven't finished it yet).

**Comment by antoinelefebvre** [comment]
While you finalize the simplified process, would you be able to give instructions on building with the current process?

**Comment by antoinelefebvre** [comment]
I am planning to try again building for iOS in the upcoming days. Any progress on this front? Thanks,

**Comment by JonathanHenson** [comment]
Sorry for the delay. 

You'll want these:

http://sdk.amazonaws.com/cpp/builds/?prefix=cpp/builds/apple_mobile_libcurl/

Then a script like this should do the trick:

#!/bin/bash

mkdir iphone_build_output
mkdir build
cd build
echo $CMAKE_CXX_FLAGS
rm -r ./*
/Applications/CMake.app/Contents/bin/cmake -DCMAKE_OSX_SYSROOT="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.0.sdk" -DCMAKE_OSX_ARCHITECTURES="arm64" -DCMAKE_SYSTEM_NAME="Darwin" -DCMAKE_SHARED_LINKER_FLAGS="-framework Foundation -lz -framework Security" -DCMAKE_EXE_LINKER_FLAGS="-framework Foundation -framework Security" -DCMAKE_PREFIX_PATH="$WORKSPACE/libcurl_iphone_arm64_static/libcurl_iphone_arm64_static/" -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE="Release" -DCMAKE_INSTALL_PREFIX="$WORKSPACE/iphone_build_output" -DCMAKE_CXX_FLAGS="-std=c++11 -stdlib=libc++ -miphoneos-version-min=8.3" ../aws-sdk-cpp
make -j 8
make install

**Comment by antoinelefebvre** [comment]
Thanks. Its working.

I made static libraries with -DBUILD_SHARED_LIBS=OFF. I also used iPhoneOS10.1.sdk and changed the iphoneos-version-min to 6.0 (tried 5.1 but that but that gives an error library not found for -lcrt1.3.1.o). I also set CMAKE_OSX_ARCHITECTURES to "armv7;arm64" to create have multiple architectures.

This will be integrated in a Qt 5 application so we will write our custom http client based on the Qt Network library. I won't need lib curl so I configure with -DNO_HTTP_CLIENT=ON.

**Comment by JonathanHenson** [comment]
Out of curiosity, what are you using for http?

**Comment by antoinelefebvre** [comment]
I am using QNetworkAccessManager (http://doc.qt.io/qt-5/qnetworkaccessmanager.html), see also http://doc.qt.io/qt-5/qtnetwork-programming.html. This is working well for us on all the platforms we are supporting.

**Comment by JonathanHenson** [comment]
Would you care to make a pull request with your QT builds? I'd love to offer this to more customers.

**Comment by antoinelefebvre** [comment]
We are not ready to share our work at this point. This is still a work in progress. Thanks for the interest.

**Comment by tttthiagoooo** [comment]
Hi Jonathan Henson,
I'm trying to build for iOS too. I follow your tips and CMake was generated correctly, but during the building, the process stops because 'curl/curl.h' file was not found.

On Windows and MacOS I had no problems.


**STEPS**
cd /Users/thiagoguimaraes/Documents/Dev/iOS
cmake -DCMAKE_BUILD_TYPE=Release -BUILD_SHARED_LIBS=OFF -FORCE_SHARED_CRT=OFF -DBUILD_ONLY="access-management;cognito-identity;cognito-idp;cognito-sync;s3;s3-encryption;transfer" -DCMAKE_OSX_SYSROOT="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.1.sdk" -DCMAKE_OSX_ARCHITECTURES="arm64" -DCMAKE_SYSTEM_NAME="Darwin" -DCMAKE_SHARED_LINKER_FLAGS="-framework Foundation -lz -framework Security" -DCMAKE_EXE_LINKER_FLAGS="-framework Foundation -framework Security" -DCMAKE_PREFIX_PATH="/Users/thiagoguimaraes/Documents/Dev/libcurl_iphone_arm64_static/libcurl_iphone_arm64_static/" -DCMAKE_INSTALL_PREFIX="/Users/thiagoguimaraes/Documents/Dev/iOSInstall" -DCMAKE_CXX_FLAGS="-std=c++11 -stdlib=libc++ -miphoneos-version-min=8.3" /Users/thiagoguimaraes/Documents/Dev/aws-sdk-cpp-master
make -j 8

**ERROR MESSAGE**

[  6%] ...
In file included from /Users/thiagoguimaraes/Documents/Dev/aws-sdk-cpp-master/aws-cpp-sdk-core/source/http/curl/CurlHandleContainer.cpp:16:
/Users/thiagoguimaraes/Documents/Dev/aws-sdk-cpp-master/aws-cpp-sdk-core/include/aws/core/http/curl/CurlHandleContainer.h:21:10: fatal error: 'curl/curl.h' file not
      found
#include <curl/curl.h>
         ^
In file included from /Users/thiagoguimaraes/Documents/Dev/aws-sdk-cpp-master/aws-cpp-sdk-core/source/http/curl/CurlHttpClient.cpp:16:
In file included from /Users/thiagoguimaraes/Documents/Dev/aws-sdk-cpp-master/aws-cpp-sdk-core/include/aws/core/http/curl/CurlHttpClient.h:21:
/Users/thiagoguimaraes/Documents/Dev/aws-sdk-cpp-master/aws-cpp-sdk-core/include/aws/core/http/curl/CurlHandleContainer.h:21:10: fatal error: 'curl/curl.h' file not
      found
#include <curl/curl.h>
         ^
[  6%] Building CXX object aws-cpp-sdk-core/CMakeFiles/aws-cpp-sdk-core.dir/source/utils/Array.cpp.o
1 error generated.
make[2]: *** [aws-cpp-sdk-core/CMakeFiles/aws-cpp-sdk-core.dir/source/http/curl/CurlHandleContainer.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
1 error generated.
make[2]: *** [aws-cpp-sdk-core/CMakeFiles/aws-cpp-sdk-core.dir/source/http/curl/CurlHttpClient.cpp.o] Error 1
make[1]: *** [aws-cpp-sdk-core/CMakeFiles/aws-cpp-sdk-core.dir/all] Error 2


Please, can you give me any tips?

**Comment by tttthiagoooo** [comment]
Hi Jonathan,

I'm trying to build the AWS-SDK-CPP to iOS, and I have successfully with arm64, using the library you provided, but I found some problems with libcurl for another architectures armv7, armv7s and i386. I've spent a lot of time trying to build the curl. My question is, can you make libcurl available to other architectures? Anyway, see below what I've tried.

My steps;

To build the cURL I followed these steps; 
https://github.com/jasonacox/Build-OpenSSL-cURL

To build AWS I followed thes steps, that works fine with your libcurl using arm64;

cd /Users/thiagoguimaraes/Documents/Dev/iOS
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="/Users/thiagoguimaraes/Documents/Dev/iOSInstall/armv7s-apple-darwin_ios" -DBUILD_SHARED_LIBS=OFF -DFORCE_SHARED_CRT=OFF  -DBUILD_ONLY="sns;sqs;ssm" -DCMAKE_OSX_SYSROOT="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.1.sdk" -DCMAKE_OSX_ARCHITECTURES="armv7s" -DCMAKE_SYSTEM_NAME="Darwin" -DCMAKE_SHARED_LINKER_FLAGS="-framework Foundation -lz -framework Security" -DCMAKE_EXE_LINKER_FLAGS="-framework Foundation -framework Security" -DCMAKE_PREFIX_PATH="/Users/thiagoguimaraes/Documents/Dev/cURL_OpenSSL/Libs" -DCMAKE_CXX_FLAGS="-std=c++11 -stdlib=libc++ -miphoneos-version-min=8.3" /Users/thiagoguimaraes/Documents/Dev/aws-sdk-cpp-master
make -j 8

These three project "sns;sqs;ssm", or one off these, cause a problem while linking. Before I was trying to compile the whole project, and I always made a mistake with one of these projects.

[ 32%] Linking CXX executable aws-cpp-sdk-core-tests
[ 32%] Building CXX object aws-cpp-sdk-cognito-identity/CMakeFiles/aws-cpp-sdk-cognito-identity.dir/source/model/SetIdentityPoolRolesRequest.cpp.o
Undefined symbols for architecture armv7s:
...
...
  "_zlibVersion", referenced from:
      _Curl_version_init in libcurl.a(libcurl_la-version.o)
      _curl_version in libcurl.a(libcurl_la-version.o)
      _curl_version_info in libcurl.a(libcurl_la-version.o)
      _Curl_unencode_gzip_write in libcurl.a(libcurl_la-content_encoding.o)
ld: symbol(s) not found for architecture armv7s
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [aws-cpp-sdk-core-tests/aws-cpp-sdk-core-tests] Error 1
make[1]: *** [aws-cpp-sdk-core-tests/CMakeFiles/aws-cpp-sdk-core-tests.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by tttthiagoooo** [comment]
Hi @JonathanHenson 
Building libcurl using this sh https://raw.githubusercontent.com/sinofool/build-libcurl-ios/master/build_libcurl_dist.sh, adapting this with IPHONEOS_DEPLOYMENT_TARGET="8.3", I had the following errors while building AWS libs. With libcurl built following https://github.com/jasonacox/Build-OpenSSL-cURL, I was getting more error messages.

...
Scanning dependencies of target aws-cpp-sdk-core-tests
[ 10%] Building CXX object aws-cpp-sdk-core-tests/CMakeFiles/aws-cpp-sdk-core-tests.dir/RunTests.cpp.o
...
[ 33%] Linking CXX executable aws-cpp-sdk-core-tests
Undefined symbols for architecture armv7s:
  "_inflate", referenced from:
      _inflate_stream in libcurl.a(libcurl_la-content_encoding.o)
  "_inflateEnd", referenced from:
      _inflate_stream in libcurl.a(libcurl_la-content_encoding.o)
      _Curl_unencode_gzip_write in libcurl.a(libcurl_la-content_encoding.o)
      _Curl_unencode_cleanup in libcurl.a(libcurl_la-content_encoding.o)
  "_inflateInit2_", referenced from:
      _inflate_stream in libcurl.a(libcurl_la-content_encoding.o)
      _Curl_unencode_gzip_write in libcurl.a(libcurl_la-content_encoding.o)
  "_inflateInit_", referenced from:
      _Curl_unencode_deflate_write in libcurl.a(libcurl_la-content_encoding.o)
  "_zlibVersion", referenced from:
      _curl_version in libcurl.a(libcurl_la-version.o)
      _curl_version_info in libcurl.a(libcurl_la-version.o)
      _Curl_unencode_gzip_write in libcurl.a(libcurl_la-content_encoding.o)
ld: symbol(s) not found for architecture armv7s
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [aws-cpp-sdk-core-tests/aws-cpp-sdk-core-tests] Error 1
make[1]: *** [aws-cpp-sdk-core-tests/CMakeFiles/aws-cpp-sdk-core-tests.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 33%] Building CXX object aws-cpp-sdk-cognito-identity/CMakeFiles/aws-cpp-sdk-cognito-identity.dir/source/model/MergeDeveloperIdentitiesResult.cpp.o
...
[ 98%] Linking CXX static library libaws-cpp-sdk-ssm.a
[ 98%] Built target aws-cpp-sdk-ssm
make: *** [all] Error 2

**Comment by JonathanHenson** [comment]
im looking in to this right now, I'll respond as soon as possible.

**Comment by JonathanHenson** [comment]
Are you using darwin ssl? You should, OpenSSL has been deprecated on Apple platforms for several releases now. The SDK will not link with it if you don't use CommonCrypto

**Comment by JonathanHenson** [comment]
You also need to disable gzip.

**Comment by tttthiagoooo** [comment]
Hi  @JonathanHenson,

I had been with OpenSSL, but in the last tests I was not using it. But I had not disabled ZLIB for building cURL.

Now I have been able to build as expected the 3 libs, I will leave building the whole sdk.

Thank you very much!

**Comment by dschmitt006** [comment]
It would be nice to have an option to build/use zlib/openssl/libcurl across all platforms from a process standpoint.  (If I support x platforms, I'm much more confident that if I build/update/test my library for one platform, I've fixed it and/or will see similar behavior for all of them.)
