### ISSUE TITLE
Close socket connection after curl handle is released to handle pool

### ISSUE THREAD

**Issue by mikewang2016** [aws/aws-sdk-cpp#393]
My application is multithreading application and upload/download many files at the same time. After it goes into idle state, I can see it still keep many socket connections at "CLOSE_WAIT".

Look at the SDK source code, it's clear that SDK will only call curl_easy_cleanup during its shutdown.

I suggest SDK should call curl_easy_cleanup once a curl handle is going to be returned to pool.

**Comment by bretambrose** [comment]
Cleaning up curl handles after every use would substantially degrade the SDK's throughput when hitting the same endpoint, since every request would be made from scratch with no TLS caching.  If you want, you can certainly reduce/limit the size of the connection pool to keep the number of sockets used to be as small as you'd like (see ClientConfiguration::maxConnections).

**Comment by mikewang2016** [comment]
I understand the intention that SDK keeps a pool of curl handles. However, from technical point of view, a long time "CLOSE_WAIT" socket sometimes is explained as a programming error. From end user's point of view, a system administrator may ask why your application keep so many sockets in "CLOSE_WAIT" state.

Reducing max connection is not an option as my application is a multithreading application and can be very busy sometimes (not always).

On the other hand, I am curious about if there is other way to reduce the performance impact if we close socket every time. I have no much experience with libcurl. But I guess you can implement a usage monitor logic: allocate (and keep) more handles when busy, release (and close) handle when idle.

You mentioned DNS caching. But I guess if that really takes effect. AWS S3 service seems to be a DNS load balance system. We will get different IP address for every time we try to resolve the DNS name. Testing result also shows that the SDK use many different IP address.

**Comment by JonathanHenson** [comment]
A TLS connection is three round trips to the server just to setup a socket. This would be a heavy penalty to pay for the application. Just about every http application maintains a connection pool under the hood. I don't see why this is a problem.

**Comment by JonathanHenson** [comment]
and the sockets should only be staying open as long as the keep alive from the server specifies which is in keeping with the spec.

**Comment by earnestzhao** [comment]
Many CLOSE_WAIT connections hanging is a bug, which it is a base knowledge, very clear. It is because client doesn't execute close when read return code is 0. See the answers below, we cannot see any investigations, but perfunctoriness. This is the consistent attitude when Amazon/AWS employees face to problems/questions/bugs. I get use to it.
