### ISSUE TITLE
How can I use aws c++ SDK in qt project using qt creator?

### ISSUE THREAD

**Issue by gkhanacer** [aws/aws-sdk-cpp#436]
We have a QT qmake project and we would like import AWS C++ SDK to our project. 
We built aws-sdk release mode.

**Comment by JonathanHenson** [comment]
Here's how I'm using the SDK and QT via CMake, you should be able to find the analogs for your build system:

add_project(aws-cpp-sdk-s3-desktop-sync
"GUI application using the transfer manager"
aws-cpp-sdk-transfer
aws-cpp-sdk-s3
aws-cpp-sdk-s3-encryption
aws-cpp-sdk-kms
aws-cpp-sdk-core)

# Headers are included in the source so that they show up in Visual Studio.
# They are included elsewhere for consistency.

#find Qt and get the cmake variables necessary to use it.
find_package(Qt5Widgets REQUIRED)
set(CMAKE_INCLUDE_CURRENT_DIR ON)

include_directories(${Qt5Widgets_INCLUDE_DIRS})
include_directories("${CMAKE_CURRENT_SOURCE_DIR}/include")
include_directories("${CMAKE_CURRENT_SOURCE_DIR}/qt")

add_definitions(${Qt5Widgets_DEFINITIONS})
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${Qt5Widgets_EXECUTABLE_COMPILE_FLAGS}")

set(CMAKE_AUTOMOC ON)   

file(GLOB QT_GUI_SRC
    "qt/*.cpp"
)

file(GLOB QT_GUI_HEADERS
    "qt/*.h"
)
  
file(GLOB QT_GUI_RESOURCES
    "qt/*.qrc"
)

file(GLOB APP_HEADERS
    "include/aws/s3-desktop-sync/*.h"
)

file(GLOB ROOT_SRC
    "source/*.cpp"
)   

QT5_ADD_RESOURCES( RES_SOURCES ${QT_GUI_RESOURCES} )
QT5_WRAP_CPP( MOC_SRCS ${QT_GUI_HEADERS} )

include_directories(${CMAKE_CURRENT_BINARY_DIR})

file(GLOB ALL_SRC
    ${RES_SOURCES}
    ${QT_GUI_HEADERS}
    ${MOC_SRCS}
    ${QT_GUI_SRC}
    ${APP_HEADERS}
    ${ROOT_SRC}
)
   
add_executable(${PROJECT_NAME} ${ALL_SRC})
target_link_libraries(${PROJECT_NAME} ${PROJECT_LIBS} ${Qt5Widgets_LIBRARIES})
copyDlls(${PROJECT_NAME} ${PROJECT_LIBS})

if(WIN32) # Check if we are on Windows
SET(EXTENSION "dll")
SET(LIBPATH "so")
SET(QT_NAME "Qt5")
SET(DEBUG_EXTENSION "d")
SET(PREFIX "")
if(MSVC) # Check if we are using the Visual Studio compiler
  set_target_properties(${PROJECT_NAME} PROPERTIES
      WIN32_EXECUTABLE YES
      LINK_FLAGS "/ENTRY:mainCRTStartup"
)
elseif(CMAKE_COMPILER_IS_GNUCXX)
  # SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -mwindows") # Not tested
else()
  message(SEND_ERROR "You are using an unsupported Windows compiler! (Not MSVC or GCC)")
endif(MSVC)
elseif(APPLE)
SET(EXTENSION "framework")
SET(LIBPATH "lib")
SET(QT_NAME "Qt")
SET(DEBUG_EXTENSION ".dSYM")
SET(PREFIX "")
set_target_properties(${PROJECT_NAME} PROPERTIES
    MACOSX_BUNDLE YES
)
else()
SET(LIBPATH "lib")
SET(EXTENSION "so")
SET(PREFIX "lib")
SET(QT_NAME "Qt5")
# Nothing special required
endif(WIN32)

#copy QT binaries over to the executable's directory for dynamic linking
if(WIN32)
add_custom_command(TARGET aws-cpp-sdk-s3-desktop-sync POST_BUILD
                COMMAND ${CMAKE_COMMAND} -E copy_if_different
                "${_qt5Widgets_install_prefix}/${LIBPATH}/${PREFIX}${QT_NAME}Core${DEBUG_EXTENSION}.${EXTENSON}" ${CMAKE_CURRENT_BINARY_DIR}/$<CONFIGURATION>
                COMMAND ${CMAKE_COMMAND} -E copy_if_different
                "${_qt5Widgets_install_prefix}/${LIBPATH}/${PREFIX}${QT_NAME}Widgets${DEBUG_EXTENSION}.${EXTENSION}" ${CMAKE_CURRENT_BINARY_DIR}/$<CONFIGURATION>
                COMMAND ${CMAKE_COMMAND} -E copy_if_different
                "${_qt5Widgets_install_prefix}/${LIBPATH}/${PREFIX}${QT_NAME}Gui${DEBUG_EXTENSION}}.${EXTENSION}" ${CMAKE_CURRENT_BINARY_DIR}/$<CONFIGURATION>
                )
endif(WIN32)

set(SUFFIX "")
add_custom_command(TARGET aws-cpp-sdk-s3-desktop-sync POST_BUILD
                COMMAND ${CMAKE_COMMAND} -E copy_if_different
                "${_qt5Widgets_install_prefix}/${LIBPATH}/${PREFIX}${QT_NAME}Core${SUFFIX}.${EXTENSION}" ${CMAKE_CURRENT_BINARY_DIR}/$<CONFIGURATION>
                COMMAND ${CMAKE_COMMAND} -E copy_if_different
                "${_qt5Widgets_install_prefix}/${LIBPATH}/${PREFIX}${QT_NAME}Widgets${SUFFIX}.${EXTENSION}" ${CMAKE_CURRENT_BINARY_DIR}/$<CONFIGURATION>
                COMMAND ${CMAKE_COMMAND} -E copy_if_different
                "${_qt5Widgets_install_prefix}/${LIBPATH}/${PREFIX}${QT_NAME}Gui${SUFFIX}.${EXTENSION}" ${CMAKE_CURRENT_BINARY_DIR}/$<CONFIGURATION>
                )

add_custom_command(TARGET aws-cpp-sdk-s3-desktop-sync POST_BUILD
                COMMAND ${CMAKE_COMMAND} -E copy_directory
                "${CMAKE_CURRENT_SOURCE_DIR}/assets" ${CMAKE_CURRENT_BINARY_DIR}/$<CONFIGURATION>               
                )

**Comment by gkhanacer** [comment]
Thanks @JonathanHenson. I was able to do this with qmake in .pro file. Like:
`INCLUDEPATH += /usr/local/include/
LIBS += -L/usr/local/lib -laws-cpp-sdk-core -laws-cpp-sdk-s3 \
        -laws-cpp-sdk-cognito-sync -laws-cpp-sdk-cognito-idp -laws-cpp-sdk-cognito-identity \
        -laws-cpp-sdk-s3`

**Comment by aminkatani** [comment]
@gkhanacer  
So I'm also trying to include AWS SDK into my QT project. (Issue #885)
I try to install with make install but it doesn't work. 
Could you please help me with issue 885. I would really appreciate  #it.

**Comment by varmatangoit** [comment]
make itself is failing. could you please elaborate on the correct procedures or make a instructions video so that we could follow.
