### ISSUE TITLE
Is there any sample code to do Authentication with Congnito?

### ISSUE THREAD

**Issue by gkhanacer** [aws/aws-sdk-cpp#442]
In my desktop application, I need to create a login screen (login, forget password etc.). I searched developer guides and on the net, but I couldn't find any sample code to do this.
Could you help me for this issued?

**Comment by bretambrose** [comment]
For general service use questions (all the SDKs expose the same set of web APIs and what you need is guidance on resource creation and then what API calls to use in your code), we are pushing towards using Stack Overflow these days so that we can reserve the issues here for bugs and feature requests.  Try searching Stack Overflow (aws, cognito, etc... as keywords) and if you can't find anything, ask a question with the appropriate tags (aws-sdk, aws-cognito, amazon-cognito, etc...)

**Comment by chadbrewbaker** [comment]
@gkhanacer Check out https://pragprog.com/book/brapps/serverless-single-page-apps.  You should be able to translate the javascript into Qt, or use the Qt javascript engine to run the same code under Webkit.

The SDK-CPP should have integration/unit test to demonstrate logons. Take a look at the commented out https://github.com/aws/aws-sdk-cpp/blob/master/aws-cpp-sdk-cognitoidentity-integration-tests/IdentityPoolOperationTest.cpp#L263.  I think this could be vastly improved.

**Comment by JonathanHenson** [comment]
If you ware wanting to just use Cognito-Identity for federation, we've already done that for you. Check out aws-cpp-sdk-identity-management. 

If you are wanting to use Cognito-Idp with SRP, then we haven't added SRP support yet.

**Comment by atlascoder** [comment]
@JonathanHenson do you have any plans to add SRP to cpp sdk?

**Comment by jkoutavas** [comment]
Here's an SRP I've had some success with: https://github.com/drozhkov/aws-cpp-cognito-auth
