### ISSUE TITLE
Get content md5 from HeadObjectRequest

### ISSUE THREAD

**Issue by shuzhang1989** [aws/aws-sdk-cpp#459]
do we now support getting the Content-MD5 from HeadObject? 
it's documented officially here:
http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html#object-metadata

**Comment by shuzhang1989** [comment]
follow up - i get around it by parsing the http header by my self. an example pr:
https://github.com/pinterest/rocksplicator/pull/28

do you think it's worth a patch to the cpp sdk?

**Comment by JonathanHenson** [comment]
We should be supporting this out of the gate. I'll add it to the backlog at the top of the queue. Thanks for reaching out!

**Comment by shuzhang1989** [comment]
@JonathanHenson if you think getting md5 from http response header's etag (which is in the diff) is the correct way, i can do it. if you think there are better ways, never mind what i said :).

**Comment by JonathanHenson** [comment]
This should be in the metadata. So GetMetadata()["content-md5"]

**Comment by shuzhang1989** [comment]
Yes, currently is that GetMetadata() in get Header() returns me an empty dict.

**Comment by JonathanHenson** [comment]
GetHeader()?

Is GetMetadata() returning an empty map?

**Comment by shuzhang1989** [comment]
hmm, sorry not very clear.

i called HeadObject().GetResult().getMetadata(), it returns me an empty map.

**Comment by KaibaLopez** [comment]
Hi, 
I know it's an old issue but just in case this is still a problem. 
There's 2 things that I'd like to add to the answers:
- HeadObject().GetResult().getMetadata() returns a map of the meta data with prefix : "x-amz-meta", so it's not a where you'd look for this unless set manually on your s3 for the object.
- In order to get other metadata keys such as [Content-Type] there are other specific methods ( in that case HeadObject().GetResult().GetContentType() ) .

Anyways you seem to have found a work around on your own, so if there are no future comments on this I'll be closing the issue, feel free to comment if you need more info.
