### ISSUE TITLE
10 retries?

### ISSUE THREAD

**Issue by OlafvdSpek** [aws/aws-sdk-cpp#463]
My put example is failing with "Send request failed: The HTTP redirect request failed".
Does it really make sense to retry 10 times in this case?
Does it ever make sense to retry (10 times)?

**Comment by JonathanHenson** [comment]
that one shouldn't retry at all. we have a flag in the errors for what is retryable and what is not. That one needs to be fixed.

**Comment by OlafvdSpek** [comment]
What could be causing this error?

**Comment by JonathanHenson** [comment]
It's hard to tell without logs, but it looks like you are using the us standard region on a bucket that isn't in us-standard (e.g. us-east-1) For example, if the bucket is in us-west-2, you need to configure your client for that region. We should, handle 304 correctly, but apparently we aren't, it is getting retried, because the SDK is thinking that it is a network timeout. I'll add a story to our backlog to fix that. In the meantime, you can avoid the issue by configuring your client with the region of your bucket.

**Comment by asylvest** [comment]
Related question @JonathanHenson... what exactly does the current retry logic try to handle?  My understanding is that it definitely handles straight up HTTP request failures.  If there is successful HTTP communication but a service returns an error code, are you saying there are certain error codes that the SDK will automatically retry?  For example with S3, if I got an InternalError response (http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html), would the SDK automatically retry this for me or is my job as the caller to put a wrapper around the SDK to handle this?

I have intermittently seen InternalError responses from S3; I'm trying to figure out if I should code in some retry logic myself or if I should just bump up / customize the SDK's existing retry customization layer.

If the SDK does retry certain error codes automatically, does it key off of the HTTP status code or the error code in the table in the above link?  If there's a spot in the code you could point me to that does that logic, that would be helpful.

Thanks.

**Comment by marcomagdy** [comment]
It's keyed off the error codes/exception headers sent by AWS.
You can find a common list of errors in:
https://github.com/aws/aws-sdk-cpp/blob/master/aws-cpp-sdk-core/source/client/CoreErrors.cpp

And S3 specific errors can be found in:
https://github.com/aws/aws-sdk-cpp/blob/master/aws-cpp-sdk-s3/source/S3Errors.cpp

Note that the last boolean parameter determines whether this error is retry-able or not.

This does not answer your original question, but if you can provide logs, we could help you further.

**Comment by orinem** [comment]
This still happens and is a bug.

The error (ERROR_WINHTTP_REDIRECT_FAILED) comes from WinHttp.

If you turn logging on, extract the Url being used and post the Url manually, you get a 301 response with the following content:

```
<?xml version="1.0" encoding="UTF-8"?>
<Error>
    <Code>PermanentRedirect</Code>
    <Message>The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.</Message>
    <Endpoint>my-bucket.s3-us-west-2.amazonaws.com</Endpoint>
    <Bucket>my-bucket</Bucket>
    <RequestId>BC57F9FA4D7C7DE5</RequestId>
    <HostId>zJ36wH04X6KDt8LxVp3TDsF67olvRyOrqUuLwDww/ZXbNQte5e44pHyPdeDZXZvq6ivwmxkWlIA=</HostId>
</Error>
```

However, the S3 server does not return a "Location" header, so presumably, this is why WinHttp fails.

For FollowRedirectsPolicy of DEFAULT and ALWAYS, WinHttp is instructed to follow redirects... which are guaranteed to fail with the ERROR_WINHTTP_REDIRECT_FAILED since there is no Location header for WinHttp to follow.

Furthermore, it is almost always incorrect to allow WinHttp to follow redirects as it _is allowed to_ and _does_ convert POST into GET after a redirect.

One can get a slightly better result by setting FollowRedirectsPolicy to NEVER.  However, the most useful information, the Endpoint information is thrown away.

I will raise separate issues on both these points.
