### ISSUE TITLE
How to reach S3 bucket without specifying region

### ISSUE THREAD

**Issue by johnny-guo** [aws/aws-sdk-cpp#47]
I can get object in S3 bucket when specifying region in ClientConfiguration:

ClientConfiguration config;
config.scheme = Scheme::HTTPS;
config.connectTimeoutMs = 30000;
config.requestTimeoutMs = 30000;
config.region = Aws::Region::US_WEST_2;
Aws::S3::S3Client Client(config);

And I'm wondering whether there is a way to get the same object in S3 bucket without specifying the region, similar to java sdk. 

Thanks again for the great help!
Johnny

**Comment by JonathanHenson** [comment]
Sorry for the delay on this one. If you don't specify the correct region, S3 will send a redirect back. By default we have automatic following of redirects turned off. Have you tried turning on redirects in your clientConfig?

**Comment by johnny-guo** [comment]
Thanks, Jonathan. I did try to turn on redirect with:

config.followRedirects = true;

but I still to have error. Any idea how I get it wrong?

Thanks,
Johnny

**Comment by JonathanHenson** [comment]
I couldn't really tell you without the logs. If you could turn logging on at TRACE level and then upload the log. I could dive in a bit further.

**Comment by JonathanHenson** [comment]
So due to us using Sigv4 only with S3, the region has to be present. The old style redirect no longer works. Instead you would need to call HeadBucket on the bucket in question on the s3.amazonaws.com. From there it will return the region the bucket is in. At that point you can use the region to setup a client for communicating with that bucket. Please feel free to reopen if this is still an issue for you.
