### ISSUE TITLE
aws-cpp-sdk-transfer problem with upload file to s3 when target object key contains '?' sign 

### ISSUE THREAD

**Issue by Eliyahu-Machluf** [aws/aws-sdk-cpp#547]
Hi,

I tried to upload file to S3 using aws-cpp-sdk-transfer. when target object key contains '?' sign, the object key is being truncated.
i.e. I requested to upload a file to an object key named 'a?txt', file was uploaded, but the object key name was 'a' (i.e. the '?' and all other characters where truncated).
I tried also to give the url encoded string for '?' (%3F), but then I got an object key name was a%3Ftxt and not a?txt as I wanted

Eliyahu

**Comment by singku** [comment]
See #546

**Comment by Eliyahu-Machluf** [comment]
Hi,

According to http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html any utf8 characters are valid. there is recommendation not to use question mark, or url encode it, "The following characters in a key name may require additional code handling and will likely need to be URL encoded or referenced as HEX"

but I understand this is still a valid object key name. As the SDK shall support valid usage of S3, I think it shall be added the ability to support question mark at object name.

**Comment by singku** [comment]
Content after '?' is treated as url query string, so ? is not encoded. Users can encode the key's name by themselves, but on S3 you will see %3F, because SDK will encode it again, then in url it becames %253F. on S3's service end, it will treat it as %3F.  What you could do is to decode the key's name after you download it If you don't care about how it shows on S3.

**Comment by singku** [comment]
@Eliyahu-Machluf Hi, this has been solved.
