### ISSUE TITLE
Xml::XmlNode::GetAttributeValue crashed if attribute name is not available in Xml Node

### ISSUE THREAD

**Issue by PoundKey** [aws/aws-sdk-cpp#626]
Hello AWS C++ SDK Team:

Just found that Xml::XmlNode::GetAttributeValue crashed if attribute name is not available in Xml Node.
The root cause is this method:

```cpp
const Aws::String XmlNode::GetAttributeValue(const Aws::String& name) const
{
    return m_node->ToElement()->Attribute(name.c_str(), nullptr);
}
```

The issue might be due to nullptr is passed into Aws::String constructor when name is not found and causing undefined behavior.

In this case, nullptr should be changed to empty string and returned by the method instead of crashing.

Thanks.

**Comment by singku** [comment]
If name is not found, 0 will be returned by Attribute(), then GetAttributeValue() will try constructing a string with pointer 0, which caused segfault of accessing mem address 0. When you said nullptr should be changed to "", you mean the returned value of Attribute() instead of nullptr passed to this function in the above code right?

**Comment by PoundKey** [comment]
Yeah, `GetAttributeValue` should try to construct a empty string from the "" returned from `Attribute`

**Comment by singku** [comment]
Thanks for letting us know, will fix it soon.

**Comment by singku** [comment]
This has been fixed , will be pushed out later today
