### ISSUE TITLE
Why there is a partNumber in GetObjectRequest?

### ISSUE THREAD

**Issue by crusader-mike** [aws/aws-sdk-cpp#662]
It seems that you can specify [partNumber](https://github.com/aws/aws-sdk-cpp/blob/master/aws-cpp-sdk-s3/include/aws/s3/model/GetObjectRequest.h#L710) in GetObject request. What is the associated semantic -- can I download object piece-by-piece using this?

**Comment by marcomagdy** [comment]
Yes, you can.

**Comment by crusader-mike** [comment]
So, which byte range GetObjectRequest with partNumber =5 will retrieve? Where can I get such information (along with total number of parts)? I can't find anything in [documentation](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectGET.html)...

**Comment by marcomagdy** [comment]
This applies for multi-part uploads only. Specifically, multipart uploads that have neither completed nor aborted. 
Essentially, this allows you to download a part of an object you're uploading via multi-part upload. 

See http://docs.aws.amazon.com/AmazonS3/latest/dev/mpuoverview.html

**Comment by crusader-mike** [comment]
I see... Thank you.

Is there any way to implement multi-part download (that is download different parts of the same object in parallel) besides using GetObject with byte ranges?

**Comment by marcomagdy** [comment]
I don't think so. Range-get is the only way I'm aware of.

**Comment by vlovich** [comment]
To anyone else coming across this link, the explanation doesn't seem correct. AFAICT there's no way to access the contents of an in-progress upload. This should be pretty clear because the `GetObject` API does not take in an upload ID. So if a part number were referring to an incomplete/not aborted uploaded, which upload would that be? There could be several in flight at one time after all.

The part number in `GetObject` actually corresponds to the byte range of a published multipart upload. So if you published parts 1(10MB), 2(10MB), and 3(3MB) and ask for part 2, you'll get the byte range [10MB, 20MB).

What's not clear to me is what happens if you upload parts 1 3 & 7 and then ask for part 3. Do you get back part #3 that you uploaded or the third consecutive part contained within the file (i.e. part 7 in the upload). It's not hard to test but I'm lazy.
