### ISSUE TITLE
Using the sdk for windows store

### ISSUE THREAD

**Issue by systemKMP** [aws/aws-sdk-cpp#693]
Hello,
Is there currently a way to build the sdk for UWP? It seems that if we compile the sdk ourselves, or use the one provided with nuget, we to fail the verification step. Problem seems to stem from the sdk using windows api not allowed for UWP.

**Comment by wps132230** [comment]
Can you try cmake option `USE_IXML_HTTP_REQUEST_2`? It will let sdk use `IXmlHttpRequest2` API.

**Comment by systemKMP** [comment]
Same results. Supported api test gives me this: [https://pastebin.com/5CZeG0Lc](https://pastebin.com/5CZeG0Lc)

**Comment by marcomagdy** [comment]
>Is there currently a way to build the sdk for UWP?

Based on what I'm reading on msdn on [How to: Use Existing C++ Code in a Universal Windows Platform App](https://msdn.microsoft.com/en-us/library/mt186162.aspx), it seems that you would have to port the library to make it usable. Basically, all our usage of `std::iostream` would have to be replaced, because [Microsoft banned the APIs it uses under the hood](https://docs.microsoft.com/en-us/cpp/cppcx/crt-functions-not-supported-in-universal-windows-platform-apps).

**Comment by mlfarrell** [comment]
Wait what.. you can't use this SDK on windows store?  

This issue is over a year old.  Seriously???  come on guys
