### ISSUE TITLE
About S3 region

### ISSUE THREAD

**Issue by SubmarineX** [aws/aws-sdk-cpp#695]
These regions:

- us-east-1
- ca-central-1
- ap-northeast-2
- eu-west-2

mentioned in [Amazon Simple Storage Service (Amazon S3)](http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region) but not in [BucketLocationConstraint](https://github.com/aws/aws-sdk-cpp/blob/master/aws-cpp-sdk-s3/include/aws/s3/model/BucketLocationConstraint.h). Why is that?

**Comment by wps132230** [comment]
If the region is `us-east-1`, Amazon S3 returns an empty string for the bucket's region.
http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketGETlocation.html
Still taking a look why `ca-central-1`, `ap-northeast-2`, `eu-west-2` are not in `BucketLocationConstraint`.

**Comment by wps132230** [comment]
We are missing these region related enums because of the out-of-date [service model](https://github.com/aws/aws-sdk-cpp/blob/e8ff65d05acdce404ab8f83c1288dc41137ac571/code-generation/api-descriptions/s3-2006-03-01.normal.json#L1067) provided by S3.
Can I know your use case? It will not break your code in some cases, and you can use `Aws::S3::Model::BucketLocationConstraintMapper::GetBucketLocationConstraintForName("ca-central-1")` to static cast to `BucketLocationConstraint` and it will finally be static cast to String again when making request.

**Comment by wps132230** [comment]
Hi, we added these regions manually with this commmit: https://github.com/aws/aws-sdk-cpp/commit/e7a57cdd6932ab3804ed1038ba90416d7fa7cb4a.
You can find them in `BucketLocationConstraint` since version 1.2.21.
https://github.com/aws/aws-sdk-cpp/blob/4de9b52076632ee600d2f9d8e188146d3104790d/aws-cpp-sdk-s3/include/aws/s3/model/BucketLocationConstraint.h#L40
