### ISSUE TITLE
Exception safety in New

### ISSUE THREAD

**Issue by HowardHinnant** [aws/aws-sdk-cpp#707]
What happens if `T(std::forward<ArgTypes>(args)...)` throws an exception here:

https://github.com/aws/aws-sdk-cpp/blob/master/aws-cpp-sdk-core/include/aws/core/utils/memory/AWSMemory.h#L72

?

Looks like a memory leak to me.

**Comment by marcomagdy** [comment]
Hey Howard,
We make no guarantees in the SDK about exception safety because we target platforms that turn off exceptions anyways. So, to cater to the lowest common denominator, our CMake script adds `-fno-exceptions` flag on gcc/clang builds (AFAIK, MSVC doesn't have a way to completely turn off exceptions).

**Comment by HowardHinnant** [comment]
I see, my mistake.
