### ISSUE TITLE
Support for multipart upload via S3EncryptionClient

### ISSUE THREAD

**Issue by dyfrgi** [aws/aws-sdk-cpp#732]
In the blog post announcing the encrypted S3 client, it was mentioned that support for multipart upload to encrypted buckets is the next priority. As of yet, it is not supported (https://github.com/aws/aws-sdk-cpp/blob/master/aws-cpp-sdk-s3-encryption/source/s3-encryption/S3EncryptionClient.cpp#L129) Is there currently a timeline for Amazon to implement this feature, or any external contributor which plans to do so?

**Comment by JonathanHenson** [comment]
This proved to be a difficult task, since to do multiple parts in parallel, you'd need to recompute the initialization vectors for AES CBC. For AES CTR mode it would work (but we never PUT with AES CTR). For AES GCM, you'd need to compute the Hash as well (which AFAIK can't be easily done without computing it for the entire body. As a result, we simply turned off multipart put for S3 Encryption Client when used inside of TransferManager.

**Comment by dyfrgi** [comment]
I can certainly see how, if you're treating each file as a single message, AES CBC would be problematic. Given that you're using different write and read modes, am I right to assume that S3 re-encrypts for storage after the upload is complete? In that case, AES CBC would be fine for PUT with each part treated as a message and using its own IV. It'll eat more entropy but it's not like good PRNGs are that hard to come by, and are the standard today.

Is AES CTR simply not considered to be secure enough? It seems like the standard choice for parallel encryption.  If it's good enough for read I don't see why it wouldn't be for write as well. Just not yet supported on the server side?

**Comment by JonathanHenson** [comment]
CTR mode is for range gets and only in non-strict mode. We never put with it (since gcm is essentially CTR mode with a gmac attached to it) and we never use it to get an entire object.

It’s not that we can’t use CTR mode for put. It’s that if we did, it wouldn’t be compatible with the other clients (e.g. Java).

**Comment by JonathanHenson** [comment]
No s3 does not reencrypt. Server side encryption is a less useful feature, since if you have a bucket access issue (someone gains access to the bucket) the object can be downloaded unencrypted.
