### ISSUE TITLE
Versioning scheme (source/binary compatibility)

### ISSUE THREAD

**Issue by jwustrack-amadeus** [aws/aws-sdk-cpp#801]
Hello,

I would like to know if the versioning scheme of aws-sdk-cpp is linked to binary and/or source compatibility of the changes between releases.
More specifically are there any rules on which part (X, Y or Z) of the version (X.Y.Z) is bumped if the API changes (potentially requiring code changes in code using the library) or if a non-binary compatible change is introduced (requiring a recompilation of the binary using the library).

Thanks,
Jonas Wustrack

**Comment by marcomagdy** [comment]
The versioning is for source compatibility only. In a Major.Minor.Patch scheme, we bump "Minor" when we introduce source-breaking changes (in any of the services). We're reserving bumping "Major" to when we introduce holistic changes to the SDK. "Patch" is incremented with every backwards-compatible change.

Binary compatibility in C++ is tricky business (specially in a cross platform library) so we don't tie versioning to it because it depends on how the library is built (static or dynamic) and on which platform, whether custom allocators are used, etc.

**Comment by singku** [comment]
Closing this issue because it's has been answered by Marco. @jwustrack-amadeus please reopen if you have further questions.
