### ISSUE TITLE
Allow setting content length in transfer manager interface.

### ISSUE THREAD

**Issue by howryu** [aws/aws-sdk-cpp#839]
I am trying to put a custom iostream to a s3 bucket using transfer manager api (since it allows me to use multipart upload feature). However, it seems that transfer manager will call seekg and tellg on stream object to get size of the stream. In my case, I have not implemented the custom seekoff method to let tellg or seekg returning correct answer. Since I already know the size of my custom stream, I wonder if I can set content length directly on transfer manager interface?

**Comment by marcomagdy** [comment]
You can set the content-length if you use the S3 client directly. There's currently no way to do that in TransferManager, which I acknowledge is an oversight on our part since the interface to upload is a stream. Your best bet at this point is to either implement tellg and seekg or use the S3 client directly and set the content-length on the request object.

**Comment by howryu** [comment]
Right. I realized that and I switched to aws s3 client instead of transfer manager. Should have closed it. Thanks for response.
