### ISSUE TITLE
Add ability to clear CompletedPart vector in CompletedMultipartUpload

### ISSUE THREAD

**Issue by LarryMarg** [aws/aws-sdk-cpp#855]
### Can you provide a TRACE level log? (sanitize any sensitive information)  N/A

If I have a CompletedMultipartUpload as a class member, I'd like to free up memory by freeing the elements in CompletedPart following a CompleteMultipartUpload() or AbortMultipartUpload() call.

I propose adding to aws\s3\model\CompletedMultipartUpload.h:
```
    inline void ClearParts(void) { m_partsHasBeenSet = false; m_parts.clear(); }
```

P.S.  Do I need to be authorized to open a pull request?

**Comment by KaibaLopez** [comment]
Hi @LarryMarg ,
Sorry for the late response, I'm going through old issues and feature requests and noticed this one. 
I don't know if you're still interested in this but if so, could you specify the use case for the clear parts? 
Ah and no, you don't need to be authorized to open a pull request.

**Comment by LarryMarg** [comment]
Hi @KaibaLopez ,

The use case is as I described:

- a CompletedMultipartUpload is a class member
- a large file is uploaded
- CompleteMultipartUpload() (or AbortMultipartUpload() ) is done successfully
- It's desired to free up the memory tied up by m_parts, without deleting the object containing the CompletedMultipartUpload

**Comment by KaibaLopez** [comment]
Yea, and I get what you're saying, but I'm trying to see the value in doing that since I think there are easy ways around that, for example, the CompletedMultipartUpload default constructor creates an empty object, would it not be essentially the same to do something like?
```
CompletedMultipartUpload completedMultipartUploadEmpty;
CompletedMultipartUpload completedMultipartUpload;
        completedMultipartUpload.AddParts(completedPart1);
        ...
        completeMultipartUploadRequest.WithMultipartUpload(completedMultipartUpload);
completedMultipartUpload = completedMultipartUploadEmpty;
```
That being said, if you don't want to get around it, can you make a Pull request with the changes you suggest? I know it's our bad that it took this long to address this but It'd help to make it more visible if it's a pull request rather than just an issue.

Also, just to clarify, CompleteMultiPart (same for Abort) does not hold the object itself, it's a group of signals for each of the uploaded parts (a string, 2 bools and an int) that is meant to keep track of success or failure, so while yea it is definitely memory that maybe you'd want to clear up, it is not as big as the object being uploaded.
