### ISSUE TITLE
SQS SetWaitTimeSeconds() is flaky for values > ~5

### ISSUE THREAD

**Issue by bppnw** [aws/aws-sdk-cpp#962]
Hello All,

I've been fighting with SetWaitTimeSeconds() for a while.  When I set the value to <= 5, it works as expected - I see a wait time of N seconds and then it times out and returns. 👍

However, if I set the value to some larger number - say, 10 - then it goes into a Weird State where it will pause for a very long time, or perhaps indefinitely.  I haven't had the time to dig deep down into the system to determine where this is occurring, but it anyone has an answer off the top of their head, I'd appreciate it.  I do at least see that internally we're getting a timeout error from curl, but this seems like it would be expected (as no messages arrive during my wait time).

For example:

Aws::SQS::Model::ReceiveMessageRequest mreq;
mreq.SetWaitTimeSeconds(10); // Will wait forever.  5 works fine.

### What platform/OS are you using?
macOS 10.13.6 and SDK 1.4.5.

### What compiler are you using? what version?
native clan-902.0.39.2

### What's your CMake arguments?
-DCMAKE_BUILD_TYPE=Release -DBUILD_ONLY="iot;iot-data;dynamodb;sqs" -DCUSTOM_MEMORY_MANAGEMENT=0 -DBUILD_SHARED_LIBS=ON -DENABLE_TESTING=OFF -DCURL_INCLUDE_DIR=/opt/local/include/curl -DCURL_LIBRARY=/opt/local/lib/libcurl.dylib -DENABLE_COMMONCRYPTO_ENCRYPTION=OFF -DENABLE_OPENSSL_ENCRYPTION=ON

### Can you provide a TRACE level log? (sanitize any sensitive information)
[TRACE] 2018-09-12 17:54:18 CurlHttpClient [0x700008240000] HTTP/1.1 100 Continue
[TRACE] 2018-09-12 17:54:18 CurlHttpClient [0x700008240000] 
 ... note the 10 second interval ...
[ERROR] 2018-09-12 17:54:27 CurlHttpClient [0x700008240000] Curl returned error code 28
[DEBUG] 2018-09-12 17:54:27 CurlHandleContainer [0x700008240000] Releasing curl handle 0x7fbfae818600
[DEBUG] 2018-09-12 17:54:27 CurlHandleContainer [0x700008240000] Notified waiting threads.
[DEBUG] 2018-09-12 17:54:27 AWSClient [0x700008240000] Request returned error. Attempting to generate appropriate error codes from response
[WARN] 2018-09-12 17:54:27 AWSClient [0x700008240000] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.
[DEBUG] 2018-09-12 17:54:27 AWSClient [0x700008240000] Date header was not found in the response, can't attempt to detect clock skew
[DEBUG] 2018-09-12 17:54:27 AWSClient [0x700008240000] Server time is Thu, 13 Sep 2018 00:54:27 GMT, while client time is Thu, 13 Sep 2018 00:54:27 GMT
[INFO] 2018-09-12 17:54:27 CurlHandleContainer [0x700008240000] Cleaning up CurlHandleContainer.
[INFO] 2018-09-12 17:54:27 CurlHandleContainer [0x700008240000] Cleaning up CurlHandleContainer.
[DEBUG] 2018-09-12 17:54:27 CurlHandleContainer [0x700008240000] Cleaning up 0x7fbfae80c600
[DEBUG] 2018-09-12 17:54:27 CurlHandleContainer [0x700008240000] Cleaning up 0x7fbfae818600

**Comment by singku** [comment]
Thanks for reporting this problem. This information supplied is very helpful.
From your log I do see that `curl` returned error code `28`, which is request timeout. Note that the default http request timeout is 3 seconds. It can be adjusted in `ClientConfiguration`. If you didn't touch this setting then I think the problem is `curl` timeout before service timeout and returned without actual response from server. But it will return and the outcome should have `IsSuccess() == false`. So I don't quit get what do you mean here by `wait infinitely`, could you be more specific? Or could you please set the request timeout to be larger than 10 seconds and try it again?

**Comment by bppnw** [comment]
Thanks again for the quick reply!  What I meant by "pause for a very long time" is that although I have my wait time set to 10 seconds (for example), when I call SQSClient::ReceiveMessage(ReceiveMessageRequest), it will block in the call for a considerably longer time than 10 seconds before then returning an error.  My expectation with the long poll wait time is that it would wait up to this long and then return without an error (unless some error other than a timeout actually occurs).  I will try updating my client timeout as you suggest and report back later.

**Comment by bppnw** [comment]
Indeed, setting the ClientConfiguration::requestTimeoutMs to match the value I'm using in SetWaitTimeSeconds works around the issue.  For me and for now, this is fine.  However, I think the behavior observed when the client is timing out prior to the configured SetWaitTimeSeconds is dubious.  I would expect that otherwise "early" timeout conditions would be silently retried with updated wait times equal to the difference between the SetWaitTimeSeconds and the elapsed wall clock time.

**Comment by singku** [comment]
Note `SetWaitTimeSeconds` is inside the high level service request. AWSClient only sends out the low level http request and has no idea what's the high level service request looks like and shouldn't manipulate the high level service request data (here is the wait time). Also the wait time or curl time out is different with sqs's wait time on server side. They are irrelevant and shouldn't be adjusted according to each other's value.

I also wouldn't suggest you to retry the request, you better wait for service response then decide what to do. Otherwise, you might have repeated request sent to sqs because sqs is executing, just hasn't respond to you yet. And if sqs always timeout, your might stuck waiting there.

**Comment by bppnw** [comment]
Thank you again for the quick and helpful response, which makes sense.  Now that I understand the difference in semantics for the timeouts, I think I'm in the green.  As long as my rationale for increasing my client timeout seems reasonable to you for managing my total wait time & number of SQS requests.

**Comment by MrMoose** [comment]
I have just run into this on windows with 1.8.150.
Using 4 and below is OKish, using 5 and above not so much.
Alas, I cannot use the proposed solution with the CURL timeout as CURL doesn't seem to be used in Windows builds.
Meaning this issue is very real for me right now.

There's one weirdness about it though:
It used to work just fine with 5 seconds until a few weeks ago without me updating anything. Multiple projects, AWS accounts, regions, Queues, same code. No change. The issue popped up a few days ago when the Q polling started to misbehave. I investigated and eventually came here.
